"""
Carbon Bombs — 425 fossil fuel projects each capable of over 1 Gt CO2 over
their lifetime.

Source: https://github.com/dataforgoodfr/CarbonBombs (Data For Good), which
reproduces the dataset behind carbonbombs.org from the Kühne et al. paper plus
GEM's coal mine and oil & gas extraction trackers.

Provenance note that the map has to respect: only 330 of the 425 rows carry a
real asset coordinate from GEM. 92 are country centroids and 3 were placed by
hand. A centroid is not a facility location, so `precision` travels with every
feature and the map styles and filters on it. Dropping that distinction would
put 92 invented pins on the map.

Two other cautions from the upstream README, both left in the data rather than
silently smoothed over:
  - where a carbon bomb spans several extraction sites, the coordinate is the
    first site only, not the field's extent
  - company headquarters in company_data.csv were geocoded from addresses
    generated by ChatGPT. That file is deliberately not harvested here.
"""

import csv
import io

import requests

import discover

REPO = "dataforgoodfr/CarbonBombs"
PATH = "data_cleaned/carbon_bombs_data.csv"


def resolve():
    """Current raw URL and change signal. Never a pinned branch or path."""
    return discover.github_file(REPO, PATH)

PRECISION = {
    "GEM": "asset",              # real site coordinate
    "Manual": "asset_manual",    # placed by hand against a named site
    "Country CB": "country",     # country centroid — NOT a site location
}


def fetch():
    url, _ = resolve()
    r = requests.get(url, timeout=90)
    r.raise_for_status()
    rows = list(csv.DictReader(io.StringIO(r.text.lstrip("\ufeff"))))

    out = []
    for row in rows:
        lat, lon = row.get("Latitude"), row.get("Longitude")
        if not lat or not lon:
            continue

        origin = (row.get("Latitude_longitude_source") or "").strip()
        precision = PRECISION.get(origin, "unknown")

        gt = row.get("Potential_GtCO2_source_CB")
        out.append({
            "ident": row.get("GEM_id_source_GEM") or row["Carbon_bomb_name_source_CB"],
            "name": row["Carbon_bomb_name_source_CB"],
            "lon": lon,
            "lat": lat,
            "value": float(gt) if gt else None,
            "unit": "Gt CO₂ lifetime potential",
            "year": int(row["Carbon_bomb_start_year"]) if (row.get("Carbon_bomb_start_year") or "").isdigit() else None,
            "url": row.get("GEM_url_source_GEM") or None,
            "extra": {
                "precision": precision,
                "coord_origin": origin,
                "country": row.get("Country_source_CB"),
                "fuel": row.get("Fuel_type_source_CB"),
                "operator": row.get("Operators_source_GEM"),
                "parent": row.get("Parent_company_source_GEM"),
                "status": row.get("Status_lvl_1"),
            },
        })
    return out


if __name__ == "__main__":
    from collections import Counter
    rows = fetch()
    print(f"{len(rows)} carbon bombs")
    print("precision:", Counter(r["extra"]["precision"] for r in rows).most_common())
    print("total:", round(sum(r["value"] or 0 for r in rows)), "Gt CO₂")
