#!/usr/bin/env python3
"""Round 69 (26 September): the 250 largest banks by total assets, compiled from Wikidata, as a row under Banks and monetary power. Needs round 68 first (they run in name order). Upload to the culprits repo's patches folder. Safe to run twice."""
import base64, subprocess, sys, os, tempfile
NOTE = """
## Round 69 (26 September)

- largest_banks (asked 26 September: the owner's own layer of the world's
  largest banks): route geojsonlive reading culprits-tiles-more
  banks/largest.geojson, built weekly by scripts/largest_banks.py (round 69
  tiles patch) the way largest_companies.py builds the companies: Wikidata
  total assets (P2403), latest year per item, in dollars at the year's ECB or
  World Bank rate, the 250 largest that are a kind of bank (Q22687). Central
  and development banks are kept, with Wikidata's kinds on each; items that
  are not banks are listed in banks/largest.build.json. Filed first under
  Suppression > ... > Banks and monetary power. NOT LIVE (weekly copy).
- Checked in a browser with a test file: the row draws and its box shows
  every field. The real file appears after the tiles repo's refresh runs
  largest_banks (nightly, or by hand).
"""
DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IGExZjQ5NmQuLjdhYWMw
MTAgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMTIxMTEsNiAr
MTIxMTEsMTIgQEAgY29uc3QgT1RIRVJfTUFQUyA9IHsKICAgICAgIGZpbGVzOiBbeyBsYWJlbDog
IlRoZSA1MDAgbGFyZ2VzdCBjb21wYW5pZXMgYnkgcmV2ZW51ZSIsIHVybDogImh0dHBzOi8vd2Vs
Y29tZXRveW91cmdhbGF4eS5naXRodWIuaW8vY3VscHJpdHMtdGlsZXMtbW9yZS9jb21wYW5pZXMv
bGFyZ2VzdC5nZW9qc29uIiB9XSwKICAgICAgIGF0dHJpYnV0aW9uOiAiV2lraWRhdGEgKENDMCk7
IGV4Y2hhbmdlIHJhdGVzIGZyb20gdGhlIEV1cm9wZWFuIENlbnRyYWwgQmFuayBhbmQgdGhlIFdv
cmxkIEJhbmsiLAogICAgICAgbm90ZTogIkNvbXBpbGVkIGhlcmUgaW4gcGxhY2Ugb2YgRm9ydHVu
ZSdzIEdsb2JhbCA1MDAsIHdob3NlIHRlcm1zIGZvcmJpZCBjb3B5aW5nIGl0LiBFdmVyeSBjb21w
YW55IFdpa2lkYXRhIGdpdmVzIGEgdG90YWwgcmV2ZW51ZSBmb3IsIGF0IGl0cyBsYXRlc3QgeWVh
ciwgdHVybmVkIGludG8gVVMgZG9sbGFycyBhdCB0aGF0IHllYXIncyBhdmVyYWdlIHJhdGUgKHRo
ZSBFdXJvcGVhbiBDZW50cmFsIEJhbmsncywgb3IgZm9yIGN1cnJlbmNpZXMgaXQgZG9lcyBub3Qg
cHVibGlzaCwgdGhlIFdvcmxkIEJhbmsncyBvZmZpY2lhbCByYXRlKSwgYW5kIHRoZSA1MDAgbGFy
Z2VzdCB0aGF0IFdpa2lkYXRhIHNheXMgYXJlIGJ1c2luZXNzZXMuIEVhY2ggYm94IHNob3dzIGV2
ZXJ5dGhpbmcgZ2F0aGVyZWQ6IHJhbmssIHJldmVudWUgYXMgc3RhdGVkIGFuZCBpbiBkb2xsYXJz
LCB0aGUgcmF0ZSB1c2VkLCBoZWFkcXVhcnRlcnMsIGNvdW50cnksIGluZHVzdHJ5LCBlbXBsb3ll
ZXMsIGZvdW5kaW5nIGRhdGUsIHdlYnNpdGUsIHN0b2NrIGV4Y2hhbmdlLCBwYXJlbnQgYW5kIGNo
aWVmIGV4ZWN1dGl2ZSwgd2l0aCBhIGxpbmsgdG8gdGhlIFdpa2lkYXRhIHBhZ2UuIFdpa2lkYXRh
IGlzIGVkaXRlZCBieSBhbnlvbmUsIHNvIGEgZmlndXJlIGNhbiBiZSBvdXQgb2YgZGF0ZSBvciB3
cm9uZzsgdGhlIGxpbmsgc2hvd3Mgd2hlcmUgaXQgY2FtZSBmcm9tLiBBIGNvbXBhbnkgd2hvc2Ug
aGVhZHF1YXJ0ZXJzIGhhcyBubyBwb3NpdGlvbiBpbiBXaWtpZGF0YSBpcyBsaXN0ZWQgaW4gdGhl
IGJ1aWxkIGZpbGUsIG5vdCBwbGFjZWQuIFJlYnVpbHQgd2Vla2x5IGJ5IGN1bHByaXRzLXRpbGVz
LW1vcmUuIiB9LAorICAgIC8vIEFza2VkIGZvciAyNiBTZXB0ZW1iZXIgKHJvdW5kIDY5KTogdGhl
IG93bmVyJ3Mgb3duIGxpc3Qgb2YgdGhlIHdvcmxkJ3MKKyAgICAvLyBsYXJnZXN0IGJhbmtzLCBj
b21waWxlZCB0aGUgd2F5IHRoZSBjb21wYW5pZXMgcm93IGlzLgorICAgIHsgaWQ6ICJsYXJnZXN0
X2JhbmtzIiwgbmFtZTogIlRoZSAyNTAgbGFyZ2VzdCBiYW5rcyBieSB0b3RhbCBhc3NldHMgKGNv
bXBpbGVkIGZyb20gV2lraWRhdGEpIiwgdW5pdDogImJhbmtzLCBhdCB0aGVpciBoZWFkcXVhcnRl
cnMiLCBjb2xvdXI6ICIjNkE1RDZCIiwgcm91dGU6ICJnZW9qc29ubGl2ZSIsIHJlYWR5OiB0cnVl
LCBsYXp5OiB0cnVlLAorICAgICAgZmlsZXM6IFt7IGxhYmVsOiAiVGhlIDI1MCBsYXJnZXN0IGJh
bmtzIGJ5IHRvdGFsIGFzc2V0cyIsIHVybDogImh0dHBzOi8vd2VsY29tZXRveW91cmdhbGF4eS5n
aXRodWIuaW8vY3VscHJpdHMtdGlsZXMtbW9yZS9iYW5rcy9sYXJnZXN0Lmdlb2pzb24iIH1dLAor
ICAgICAgYXR0cmlidXRpb246ICJXaWtpZGF0YSAoQ0MwKTsgZXhjaGFuZ2UgcmF0ZXMgZnJvbSB0
aGUgRXVyb3BlYW4gQ2VudHJhbCBCYW5rIGFuZCB0aGUgV29ybGQgQmFuayIsCisgICAgICBub3Rl
OiAiQ29tcGlsZWQgaGVyZSBmcm9tIG9wZW4gZGF0YSByYXRoZXIgdGhhbiBjb3BpZWQgZnJvbSBh
IHB1Ymxpc2hlZCByYW5raW5nLiBFdmVyeSBpdGVtIFdpa2lkYXRhIGdpdmVzIGEgdG90YWwgYXNz
ZXRzIGZpZ3VyZSBmb3IsIGF0IGl0cyBsYXRlc3QgeWVhciwgdHVybmVkIGludG8gVVMgZG9sbGFy
cyBhdCB0aGF0IHllYXIncyBhdmVyYWdlIHJhdGUgKHRoZSBFdXJvcGVhbiBDZW50cmFsIEJhbmsn
cywgb3IgZm9yIGN1cnJlbmNpZXMgaXQgZG9lcyBub3QgcHVibGlzaCwgdGhlIFdvcmxkIEJhbmsn
cyBvZmZpY2lhbCByYXRlKSwgYW5kIHRoZSAyNTAgbGFyZ2VzdCB0aGF0IFdpa2lkYXRhIHNheXMg
YXJlIGEga2luZCBvZiBiYW5rLiBDZW50cmFsIGJhbmtzLCBkZXZlbG9wbWVudCBiYW5rcyBhbmQg
dGhlIHJlc3QgYXJlIGFsbCBrZXB0LCBlYWNoIGJveCBzYXlpbmcgd2hhdCBraW5kIG9mIGJhbmsg
V2lraWRhdGEgY2FsbHMgaXQuIFllYXJzIGNhbiBkaWZmZXIgZnJvbSBiYW5rIHRvIGJhbms7IGVh
Y2ggYm94IGdpdmVzIHRoZSB5ZWFyIG9mIGl0cyBmaWd1cmUuIEVhY2ggYm94IHNob3dzIGV2ZXJ5
dGhpbmcgZ2F0aGVyZWQ6IHJhbmssIHRvdGFsIGFzc2V0cyBhcyBzdGF0ZWQgYW5kIGluIGRvbGxh
cnMsIHRoZSByYXRlIHVzZWQsIGtpbmQsIGhlYWRxdWFydGVycywgY291bnRyeSwgZW1wbG95ZWVz
LCBmb3VuZGluZyBkYXRlLCB3ZWJzaXRlLCBzdG9jayBleGNoYW5nZSwgcGFyZW50LCBvd25lciBh
bmQgY2hpZWYgZXhlY3V0aXZlLCB3aXRoIGEgbGluayB0byB0aGUgV2lraWRhdGEgcGFnZS4gV2lr
aWRhdGEgaXMgZWRpdGVkIGJ5IGFueW9uZSwgc28gYSBmaWd1cmUgY2FuIGJlIG91dCBvZiBkYXRl
IG9yIHdyb25nOyB0aGUgbGluayBzaG93cyB3aGVyZSBpdCBjYW1lIGZyb20uIEEgYmFuayB3aG9z
ZSBoZWFkcXVhcnRlcnMgaGFzIG5vIHBvc2l0aW9uIGluIFdpa2lkYXRhIGlzIGxpc3RlZCBpbiB0
aGUgYnVpbGQgZmlsZSwgbm90IHBsYWNlZC4gUmVidWlsdCB3ZWVrbHkgYnkgY3VscHJpdHMtdGls
ZXMtbW9yZS4iIH0sCiAgICAgeyBpZDogInRoZXlydWxlIiwgbmFtZTogIlRoZXkgUnVsZSIsIHVu
aXQ6ICJvcGVucyB0aGUgcGFnZSBpdHNlbGYgaW4gYSBwYW5lbCIsIGNvbG91cjogIiM2QTYyNTgi
LCByb3V0ZTogImNvbXBhbmlvbiIsIHJlYWR5OiB0cnVlLCBsYXp5OiB0cnVlLAogICAgICAgcGFn
ZTogImh0dHBzOi8vdGhleXJ1bGUubmV0LyIsCiAgICAgICBub3RlOiAiVGhlIHBhZ2UgYXMgdGhl
IHNpdGUgc2hvd3MgaXQsIHdob2xlLCBpbiB0aGUgcGFuZWwgYWxvbmcgdGhlIGJvdHRvbTsgaXRz
IGRhdGEgY2Fubm90IGJlIHJlYWQgZGlyZWN0bHkgdG8gZHJhdyBoZXJlLiIgfSwKQEAgLTEyODA2
LDYgKzEyODEyLDcgQEAgY29uc3QgTEFZRVJfS0lORCA9IHsKICAgZGZmOiBbInBsYW50IiwgInVw
c3RyZWFtIl0sCiAgIGZvcmVzdF9tYW5hZ2VtZW50OiBbInBsYW50IiwgImRvd25zdHJlYW0iXSwK
ICAgbGFyZ2VzdF9jb21wYW5pZXM6IFsiaHVtYW4iLCAidXBzdHJlYW0iXSwKKyAgbGFyZ2VzdF9i
YW5rczogWyJodW1hbiIsICJ1cHN0cmVhbSJdLAogICB0aGV5cnVsZTogWyJodW1hbiIsICJ1cHN0
cmVhbSJdLAogICBwZV9iYW5rcm9sbGluZzogWyJhbmltYWwiLCAidXBzdHJlYW0iXSwKICAgcGVf
YmFua3M6IFsiYW5pbWFsIiwgInVwc3RyZWFtIl0sCkBAIC0xMzQyOSw2ICsxMzQzNiw3IEBAIGNv
bnN0IExBWUVSX1NJVEUgPSB7CiAgIGZpbmFsX25haWw6ICJodHRwczovL2ZpbmFsbmFpbC5jb20v
d3AtanNvbi93cGdtemEvdjEvZmVhdHVyZXMvIiwKICAgZmlzaGluZzogImh0dHBzOi8vZ2xvYmFs
ZmlzaGluZ3dhdGNoLm9yZyIsCiAgIGxhcmdlc3RfY29tcGFuaWVzOiAiaHR0cHM6Ly9xdWVyeS53
aWtpZGF0YS5vcmciLAorICBsYXJnZXN0X2JhbmtzOiAiaHR0cHM6Ly9xdWVyeS53aWtpZGF0YS5v
cmciLAogICBmcmFjdHJhY2tlcl9yZWZpbmVyaWVzOiAiaHR0cHM6Ly93d3cuZnJhY3RyYWNrZXIu
b3JnIiwKICAgZ2VtX2NvYWw6ICJodHRwczovL2dpdGh1Yi5jb20vR3JlZW5JbmZvLU5ldHdvcmsv
Y29hbC10cmFja2VyLWNsaWVudCIsCiAgIGdmd19jYXRhbG9ndWU6ICJodHRwczovL2RhdGEtYXBp
Lmdsb2JhbGZvcmVzdHdhdGNoLm9yZyIsCkBAIC0xMzYyMCw2ICsxMzYyOCw3IEBAIGNvbnN0IE5P
VF9MSVZFID0gewogICBzb2lsX3NwdW46ICJDb3BpZWQgb25jZSBmcm9tIHRoZSBVbmRlcmdyb3Vu
ZCBBdGxhcyBkYXRhIHJlY29yZCAoWmVub2RvIDEwLjUyODEvemVub2RvLjE0ODcxNTg4KSIsCiAg
IHNvaWxfbmVtYXRvZGVzOiAiQ29waWVkIGZyb20gaXRzIGZpZ3NoYXJlIGRhdGEgcmVjb3JkOyBj
b3BpZWQgYWdhaW4gb25seSB3aGVuIGEgZmlsZSBjaGFuZ2VzIiwKICAgbGFyZ2VzdF9jb21wYW5p
ZXM6ICJDb21waWxlZCB3ZWVrbHkgZnJvbSBXaWtpZGF0YSBieSBjdWxwcml0cy10aWxlcy1tb3Jl
IiwKKyAgbGFyZ2VzdF9iYW5rczogIkNvbXBpbGVkIHdlZWtseSBmcm9tIFdpa2lkYXRhIGJ5IGN1
bHByaXRzLXRpbGVzLW1vcmUiLAogICBjb2FzdGFsX2NsZWFudXA6ICJPY2VhbiBDb25zZXJ2YW5j
eSdzIGNsZWFudXAgc2l0ZXMsIGZyb20gYSBjb3B5IG1hZGUgZGFpbHkgKHRoZWlyIHNlcnZlciBs
ZXRzIG9ubHkgdGhlaXIgb3duIHNpdGUgcmVhZCBpdCkiLAogICBmb29kX3NveTogIkJ1aWx0IG9u
Y2UgZnJvbSB0aGUgMjAxNyBkYXRhIHBhY2thZ2Ugb2YgSGFscGVybiBldCBhbC4gMjAyMjsgaXQg
aXMgbm90IHVwZGF0ZWQiLAogICB3YXN0ZXdhdGVyX3BsdW1lczogIkJ1aWx0IG9uY2UgZnJvbSB0
aGUgR2xvYmFsIFdhc3Rld2F0ZXIgTW9kZWwncyAyMDIxIGRhdGEgcGFja2FnZTsgaXQgaXMgbm90
IHVwZGF0ZWQiLApAQCAtMTM4NDMsNyArMTM4NTIsNyBAQCBjb25zdCBQQU5FTF9PUkRFUiA9IFsK
ICAgeyBoOiAyLCB0OiAiT2YgaHVtYW5zIiB9LAogICB7IGg6IDMsIHQ6ICJQaHlzaWNhbCBzdXBw
cmVzc2lvbiIgfSwKICAgeyBoOiA0LCB0OiAiQ29udHJvbCBvZiBwaHlzaWNhbCByZXNvdXJjZXMi
IH0sCi0gIHsgaDogNSwgdDogIkJhbmtzIGFuZCBtb25ldGFyeSBwb3dlciIgfSwgInNpdGVfY2Vu
dHJhbF9iYW5rcyIsICJzaXRlX2JhbmtpbmdfZHluYXN0aWVzIiwgInNpdGVfYmFua2luZ19keW5h
c3RpZXNfY2hhcnRzIiwgInBvbGljeV9yYXRlcyIsICJpbWJhbGFuY2VzIiwgImNmcl90cmFja2Vy
IiwgInRhYmxlYXVfenNmIiwgInNpdGVfZXhwb3J0X2NyZWRpdCIsICJ0cm91dHdvb2QiLAorICB7
IGg6IDUsIHQ6ICJCYW5rcyBhbmQgbW9uZXRhcnkgcG93ZXIiIH0sICJsYXJnZXN0X2JhbmtzIiwg
InNpdGVfY2VudHJhbF9iYW5rcyIsICJzaXRlX2JhbmtpbmdfZHluYXN0aWVzIiwgInNpdGVfYmFu
a2luZ19keW5hc3RpZXNfY2hhcnRzIiwgInBvbGljeV9yYXRlcyIsICJpbWJhbGFuY2VzIiwgImNm
cl90cmFja2VyIiwgInRhYmxlYXVfenNmIiwgInNpdGVfZXhwb3J0X2NyZWRpdCIsICJ0cm91dHdv
b2QiLAogICB7IGg6IDUsIHQ6ICJUcmFkZSIgfSwgInJ0ZV90cmFkZSIsICJzaXRlX3RyYWRlX3By
b2ZpdHMiLCAiZ3RhX2FjdHMiLAogICB7IGg6IDUsIHQ6ICJGdW5kaW5nIG9mIGludGVybmF0aW9u
YWwgYm9kaWVzIiB9LCAic2l0ZV9lYXJtYXJrZWRfZnVuZGluZyIsCiAgIHsgaDogNCwgdDogIkVj
b25vbWljIGluZXF1YWxpdHkgd2l0aGluIGl0IiB9LApkaWZmIC0tZ2l0IGEvbWFwL2luZGV4Lmh0
bWwgYi9tYXAvaW5kZXguaHRtbAppbmRleCBiZmYyMGYwLi5hMTI1NGRlIDEwMDY0NAotLS0gYS9t
YXAvaW5kZXguaHRtbAorKysgYi9tYXAvaW5kZXguaHRtbApAQCAtNTE4LDcgKzUxOCw3IEBACiAg
IH07CiB9KSgpOwogPC9zY3JpcHQ+Ci08c2NyaXB0IHNyYz0iLi9hcHAuanM/dj02OCI+PC9zY3Jp
cHQ+Cis8c2NyaXB0IHNyYz0iLi9hcHAuanM/dj02OSI+PC9zY3JpcHQ+CiA8c2NyaXB0IHNyYz0i
Li93aXJlLmpzP3Y9NjciPjwvc2NyaXB0PgogPCEtLSBUaGUgZHJhZyBiYXIgb24gdGhlIGxheWVy
cyBib3gncyByaWdodCBlZGdlIChtYWRlIGJ5IGNvbHVtbkVkZ2UoKSBpbgogICAgICBhcHAuanMp
IHJhbiB0aGUgZnVsbCBoZWlnaHQgb2YgdGhlIGNvbHVtbiwgc28gaXQgc3RheWVkIHN0YW5kaW5n
IGJlc2lkZQpkaWZmIC0tZ2l0IGEvbWFwL3Rlc3QubWpzIGIvbWFwL3Rlc3QubWpzCmluZGV4IDIy
NWNjN2YuLmE2MjFkNTYgMTAwNjQ0Ci0tLSBhL21hcC90ZXN0Lm1qcworKysgYi9tYXAvdGVzdC5t
anMKQEAgLTMzODcsNiArMzM4NywxMCBAQCBjb25zb2xlLmxvZygiXG5yb3VuZCBvZiAyMyBTZXB0
ZW1iZXIgKDUpOiB0aGUgQXRsYXMgcGFuZWwgcGFyZWQgZG93bjsgbm8gZ3JhaW47CiAgIGNoZWNr
KCJhIHB1bGwgc2V0cyB0aGUgbW9zdCBhIGJveCBzaG93cywgc28gaXQgaXMgbmV2ZXIgdGFsbGVy
IHRoYW4gaXRzIGxpc3QgYW5kIHRoZSBsYXllcnMgYm94IHN0aWxsIGdpdmVzIHdheSB0byB0aGUg
U2hvd2luZyBib3ggKHJvdW5kIDY2KSIsCiAgICAgICAgIC9lbFwuc3R5bGVcLm1heEhlaWdodCA9
IGggXCsgInB4IjsvLnRlc3Qoc3JjKSAmJiAhL2VsXC5zdHlsZVwuZmxleCA9ICIwIDAgYXV0byI7
Ly50ZXN0KHNyYykgJiYgL1wubGVmdC1jb2wgXC5wYW5lbFx7ZmxleDowIDEgYXV0b1x9Ly50ZXN0
KGZzLnJlYWRGaWxlU3luYyhwYXRoLmpvaW4oSEVSRSwgImluZGV4Lmh0bWwiKSwgInV0ZjgiKSkg
JiYKICAgICAgICAgL1wubGVmdC1jb2wgXC5wYW5lbCA+IFwucHVsbC1ncmlwXHtwb3NpdGlvbjpz
dGlja3k7Ym90dG9tOjAvLnRlc3QoZnMucmVhZEZpbGVTeW5jKHBhdGguam9pbihIRVJFLCAiaW5k
ZXguaHRtbCIpLCAidXRmOCIpKSk7CisgIGNoZWNrKCJ0aGUgbGFyZ2VzdCBiYW5rcyByb3cgcmVh
ZHMgaXRzIHdlZWtseSBjb3B5LCBmaWxlZCB1bmRlciBCYW5rcyBhbmQgbW9uZXRhcnkgcG93ZXIg
KHJvdW5kIDY5KSIsCisgICAgICAgIC9pZDogImxhcmdlc3RfYmFua3MiLCBuYW1lOiAiVGhlIDI1
MCBsYXJnZXN0IGJhbmtzIGJ5IHRvdGFsIGFzc2V0cyBcKGNvbXBpbGVkIGZyb20gV2lraWRhdGFc
KSJbXlxuXSpyb3V0ZTogImdlb2pzb25saXZlIi8udGVzdChzcmMpICYmCisgICAgICAgIC9jdWxw
cml0cy10aWxlcy1tb3JlXC9iYW5rc1wvbGFyZ2VzdFwuZ2VvanNvbi8udGVzdChzcmMpICYmIC8i
QmFua3MgYW5kIG1vbmV0YXJ5IHBvd2VyIiBcfSwgImxhcmdlc3RfYmFua3MiLy50ZXN0KHNyYykg
JiYKKyAgICAgICAgL2xhcmdlc3RfYmFua3M6ICJDb21waWxlZCB3ZWVrbHkgZnJvbSBXaWtpZGF0
YS8udGVzdChzcmMpKTsKICAgY2hlY2soInRoZSB3YXRlcnNoZWRzIGFyZSBzaGFkZWQgaW4gc3Rl
cHMgb2YgdGVuLCB3aXRoIGEga2V5IChyb3VuZCA2NykiLAogICAgICAgICAvbG9nU3RlcHM6IFxb
MWU1LCAxZTYsIDFlNywgMWU4LCAxZTksIDFlMTBcXS8udGVzdChzcmMpICYmIC9jb25zdCBicmVh
a3MgPSBcKGNmZ1wubG9nU3RlcHMgXHxcfC8udGVzdChzcmMpICYmIC9ub25lIHRvIFwkXHtsYWJc
KGJyZWFrc1xbMFxdXClcfS8udGVzdChzcmMpKTsKICAgY2hlY2soInRoZSBDb3VudHJ5IG91dGxp
bmVzIGJhc2VtYXAga2VlcHMgaXRzIG93biBjb2xvdXJzIChyb3VuZCA2NikiLCAvXHxzYXQtcmVs
aWVmLWNvbG91clx8b3V0bGluZS1cLlwqXClcJFwvOy8udGVzdChzcmMpKTsK
""")
def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True)
if not os.path.exists("map/app.js"):
    sys.exit("Run this from the culprits folder.")
with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
    f.write(DIFF); path = f.name
if git("apply", "--check", "-R", path).returncode == 0:
    print("Already applied. Nothing changed.")
else:
    r = git("apply", "--3way", path)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        git("checkout", "--", "map/app.js", "map/test.mjs", "map/index.html", "map/wire.js", "map/wire.test.mjs")
        sys.exit("Did not apply; nothing changed.")
    print("Code changes applied.")
os.unlink(path)
if os.path.exists("HANDOFF.md"):
    h = open("HANDOFF.md", encoding="utf-8").read()
    if "## Round 69 (26 September)" not in h:
        i = h.index("---") + 3
        open("HANDOFF.md", "w", encoding="utf-8").write(h[:i] + "\n" + NOTE + h[i:])
        print("HANDOFF.md note added.")
