#!/usr/bin/env python3
"""Round 65 (26 September): the banking dynasties row names its 11 added cities; the Showing box keeps a kind apart from its count. Needs round 64 first (they run in name order). Upload to the culprits repo's patches folder. Safe to run twice."""
import base64, subprocess, sys, os, tempfile
NOTE = """
## Round 65 (26 September)

- Banking dynasties: the 11 family-city pairs the section lists without a
  coordinate (so its own map never plots them) are added hollow at the city
  by culprits-tiles-more scripts/dynasty_cities.py (round 65 tiles patch):
  OpenStreetMap's position for the city and its country, the family's colour
  as the ring, and a box saying it is placed at the city. Runs with the
  refresh; a pair already added is left alone.
- legendKeyPairs joins a key's parts with a space (the building kinds read
  "Banks382,338").
- Browser check with the latest culprits-tiles-more files: Global Trade Alert,
  Buildings, space industry, upcoming launches, published aggregate findings,
  Hotspot Cities (33 placed), oil slick archive, vessels of concern, Trase
  measures and facilities, materials research, Coastal Cleanup, Waste Atlas
  cities and the soybean companies all draw. Wreckers of the Earth waits for
  umap_copy's first nightly run.
"""
DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDM5MDVmNzMuLjkzMTFm
ODcgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMTExNjQsNyAr
MTExNjQsOSBAQCBmdW5jdGlvbiBsZWdlbmRLZXlQYWlycyhpZCkgewogICAgICAgY29uc3QgY29s
b3VyID0gZWwuc3R5bGUgJiYgKGVsLnN0eWxlLmJhY2tncm91bmRDb2xvciB8fCBlbC5zdHlsZS5i
YWNrZ3JvdW5kKTsKICAgICAgIGlmICghY29sb3VyIHx8IC9eKG5vbmV8dHJhbnNwYXJlbnQpJC9p
LnRlc3QoY29sb3VyKSkgY29udGludWU7CiAgICAgICBjb25zdCBob2xkZXIgPSBlbC5jbG9zZXN0
KCIuc20ta2V5LCBidXR0b24sIC5sZy1yb3csIGxhYmVsLCBsaSIpIHx8IGVsLnBhcmVudE5vZGU7
Ci0gICAgICBjb25zdCBsYWJlbCA9IFN0cmluZygoaG9sZGVyICYmIGhvbGRlci50ZXh0Q29udGVu
dCkgfHwgIiIpLnJlcGxhY2UoL1xzKy9nLCAiICIpLnRyaW0oKTsKKyAgICAgIC8vIEl0cyBwYXJ0
cycgd29yZHMgd2l0aCBhIHNwYWNlIGJldHdlZW4gKGEga2luZCBhbmQgaXRzIGNvdW50IHJhbiB0
b2dldGhlcikuCisgICAgICBjb25zdCBwYXJ0cyA9IGhvbGRlciAmJiBob2xkZXIuY2hpbGROb2Rl
cyAmJiB0eXBlb2YgaG9sZGVyLmNoaWxkTm9kZXNbU3ltYm9sLml0ZXJhdG9yXSA9PT0gImZ1bmN0
aW9uIiA/IFsuLi5ob2xkZXIuY2hpbGROb2Rlc10gOiBudWxsOworICAgICAgY29uc3QgbGFiZWwg
PSBTdHJpbmcocGFydHMgPyBwYXJ0cy5tYXAoKG4pID0+IG4udGV4dENvbnRlbnQgfHwgIiIpLmpv
aW4oIiAiKSA6IChob2xkZXIgJiYgaG9sZGVyLnRleHRDb250ZW50KSB8fCAiIikucmVwbGFjZSgv
XHMrL2csICIgIikudHJpbSgpOwogICAgICAgaWYgKCFsYWJlbCB8fCBzZWVuLmhhcyhjb2xvdXIg
KyAifCIgKyBsYWJlbCkpIGNvbnRpbnVlOwogICAgICAgc2Vlbi5hZGQoY29sb3VyICsgInwiICsg
bGFiZWwpOwogICAgICAgb3V0LnB1c2goW2NvbG91ciwgbGFiZWxdKTsKQEAgLTExNjA3LDcgKzEx
NjA5LDcgQEAgY29uc3QgU0lURV9NQVBTID0gewogICAgIHsgaWQ6ICJzaXRlX2NlbnRyYWxfYmFu
a3MiLCBuYW1lOiAiQ2VudHJhbCBCYW5rcyIsIHVuaXQ6ICJiYW5rcyIsIGNvbG91cjogIiM1QzY1
NzAiLCByb3V0ZTogInNpdGVtYXAiLCByZWFkeTogdHJ1ZSwgbGF6eTogdHJ1ZSwgZGF0YVVybDog
Imh0dHBzOi8vd2VsY29tZXRveW91cmdhbGF4eS5naXRodWIuaW8vY3VscHJpdHMtdGlsZXMtbW9y
ZS9zaXRlbWFwcy9zaXRlX2NlbnRyYWxfYmFua3MucGxhY2VzLmdlb2pzb24iLAogICAgICAgbm90
ZTogIkZyb20gdGhlIFN1cHByZXNzaW9uIHBhZ2UncyBjZW50cmFsIGJhbmtzIG1hcC4iIH0sCiAg
ICAgeyBpZDogInNpdGVfYmFua2luZ19keW5hc3RpZXMiLCBuYW1lOiAiR2xvYmFsIEJhbmtpbmcg
RHluYXN0aWVzIiwgdW5pdDogImR5bmFzdHkgc2VhdHMiLCBjb2xvdXI6ICIjNkE1RDZCIiwgcm91
dGU6ICJzaXRlbWFwIiwgcmVhZHk6IHRydWUsIGxhenk6IHRydWUsIGRhdGFVcmw6ICJodHRwczov
L3dlbGNvbWV0b3lvdXJnYWxheHkuZ2l0aHViLmlvL2N1bHByaXRzLXRpbGVzLW1vcmUvc2l0ZW1h
cHMvc2l0ZV9iYW5raW5nX2R5bmFzdGllcy5wbGFjZXMuZ2VvanNvbiIsCi0gICAgICBub3RlOiAi
RnJvbSB0aGUgU3VwcHJlc3Npb24gcGFnZSdzIGJhbmtpbmcgZHluYXN0aWVzIG1hcC4iIH0sCisg
ICAgICBub3RlOiAiRnJvbSB0aGUgU3VwcHJlc3Npb24gcGFnZSdzIGJhbmtpbmcgZHluYXN0aWVz
IG1hcDogZXZlcnkgcGxhY2UgaXQgcGxvdHMsIGFuZCAocm91bmQgNjUpIHRoZSAxMSBjaXRpZXMg
aXRzIGxpc3QgZ2l2ZXMgYSBmYW1pbHkgd2l0aG91dCBhIGNvb3JkaW5hdGUsIGRyYXduIGhvbGxv
dyBhdCB0aGUgY2l0eSBhcyBPcGVuU3RyZWV0TWFwIHBsYWNlcyBpdC4iIH0sCiAgICAgeyBpZDog
InNpdGVfYmFua2luZ19keW5hc3RpZXNfY2hhcnRzIiwgbmFtZTogIkdsb2JhbCBCYW5raW5nIER5
bmFzdGllczogdGltZWxpbmUgYW5kIGNvbXBhcmlzb25zIiwgdW5pdDogIm9wZW5zIHRoZSBwYWdl
IGl0c2VsZiBpbiBhIHBhbmVsIiwgY29sb3VyOiAiIzZBNUQ2QiIsIHJvdXRlOiAiY29tcGFuaW9u
IiwgcmVhZHk6IHRydWUsIGxhenk6IHRydWUsCiAgICAgICBwYWdlOiAiaHR0cHM6Ly93ZWxjb21l
dG95b3VyZ2FsYXh5LmdpdGh1Yi5pby9jdWxwcml0cy10aWxlcy1tb3JlL3BhZ2VzL2Jhbmtpbmdf
ZHluYXN0aWVzLmh0bWwiLAogICAgICAgbm90ZTogIlRoZSByZXN0IG9mIHRoZSBTdXBwcmVzc2lv
biBwYWdlJ3MgYmFua2luZyBkeW5hc3RpZXMgc2VjdGlvbiwgd2hvbGUgYW5kIHJ1biBieSBpdHMg
b3duIGNvZGUsIGluIHRoZSBwYW5lbCBhbG9uZyB0aGUgYm90dG9tOiBpdHMgdGltZWxpbmUgb2Yg
MjUgZmFtaWxpZXMgZnJvbSAxMjUwIHRvIDIwMjUsIGFuZCBpdHMgY2hhcnRzIG9mIHBlYWsgd2Vh
bHRoLCBiYW5rcywgcHJvcGVydGllcywgd29ya2ZvcmNlLCBsb25nZXZpdHkgYW5kIG92ZXJsYXAu
IEl0cyBtYXAgaXMgdGhlIHJvdyBhYm92ZS4iIH0sCmRpZmYgLS1naXQgYS9tYXAvaW5kZXguaHRt
bCBiL21hcC9pbmRleC5odG1sCmluZGV4IDViMGJiYzUuLjRmNDE3OWEgMTAwNjQ0Ci0tLSBhL21h
cC9pbmRleC5odG1sCisrKyBiL21hcC9pbmRleC5odG1sCkBAIC01MDQsNyArNTA0LDcgQEAKICAg
fTsKIH0pKCk7CiA8L3NjcmlwdD4KLTxzY3JpcHQgc3JjPSIuL2FwcC5qcz92PTY0Ij48L3Njcmlw
dD4KKzxzY3JpcHQgc3JjPSIuL2FwcC5qcz92PTY1Ij48L3NjcmlwdD4KIDxzY3JpcHQgc3JjPSIu
L3dpcmUuanM/dj02MSI+PC9zY3JpcHQ+CiA8IS0tIFRoZSBkcmFnIGJhciBvbiB0aGUgbGF5ZXJz
IGJveCdzIHJpZ2h0IGVkZ2UgKG1hZGUgYnkgY29sdW1uRWRnZSgpIGluCiAgICAgIGFwcC5qcykg
cmFuIHRoZSBmdWxsIGhlaWdodCBvZiB0aGUgY29sdW1uLCBzbyBpdCBzdGF5ZWQgc3RhbmRpbmcg
YmVzaWRlCmRpZmYgLS1naXQgYS9tYXAvdGVzdC5tanMgYi9tYXAvdGVzdC5tanMKaW5kZXggOGNi
ODUxZi4uNTAyMzNkNSAxMDA2NDQKLS0tIGEvbWFwL3Rlc3QubWpzCisrKyBiL21hcC90ZXN0Lm1q
cwpAQCAtNDUxNSw1ICs0NTE1LDEzIEBAIEFBQUFBQUFBQUFBQSBBQUFBQUFBQUFBQUFBQUFBIHwg
Tk5OTiB8ICAgIEEgICAgfCBZWVlZLU1NLUREIEhIOk1NIHwgRUVFRUVFRUUgfCBOCiAgICAgICAg
IC9cLmZhY2V0XFtkYXRhLWNvbG91ci1mb3I9IlwkXHtlc2NcfSJcXSwgXC5mYWNldFxbZGF0YS1r
aW5kcz0iXCRce2VzY1x9IlxdLy50ZXN0KHNyYykgJiYgL2VsXC5kYXRhc2V0XC5rZXlGb3IgPSBj
ZmdcLmlkOyAgIFwvXC8gaXRzIGtpbmRzJyBjb2xvdXJzIGFyZSBpdHMga2V5Ly50ZXN0KHNyYykp
OwogICBjaGVjaygidGhlIHBhZ2UgYXNrcyBmb3IgdGhpcyByb3VuZCdzIHNjcmlwdCIsIC9hcHBc
LmpzXD92PSg2WzQtOV18WzctOV1cZCkvLnRlc3QoaHRtbCkpOwogfQoreworICBjb25zb2xlLmxv
ZygiXG5yb3VuZCA2NTogdGhlIGR5bmFzdGllcycgbWlzc2luZyBjaXRpZXMgbmFtZWQgaW4gdGhl
IHJvdywga2V5cyByZWFkIHdpdGggdGhlaXIgY291bnRzIGFwYXJ0Iik7CisgIGNvbnN0IHNyYyA9
IGZzLnJlYWRGaWxlU3luYyhwYXRoLmpvaW4oSEVSRSwgImFwcC5qcyIpLCAidXRmOCIpOworICBj
b25zdCBodG1sID0gZnMucmVhZEZpbGVTeW5jKHBhdGguam9pbihIRVJFLCAiaW5kZXguaHRtbCIp
LCAidXRmOCIpOworICBjaGVjaygidGhlIGR5bmFzdGllcyByb3cgc2F5cyBpdHMgMTEgY2l0aWVz
IGFyZSBwbGFjZWQgaG9sbG93IGF0IHRoZSBjaXR5IiwgL3RoZSAxMSBjaXRpZXMgaXRzIGxpc3Qg
Z2l2ZXMgYSBmYW1pbHkgd2l0aG91dCBhIGNvb3JkaW5hdGUsIGRyYXduIGhvbGxvdyBhdCB0aGUg
Y2l0eS8udGVzdChzcmMpKTsKKyAgY2hlY2soImEga2V5J3Mgd29yZHMga2VlcCBhIHNwYWNlIGJl
dHdlZW4gYSBraW5kIGFuZCBpdHMgY291bnQiLCAvcGFydHNcLm1hcFwoXChuXCkgPT4gblwudGV4
dENvbnRlbnQgXHxcfCAiIlwpXC5qb2luXCgiICJcKS8udGVzdChzcmMpKTsKKyAgY2hlY2soInRo
ZSBwYWdlIGFza3MgZm9yIHRoaXMgcm91bmQncyBzY3JpcHQiLCAvYXBwXC5qc1w/dj0oNls1LTld
fFs3LTldXGQpLy50ZXN0KGh0bWwpKTsKK30KIGNvbnNvbGUubG9nKGBcbiR7cGFzc30gcGFzc2Vk
LCAke2ZhaWx9IGZhaWxlZFxuYCk7CiBwcm9jZXNzLmV4aXQoZmFpbCA/IDEgOiAwKTsK
""")
def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True)
if not os.path.exists("map/app.js"):
    sys.exit("Run this from the culprits folder.")
with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
    f.write(DIFF); path = f.name
if git("apply", "--check", "-R", path).returncode == 0:
    print("Already applied. Nothing changed.")
else:
    r = git("apply", "--3way", path)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        git("checkout", "--", "map/app.js", "map/test.mjs", "map/index.html")
        sys.exit("Did not apply; nothing changed.")
    print("Code changes applied.")
os.unlink(path)
if os.path.exists("HANDOFF.md"):
    h = open("HANDOFF.md", encoding="utf-8").read()
    if "## Round 65 (26 September)" not in h:
        i = h.index("---") + 3
        open("HANDOFF.md", "w", encoding="utf-8").write(h[:i] + "\n" + NOTE + h[i:])
        print("HANDOFF.md note added.")
