#!/usr/bin/env python3
"""Round 68 (26 September): the wastewater watersheds shaded in steps of ten, with their key. Needs round 67 first (they run in name order). Upload to the culprits repo's patches folder. Safe to run twice."""
import base64, subprocess, sys, os, tempfile
NOTE = """
## Round 68 (26 September)

- Wastewater watersheds (owner's go-ahead, 26 September): the shapes were
  already built and published (culprits-tiles-more
  tiles/wastewater_watersheds.pmtiles, 79 MB, zoom 9, 134,846 watersheds;
  wastewater/watersheds.key.json), and the row draws them; the "not built"
  lines in the older notes are out of date.
- Its shading: the key's steps were cut at equal counts of watersheds. Half
  carry no nitrogen and most very little, so the top step began at 18 t a year
  and held 9,648 watersheds with 98% of all the nitrogen, and all of Europe
  came out one shade. The row now gives logSteps (1e5 to 1e10 g: 0.1, 1, 10,
  100, 1,000 and 10,000 tonnes a year) and addPmtAreasLayer uses them before
  the key's; it also writes the steps as the row's key (rowKey), so they show
  under the row and in the Showing box. Nothing is filtered.
- Wreckers of the Earth: the layer copies are in culprits-tiles-more umap/,
  but umap/409815/map.json (added to umap_copy.py in round 61) is not there
  yet, so the row still draws nothing until the nightly refresh runs, or
  refresh is run by hand with umap_copy.
"""
DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDBmNWE3NGYuLmExZjQ5
NmQgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtNTM5Niw3ICs1
Mzk2LDEyIEBAIGFzeW5jIGZ1bmN0aW9uIGFkZFBtdEFyZWFzTGF5ZXIoY2ZnKSB7CiAgIGlmICgh
Y2ZnIHx8IG1hcC5nZXRTb3VyY2UoYCR7Y2ZnLmlkfS1zcmNgKSkgcmV0dXJuOwogICBsZXQga2V5
ID0ge307CiAgIHRyeSB7IGtleSA9IGF3YWl0IGdldEpzb24oY2ZnLmtleVVybCwgMjAwMDApOyB9
IGNhdGNoIChlKSB7IHNldExheWVyU3RhdGUoY2ZnLmlkLCBgbm90IGJ1aWx0IHlldCAoJHtlLm1l
c3NhZ2V9KWApOyByZXR1cm47IH0KLSAgY29uc3QgYnJlYWtzID0gKGtleS5icmVha3MgfHwgW10p
LmZpbHRlcigoYikgPT4gTnVtYmVyLmlzRmluaXRlKGIpKS5zbGljZSgwLCBBUkVBX1JBTVAubGVu
Z3RoIC0gMSk7CisgIC8vIFJvdW5kIDY3OiBzdGVwcyBvZiB0ZW4gb24gYSBsb2cgc2NhbGUgd2hl
biB0aGUgcm93IGFza3MgZm9yIHRoZW0uIFRoZQorICAvLyBrZXkncyBvd24gc3RlcHMgd2VyZSBj
dXQgYXQgZXF1YWwgY291bnRzIG9mIHdhdGVyc2hlZHM7IGhhbGYgY2Fycnkgbm8KKyAgLy8gbml0
cm9nZW4gYW5kIG1vc3QgdmVyeSBsaXR0bGUsIHNvIHRoZSB0b3Agc3RlcCBiZWdhbiBhdCAxOCB0
IGEgeWVhciBhbmQKKyAgLy8gaGVsZCA5LDY0OCB3YXRlcnNoZWRzIHdpdGggOTglIG9mIGFsbCB0
aGUgbml0cm9nZW46IGFsbCBvZiBFdXJvcGUgY2FtZSBvdXQKKyAgLy8gb25lIHNoYWRlLiBFdmVy
eSB3YXRlcnNoZWQgaXMgc3RpbGwgZHJhd247IG9ubHkgdGhlIHN0ZXBzIG1vdmVkLgorICBjb25z
dCBicmVha3MgPSAoY2ZnLmxvZ1N0ZXBzIHx8IChrZXkuYnJlYWtzIHx8IFtdKS5maWx0ZXIoKGIp
ID0+IE51bWJlci5pc0Zpbml0ZShiKSkpLnNsaWNlKDAsIEFSRUFfUkFNUC5sZW5ndGggLSAxKTsK
ICAgY29uc3QgdiA9IFsidG8tbnVtYmVyIiwgWyJnZXQiLCAidmFsdWUiXSwgMF07CiAgIGNvbnN0
IGNvbG91ciA9IGJyZWFrcy5sZW5ndGggPyBbInN0ZXAiLCB2LCBBUkVBX1JBTVBbMF0sIC4uLmJy
ZWFrcy5mbGF0TWFwKChiLCBpKSA9PiBbYiwgQVJFQV9SQU1QW2kgKyAxXV0pXSA6IEFSRUFfUkFN
UFszXTsKICAgbWFwLmFkZFNvdXJjZShgJHtjZmcuaWR9LXNyY2AsIHsgdHlwZTogInZlY3RvciIs
IHVybDogYHBtdGlsZXM6Ly8ke2NmZy5hcmNoaXZlVXJsfWAsIGF0dHJpYnV0aW9uOiAiVHVob2xz
a2UgZXQgYWwuIDIwMjEsIEdsb2JhbCBXYXN0ZXdhdGVyIE1vZGVsLCBLTkIiIH0pOwpAQCAtNTQw
Niw2ICs1NDExLDEyIEBAIGFzeW5jIGZ1bmN0aW9uIGFkZFBtdEFyZWFzTGF5ZXIoY2ZnKSB7CiAg
ICAgcGFpbnQ6IHsgImxpbmUtY29sb3IiOiAiI0M3QUJBMiIsICJsaW5lLXdpZHRoIjogMC40LCAi
bGluZS1vcGFjaXR5IjogMC41IH0gfSwgcG9pbnRMYXllckFib3ZlKCkpOwogICBjZmcuX2xheWVy
SWRzID0gW2Ake2NmZy5pZH0tZmlsbGAsIGAke2NmZy5pZH0tbGluZWBdOwogICBiaW5kSHRtbFBv
cHVwKGAke2NmZy5pZH0tZmlsbGAsIChwKSA9PiBwaWVjZUJveChjZmcsIHApKTsKKyAgaWYgKGJy
ZWFrcy5sZW5ndGggJiYgY2ZnLnN0ZXBMYWJlbCkgeworICAgIGNvbnN0IGxhYiA9IGNmZy5zdGVw
TGFiZWw7CisgICAgcm93S2V5KGNmZy5pZCwgQVJFQV9SQU1QLnNsaWNlKDAsIGJyZWFrcy5sZW5n
dGggKyAxKS5tYXAoKGMsIGkpID0+CisgICAgICBbYywgKGkgPT09IDAgPyBgbm9uZSB0byAke2xh
YihicmVha3NbMF0pfWAgOiBpID09PSBicmVha3MubGVuZ3RoID8gYCR7bGFiKGJyZWFrc1tpIC0g
MV0pfSBvciBtb3JlYCA6IGAke2xhYihicmVha3NbaSAtIDFdKX0gdG8gJHtsYWIoYnJlYWtzW2ld
KX1gKSArIChjZmcuc3RlcFVuaXQgfHwgIiIpXSkpOworICAgIGlmICh0eXBlb2YgYnVpbGRMZWdl
bmQgPT09ICJmdW5jdGlvbiIpIGJ1aWxkTGVnZW5kKCk7CisgIH0KICAgc2V0TGF5ZXJTdGF0ZShj
ZmcuaWQsIGJyZWFrcy5sZW5ndGggPyBgJHsoa2V5LmNvdW50IHx8IDApLnRvTG9jYWxlU3RyaW5n
KCl9IGFyZWFzLCBpbiAke2JyZWFrcy5sZW5ndGggKyAxfSBzdGVwc2AgOiAiYXJlYXMiKTsKICAg
YXBwbHlWaXNpYmlsaXR5KGNmZy5pZCk7CiB9CkBAIC0xMjI4MSw3ICsxMjI5MiwxMCBAQCBjb25z
dCBPVEhFUl9NQVBTID0gewogICAgIHsgaWQ6ICJ3YXN0ZXdhdGVyX3dhdGVyc2hlZHMiLCBuYW1l
OiAiTml0cm9nZW4gZnJvbSBodW1hbiB3YXN0ZXdhdGVyLCBieSB0aGUgd2F0ZXJzaGVkIGl0IGRy
YWlucyBmcm9tIChUdWhvbHNrZSBldCBhbC4pIiwgdW5pdDogImdyYW1zIG9mIG5pdHJvZ2VuIGEg
eWVhciIsIGNvbG91cjogIiM1RTczNzciLCByb3V0ZTogInBtdGFyZWFzIiwgcmVhZHk6IHRydWUs
IGxhenk6IHRydWUsCiAgICAgICBhcmNoaXZlVXJsOiAiaHR0cHM6Ly93ZWxjb21ldG95b3VyZ2Fs
YXh5LmdpdGh1Yi5pby9jdWxwcml0cy10aWxlcy1tb3JlL3RpbGVzL3dhc3Rld2F0ZXJfd2F0ZXJz
aGVkcy5wbXRpbGVzIiwga2V5VXJsOiAiaHR0cHM6Ly93ZWxjb21ldG95b3VyZ2FsYXh5LmdpdGh1
Yi5pby9jdWxwcml0cy10aWxlcy1tb3JlL3dhc3Rld2F0ZXIvd2F0ZXJzaGVkcy5rZXkuanNvbiIs
CiAgICAgICBib3hlczogImh0dHBzOi8vd2VsY29tZXRveW91cmdhbGF4eS5naXRodWIuaW8vY3Vs
cHJpdHMtdGlsZXMtbW9yZS93YXN0ZXdhdGVyL3BpZWNlcyIsIHNvdXJjZUxheWVyOiAid2F0ZXJz
aGVkcyIsCi0gICAgICBub3RlOiAiVGhlIEdsb2JhbCBXYXN0ZXdhdGVyIE1vZGVsJ3Mgd2F0ZXJz
aGVkczogdGhlIGxhbmQgZWFjaCBjb2FzdGFsIG91dGxldCBkcmFpbnMsIHNoYWRlZCBieSBhbGwg
dGhlIG5pdHJvZ2VuIGZyb20gaHVtYW4gd2FzdGV3YXRlciB0aGF0IHJlYWNoZXMgdGhlIHNlYSBm
cm9tIGl0LCBkYXJrIHRvIGxpZ2h0IG9uIGEgbG9nIHNjYWxlIGN1dCBhdCB0aGUgdmFsdWVzJyBv
d24gc3RlcHMuIEEgY2xpY2sgc2hvd3MgZXZlcnkgZmlndXJlIHRoZSBtb2RlbCBnaXZlcyBmb3Ig
aXQuIEJ1aWx0IG9uY2UgZnJvbSB0aGUgbW9kZWwncyAyMDIxIGRhdGEgcGFja2FnZSAoc2NyaXB0
cy93YXN0ZXdhdGVyX3dhdGVyc2hlZHMucHkgaW4gY3VscHJpdHMtdGlsZXMtbW9yZSk7IGl0IGlz
IG5vdCB1cGRhdGVkLiIgfSwKKyAgICAgIC8vIEdyYW1zIGEgeWVhciwgaW4gc3RlcHMgb2YgdGVu
IGZyb20gMC4xIHRvIDEwLDAwMCB0b25uZXMgKHJvdW5kIDY3KS4KKyAgICAgIGxvZ1N0ZXBzOiBb
MWU1LCAxZTYsIDFlNywgMWU4LCAxZTksIDFlMTBdLAorICAgICAgc3RlcExhYmVsOiAoZykgPT4g
KGcgLyAxZTYpLnRvTG9jYWxlU3RyaW5nKCJlbiIsIHsgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAx
IH0pLCBzdGVwVW5pdDogIiB0b25uZXMgYSB5ZWFyIiwKKyAgICAgIG5vdGU6ICJUaGUgR2xvYmFs
IFdhc3Rld2F0ZXIgTW9kZWwncyB3YXRlcnNoZWRzOiB0aGUgbGFuZCBlYWNoIGNvYXN0YWwgb3V0
bGV0IGRyYWlucywgc2hhZGVkIGJ5IGFsbCB0aGUgbml0cm9nZW4gZnJvbSBodW1hbiB3YXN0ZXdh
dGVyIHRoYXQgcmVhY2hlcyB0aGUgc2VhIGZyb20gaXQsIGRhcmsgdG8gbGlnaHQgaW4gc3RlcHMg
b2YgdGVuLCBmcm9tIHVuZGVyIDAuMSB0b25uZSBhIHllYXIgdG8gMTAsMDAwIHRvbm5lcyBvciBt
b3JlIChhYm91dCBoYWxmIHRoZSAxMzQsODQ2IHdhdGVyc2hlZHMgY2Fycnkgbm9uZSkuIEEgY2xp
Y2sgc2hvd3MgZXZlcnkgZmlndXJlIHRoZSBtb2RlbCBnaXZlcyBmb3IgaXQuIEJ1aWx0IG9uY2Ug
ZnJvbSB0aGUgbW9kZWwncyAyMDIxIGRhdGEgcGFja2FnZSAoc2NyaXB0cy93YXN0ZXdhdGVyX3dh
dGVyc2hlZHMucHkgaW4gY3VscHJpdHMtdGlsZXMtbW9yZSk7IGl0IGlzIG5vdCB1cGRhdGVkLiIg
fSwKICAgICB7IGlkOiAid2FzdGV3YXRlcl9wbHVtZXMiLCBuYW1lOiAiTml0cm9nZW4gZnJvbSBo
dW1hbiB3YXN0ZXdhdGVyIGluIGNvYXN0YWwgd2F0ZXJzLCAyMDE1IChUdWhvbHNrZSBldCBhbC4p
IiwgdW5pdDogInBlciBtYXAgY2VsbCIsIGNvbG91cjogIiM1RTczNzciLCByb3V0ZTogInJhc3Rl
cmxpdmUiLCByZWFkeTogdHJ1ZSwgbGF6eTogdHJ1ZSwKICAgICAgIGF0dHJpYnV0aW9uOiAiVHVo
b2xza2UgZXQgYWwuIDIwMjEsIEdsb2JhbCBXYXN0ZXdhdGVyIE1vZGVsIChLTkIgZG9pOjEwLjUw
NjMvRjc2QjA5KSIsIG1heHpvb206IDYsCiAgICAgICBjaG9pY2VzOiBbCmRpZmYgLS1naXQgYS9t
YXAvaW5kZXguaHRtbCBiL21hcC9pbmRleC5odG1sCmluZGV4IDM4MWFkNjAuLmJmZjIwZjAgMTAw
NjQ0Ci0tLSBhL21hcC9pbmRleC5odG1sCisrKyBiL21hcC9pbmRleC5odG1sCkBAIC01MTgsNyAr
NTE4LDcgQEAKICAgfTsKIH0pKCk7CiA8L3NjcmlwdD4KLTxzY3JpcHQgc3JjPSIuL2FwcC5qcz92
PTY3Ij48L3NjcmlwdD4KKzxzY3JpcHQgc3JjPSIuL2FwcC5qcz92PTY4Ij48L3NjcmlwdD4KIDxz
Y3JpcHQgc3JjPSIuL3dpcmUuanM/dj02NyI+PC9zY3JpcHQ+CiA8IS0tIFRoZSBkcmFnIGJhciBv
biB0aGUgbGF5ZXJzIGJveCdzIHJpZ2h0IGVkZ2UgKG1hZGUgYnkgY29sdW1uRWRnZSgpIGluCiAg
ICAgIGFwcC5qcykgcmFuIHRoZSBmdWxsIGhlaWdodCBvZiB0aGUgY29sdW1uLCBzbyBpdCBzdGF5
ZWQgc3RhbmRpbmcgYmVzaWRlCmRpZmYgLS1naXQgYS9tYXAvdGVzdC5tanMgYi9tYXAvdGVzdC5t
anMKaW5kZXggYTQ2ODNkMC4uMjI1Y2M3ZiAxMDA2NDQKLS0tIGEvbWFwL3Rlc3QubWpzCisrKyBi
L21hcC90ZXN0Lm1qcwpAQCAtMzM4Nyw2ICszMzg3LDggQEAgY29uc29sZS5sb2coIlxucm91bmQg
b2YgMjMgU2VwdGVtYmVyICg1KTogdGhlIEF0bGFzIHBhbmVsIHBhcmVkIGRvd247IG5vIGdyYWlu
OwogICBjaGVjaygiYSBwdWxsIHNldHMgdGhlIG1vc3QgYSBib3ggc2hvd3MsIHNvIGl0IGlzIG5l
dmVyIHRhbGxlciB0aGFuIGl0cyBsaXN0IGFuZCB0aGUgbGF5ZXJzIGJveCBzdGlsbCBnaXZlcyB3
YXkgdG8gdGhlIFNob3dpbmcgYm94IChyb3VuZCA2NikiLAogICAgICAgICAvZWxcLnN0eWxlXC5t
YXhIZWlnaHQgPSBoIFwrICJweCI7Ly50ZXN0KHNyYykgJiYgIS9lbFwuc3R5bGVcLmZsZXggPSAi
MCAwIGF1dG8iOy8udGVzdChzcmMpICYmIC9cLmxlZnQtY29sIFwucGFuZWxce2ZsZXg6MCAxIGF1
dG9cfS8udGVzdChmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUsICJpbmRleC5odG1sIiks
ICJ1dGY4IikpICYmCiAgICAgICAgIC9cLmxlZnQtY29sIFwucGFuZWwgPiBcLnB1bGwtZ3JpcFx7
cG9zaXRpb246c3RpY2t5O2JvdHRvbTowLy50ZXN0KGZzLnJlYWRGaWxlU3luYyhwYXRoLmpvaW4o
SEVSRSwgImluZGV4Lmh0bWwiKSwgInV0ZjgiKSkpOworICBjaGVjaygidGhlIHdhdGVyc2hlZHMg
YXJlIHNoYWRlZCBpbiBzdGVwcyBvZiB0ZW4sIHdpdGggYSBrZXkgKHJvdW5kIDY3KSIsCisgICAg
ICAgIC9sb2dTdGVwczogXFsxZTUsIDFlNiwgMWU3LCAxZTgsIDFlOSwgMWUxMFxdLy50ZXN0KHNy
YykgJiYgL2NvbnN0IGJyZWFrcyA9IFwoY2ZnXC5sb2dTdGVwcyBcfFx8Ly50ZXN0KHNyYykgJiYg
L25vbmUgdG8gXCRce2xhYlwoYnJlYWtzXFswXF1cKVx9Ly50ZXN0KHNyYykpOwogICBjaGVjaygi
dGhlIENvdW50cnkgb3V0bGluZXMgYmFzZW1hcCBrZWVwcyBpdHMgb3duIGNvbG91cnMgKHJvdW5k
IDY2KSIsIC9cfHNhdC1yZWxpZWYtY29sb3VyXHxvdXRsaW5lLVwuXCpcKVwkXC87Ly50ZXN0KHNy
YykpOwogICBjaGVjaygic3BhY2Ugcm93cyByZXRpdGxlZCAocm91bmQgNjYpIiwgL1x7IGg6IDMs
IHQ6ICJFeHRyYXRlcnJlc3RyaWFsIGxpZmUiIFx9Ly50ZXN0KHNyYykgJiYgL25hbWU6ICJTcGFj
ZWNyYWZ0IGluIHNwYWNlLCBnb2luZyBnYWxhY3RpYyBcKE5BU0EncyBFeWVzIG9uIHRoZSBTb2xh
ciBTeXN0ZW1cKSIvLnRlc3Qoc3JjKSk7CiAgIGNoZWNrKCJ0aGUgbmV3cyB3aXJlcycgb3Blbi1h
bmQtc2h1dCBhcnJvdyBzaXRzIGF0IHRoZSByaWdodC1oYW5kIGVuZCBvZiB0aGUgYmFyIiwK
""")
def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True)
if not os.path.exists("map/app.js"):
    sys.exit("Run this from the culprits folder.")
with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
    f.write(DIFF); path = f.name
if git("apply", "--check", "-R", path).returncode == 0:
    print("Already applied. Nothing changed.")
else:
    r = git("apply", "--3way", path)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        git("checkout", "--", "map/app.js", "map/test.mjs", "map/index.html", "map/wire.js", "map/wire.test.mjs")
        sys.exit("Did not apply; nothing changed.")
    print("Code changes applied.")
os.unlink(path)
if os.path.exists("HANDOFF.md"):
    h = open("HANDOFF.md", encoding="utf-8").read()
    if "## Round 68 (26 September)" not in h:
        i = h.index("---") + 3
        open("HANDOFF.md", "w", encoding="utf-8").write(h[:i] + "\n" + NOTE + h[i:])
        print("HANDOFF.md note added.")
