#!/usr/bin/env python3
"""
Round 124b (culprits), 2 October 2026. Needs round 123b.

Each fire record from Global Forest Watch says which country it is in and
links to its spot on OpenStreetMap.

Run from the repository root (the apply-patch workflow does).
"""
import base64, pathlib, subprocess, sys, tempfile

HEAD = "## Round 124b (2 October)"


def git(*a, check=True):
    return subprocess.run(["git", *a], capture_output=True, text=True, check=check)


def main():
    root = pathlib.Path(".")
    if not (root / "map" / "app.js").exists():
        sys.exit("round124b: run from the culprits repository root")
    text = (root / "HANDOFF.md").read_text(encoding="utf-8")
    if "## Round 123b" not in text:
        sys.exit("round124b: round 123b must be applied first")
    with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
        f.write(base64.b64decode(DIFF))
        path = f.name
    if git("apply", "--check", "-R", "--binary", path, check=False).returncode == 0:
        print("round124b: already applied")
    else:
        r = git("apply", "--3way", "--binary", path, check=False)
        if r.returncode != 0:
            git("checkout", "--", "map/app.js", "map/test.mjs", check=False)
            sys.exit("round124b: the diff did not apply:\n" + r.stdout + r.stderr)
        print("round124b: applied")
    h = root / "HANDOFF.md"
    text = h.read_text(encoding="utf-8")
    if HEAD not in text:
        at = text.index("\n## Round ") + 1
        h.write_text(text[:at] + NOTE + text[at:], encoding="utf-8")


NOTE = "## Round 124b (2 October)\n\nNeeds round 123b. Tiles patch round124b_tiles.py beside it. No app.js?v= bump.\n\n- GFW records that carry their own latitude and longitude (the VIIRS fires)\n  show the country they fall in, from the map's own outlines (countryNameAt,\n  COUNTRY_SHAPES), and a link to the spot on OpenStreetMap (recordWhere).\n  NASA names no fires.\n- tiles medical_culprits.py: the company is read from the settlements\n  table's own Company column (it took drug names such as Neurontin and\n  Zoladex as companies); rows under cells spanning several rows carry them down.\n\n"
DIFF = "ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDlmMjQwZjUuLmYyMGVlNGEgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMTAyNzUsMTMgKzEwMjc1LDUxIEBAIGZ1bmN0aW9uIGdmd0tpbmRDb2xvdXJzKG9yZGVyLCBzcGVjKSB7CiBjb25zdCBHRldfTkFNRV9GSUVMRFMgPSBbIm5hbWUiLCAidGVycmFpX25vbSIsICJOYW1lIiwgIk5BTUUiLCAibm9tZSIsICJub20iLCAibm9tYnJlIiwgInNpdGVfbmFtZSIsICJhcmVhX25hbWUiLCAiY29tbV9uYW1lIl07CiBjb25zdCBHRldfUEVPUExFX0ZJRUxEUyA9IFsiZXRobmN0eV8xIiwgImV0bmlhX25vbWUiLCAiZXRobmljaXR5IiwgInBlb3BsZSIsICJwZW9wbGVzIl07CiBjb25zdCBHRldfSElEREVOID0gbmV3IFNldChbImdmd19maWQiLCAiZ2Z3X2dlb3N0b3JlX2lkIiwgImdmd19iYm94IiwgImdmd19nZW9qc29uIiwgImNyZWF0ZWRfb24iLCAidXBkYXRlZF9vbiIsICJzaGFwZV9sZW5ndGgiLCAic2hhcGVfYXJlYSIsICJlcHNnIiwgImdpZCIsICJjYXJ0b2RiX2lkIl0pOworLy8gUm91bmQgMTIzYiAoYXNrZWQgMiBPY3RvYmVyOiB0aGUgVklJUlMgZmlyZXMnIGJveGVzICJkb24ndCBoYXZlIG11Y2g7IGEKKy8vIGxvY2F0aW9uIG9yIGZpcmUgbmFtZSB3b3VsZCBiZSBoZWxwZnVsIik6IE5BU0EgbmFtZXMgbm8gZmlyZXMsIHNvIGEgcmVjb3JkCisvLyB0aGF0IGNhcnJpZXMgaXRzIG93biBsYXRpdHVkZSBhbmQgbG9uZ2l0dWRlIGlzIGdpdmVuIHRoZSBjb3VudHJ5IGl0IGZhbGxzIGluCisvLyAodGhlIG1hcCdzIG93biBjb3VudHJ5IG91dGxpbmVzKSBhbmQgYSBsaW5rIHRvIHRoZSBzcG90IG9uIE9wZW5TdHJlZXRNYXAuCitsZXQgQ09VTlRSWV9TSEFQRVMgPSBudWxsOworZnVuY3Rpb24gY291bnRyeVNoYXBlc1Nvb24oKSB7CisgIGlmIChDT1VOVFJZX1NIQVBFUyB8fCB0eXBlb2YgZ2V0SnNvbiAhPT0gImZ1bmN0aW9uIikgcmV0dXJuOworICBDT1VOVFJZX1NIQVBFUyA9IFtdOworICBnZXRKc29uKEJPVU5EQVJJRVNfVVJMLCA2MDAwMCkudGhlbigoZykgPT4geyBDT1VOVFJZX1NIQVBFUyA9IChnICYmIGcuZmVhdHVyZXMpIHx8IFtdOyB9KS5jYXRjaCgoKSA9PiB7IENPVU5UUllfU0hBUEVTID0gbnVsbDsgfSk7Cit9CitmdW5jdGlvbiBpblJpbmcoeCwgeSwgcmluZykgeworICBsZXQgaW5zaWRlID0gZmFsc2U7CisgIGZvciAobGV0IGkgPSAwLCBqID0gcmluZy5sZW5ndGggLSAxOyBpIDwgcmluZy5sZW5ndGg7IGogPSBpKyspIHsKKyAgICBjb25zdCBbeGksIHlpXSA9IHJpbmdbaV0sIFt4aiwgeWpdID0gcmluZ1tqXTsKKyAgICBpZiAoKHlpID4geSkgIT09ICh5aiA+IHkpICYmIHggPCAoKHhqIC0geGkpICogKHkgLSB5aSkpIC8gKHlqIC0geWkgfHwgMWUtMTIpICsgeGkpIGluc2lkZSA9ICFpbnNpZGU7CisgIH0KKyAgcmV0dXJuIGluc2lkZTsKK30KK2Z1bmN0aW9uIGNvdW50cnlOYW1lQXQobG9uLCBsYXQpIHsKKyAgaWYgKCFBcnJheS5pc0FycmF5KENPVU5UUllfU0hBUEVTKSkgcmV0dXJuIG51bGw7CisgIGZvciAoY29uc3QgZiBvZiBDT1VOVFJZX1NIQVBFUykgeworICAgIGNvbnN0IGcgPSBmICYmIGYuZ2VvbWV0cnk7CisgICAgaWYgKCFnKSBjb250aW51ZTsKKyAgICBjb25zdCBwb2x5cyA9IGcudHlwZSA9PT0gIlBvbHlnb24iID8gW2cuY29vcmRpbmF0ZXNdIDogZy50eXBlID09PSAiTXVsdGlQb2x5Z29uIiA/IGcuY29vcmRpbmF0ZXMgOiBbXTsKKyAgICBmb3IgKGNvbnN0IHBvbHkgb2YgcG9seXMpIGlmIChwb2x5WzBdICYmIGluUmluZyhsb24sIGxhdCwgcG9seVswXSkgJiYgIXBvbHkuc2xpY2UoMSkuc29tZSgoaCkgPT4gaW5SaW5nKGxvbiwgbGF0LCBoKSkpIHJldHVybiAoZi5wcm9wZXJ0aWVzIHx8IHt9KS5uYW1lIHx8IG51bGw7CisgIH0KKyAgcmV0dXJuIG51bGw7Cit9CitmdW5jdGlvbiByZWNvcmRXaGVyZShwKSB7CisgIGNvbnN0IG51bSA9ICh2KSA9PiAodiA9PSBudWxsIHx8IHYgPT09ICIiID8gTmFOIDogTnVtYmVyKHYpKTsKKyAgY29uc3QgbGF0ID0gW3AubGF0aXR1ZGUsIHAubGF0LCBwLkxBVElUVURFXS5tYXAobnVtKS5maW5kKE51bWJlci5pc0Zpbml0ZSk7CisgIGNvbnN0IGxvbiA9IFtwLmxvbmdpdHVkZSwgcC5sb24sIHAubG5nLCBwLkxPTkdJVFVERV0ubWFwKG51bSkuZmluZChOdW1iZXIuaXNGaW5pdGUpOworICBpZiAoIU51bWJlci5pc0Zpbml0ZShsYXQpIHx8ICFOdW1iZXIuaXNGaW5pdGUobG9uKSkgcmV0dXJuICIiOworICBjb25zdCBjID0gY291bnRyeU5hbWVBdChsb24sIGxhdCk7CisgIHJldHVybiBgPGRpdiBjbGFzcz0ibWV0YSI+JHtjID8gYEluICR7ZXNjYXBlSHRtbChjKX0gXHUwMGI3IGAgOiAiIn08YSBocmVmPSJodHRwczovL3d3dy5vcGVuc3RyZWV0bWFwLm9yZy8/bWxhdD0ke2xhdH0mbWxvbj0ke2xvbn0jbWFwPTExLyR7bGF0fS8ke2xvbn0iIHRhcmdldD0iX2JsYW5rIiByZWw9Im5vb3BlbmVyIj4ke2xhdC50b0ZpeGVkKDQpfSwgJHtsb24udG9GaXhlZCg0KX0gb24gT3BlblN0cmVldE1hcDwvYT5gICsKKyAgICBgJHtjID8gIiAoY291bnRyeSBmcm9tIHRoaXMgbWFwJ3Mgb3duIG91dGxpbmVzKSIgOiAiIn08L2Rpdj5gOworfQogZnVuY3Rpb24gZ2Z3UmVjb3JkQm94KGQsIHApIHsKKyAgY291bnRyeVNoYXBlc1Nvb24oKTsKICAgY29uc3QgbmFtZSA9IEdGV19OQU1FX0ZJRUxEUy5tYXAoKGspID0+IHBba10pLmZpbmQoKHYpID0+IHYgIT0gbnVsbCAmJiBTdHJpbmcodikudHJpbSgpICE9PSAiIik7CiAgIGNvbnN0IHBlb3BsZSA9IEdGV19QRU9QTEVfRklFTERTLm1hcCgoaykgPT4gcFtrXSkuZmluZCgodikgPT4gdiAhPSBudWxsICYmIFN0cmluZyh2KS50cmltKCkgIT09ICIiKTsKICAgY29uc3QgcmVzdCA9IE9iamVjdC5mcm9tRW50cmllcyhPYmplY3QuZW50cmllcyhwKS5maWx0ZXIoKFtrXSkgPT4gIUdGV19ISURERU4uaGFzKGspKSk7CiAgIHJldHVybiBgPGI+JHtlc2NhcGVIdG1sKFN0cmluZyhuYW1lIHx8IGQudGl0bGUpKX08L2I+YCArCiAgICAgKHBlb3BsZSA/IGA8ZGl2IGNsYXNzPSJtZXRhIj5QZW9wbGU6ICR7ZXNjYXBlSHRtbChTdHJpbmcocGVvcGxlKSl9PC9kaXY+YCA6ICIiKSArCi0gICAgKG5hbWUgPyBgPGRpdiBjbGFzcz0ibWV0YSI+JHtlc2NhcGVIdG1sKGQudGl0bGUpfTwvZGl2PmAgOiAiIikgKworICAgIChuYW1lID8gYDxkaXYgY2xhc3M9Im1ldGEiPiR7ZXNjYXBlSHRtbChkLnRpdGxlKX08L2Rpdj5gIDogIiIpICsgcmVjb3JkV2hlcmUocCkgKwogICAgIGA8dGFibGUgY2xhc3M9Im1ldGEiPiR7ZmllbGRSb3dzKHJlc3QpfTwvdGFibGU+YDsKIH0KIGZ1bmN0aW9uIGdmd0NvbG91ckJ5KGQsIHNyYywgbmFtZXMsIGlkcykgewpAQCAtMTA1NDksNiArMTA1ODcsNyBAQCBhc3luYyBmdW5jdGlvbiBhZGRHZndNZW51TGF5ZXIoY2ZnKSB7CiAgICAgICAgICAgbWFwLmFkZExheWVyKHsgaWQ6IGAke3NyY30tcC0ke3NhZmUobil9YCwgdHlwZTogImNpcmNsZSIsIC4uLmJhc2UsIGZpbHRlcjogWyI9PSIsIFsiZ2VvbWV0cnktdHlwZSJdLCAiUG9pbnQiXSwgcGFpbnQ6IHsgImNpcmNsZS1jb2xvciI6IG5lb24sICJjaXJjbGUtcmFkaXVzIjogMywgImNpcmNsZS1zdHJva2Utd2lkdGgiOiAwLjUsICJjaXJjbGUtc3Ryb2tlLWNvbG9yIjogIiMxNzE1MEYiIH0gfSk7CiAgICAgICAgICAgZm9yIChjb25zdCBpZCBvZiBbYCR7c3JjfS1mLSR7c2FmZShuKX1gLCBgJHtzcmN9LWwtJHtzYWZlKG4pfWAsIGAke3NyY30tcC0ke3NhZmUobil9YF0pIHsKICAgICAgICAgICAgIGlkcy5wdXNoKGlkKTsKKyAgICAgICAgICAgIGNvdW50cnlTaGFwZXNTb29uKCk7CiAgICAgICAgICAgICBiaW5kSHRtbFBvcHVwKGlkLCAocCkgPT4gZ2Z3UmVjb3JkQm94KGQsIHApKTsKICAgICAgICAgICB9CiAgICAgICAgIH0KZGlmZiAtLWdpdCBhL21hcC90ZXN0Lm1qcyBiL21hcC90ZXN0Lm1qcwppbmRleCBjMTllMzczLi41NTU5Yjc5IDEwMDY0NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rlc3QubWpzCkBAIC01OTY1LDYgKzU5NjUsMTUgQEAgY29uc29sZS5sb2coIlxucm91bmQgMTIzYiAoMiBPY3RvYmVyKToga2V5bGVzcyBpbWFnZXJ5LCBvdmVybGFwIG1vZGVzLCByYWlzZSBvZmYKICAgICAgICAgL1RSQVNFX1JFTU9WRURfTUVUUklDUyA9IG5ldyBTZXRcKFxbIkJVUk5FRF9QRUFUIiwgIkVNSVNTSU9OX0JVUk5FRF9QRUFUX0NPMiJcXVwpLy50ZXN0KHNyYykgJiYgL3RjbF9maXJlOiBceyBtb2RlOiAieWVhciIvLnRlc3Qoc3JjKSk7CiAgIGNoZWNrKCJ0aGUgc2hhcmUgb2YgdGhlIG1hcCB0aGF0IGlzIGxpdmUgc2hvd3MgYXQgdGhlIHRvcCIsIC9mdW5jdGlvbiBsaXZlU2hhcmVCYWRnZVwoLy50ZXN0KHNyYykgJiYgLyUgb2YgdGhlIG1hcCBpcyBsaXZlLy50ZXN0KHNyYykpOwogfQorY29uc29sZS5sb2coIlxucm91bmQgMTI0YiAoMiBPY3RvYmVyKTogYSBmaXJlJ3MgY291bnRyeSBhbmQgcGxhY2Ugb24gdGhlIG1hcCIpOworeworICBjb25zdCBzcmMgPSBmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUsICJhcHAuanMiKSwgInV0ZjgiKTsKKyAgY29uc3QgcmluZyA9IG5ldyBGdW5jdGlvbihzcmMuc2xpY2Uoc3JjLmluZGV4T2YoImZ1bmN0aW9uIGluUmluZygiKSwgc3JjLmluZGV4T2YoImZ1bmN0aW9uIGNvdW50cnlOYW1lQXQoIikpICsgIjsgcmV0dXJuIGluUmluZzsiKSgpOworICBjb25zdCBzcSA9IFtbMCwgMF0sIFsxMCwgMF0sIFsxMCwgMTBdLCBbMCwgMTBdLCBbMCwgMF1dOworICBjaGVjaygiYSBwb2ludCBpcyBmb3VuZCBpbnNpZGUgaXRzIGNvdW50cnkncyBvdXRsaW5lIiwgcmluZyg1LCA1LCBzcSkgJiYgIXJpbmcoMTUsIDUsIHNxKSk7CisgIGNoZWNrKCJyZWNvcmRzIHdpdGggdGhlaXIgb3duIGxhdGl0dWRlIGFuZCBsb25naXR1ZGUgZ2V0IGEgY291bnRyeSBhbmQgYW4gT3BlblN0cmVldE1hcCBsaW5rIiwKKyAgICAgICAgL2Z1bmN0aW9uIHJlY29yZFdoZXJlXChwXCkvLnRlc3Qoc3JjKSAmJiAvcmVjb3JkV2hlcmVcKHBcKSBcKy8udGVzdChzcmMpICYmIC9jb3VudHJ5U2hhcGVzU29vblwoXCk7XG5ccypiaW5kSHRtbFBvcHVwXChpZCwgXChwXCkgPT4gZ2Z3UmVjb3JkQm94XChkLCBwXClcKTsvLnRlc3Qoc3JjKSk7Cit9CiBjb25zb2xlLmxvZygiXG5yb3VuZCAxMTBjICgyOSBTZXB0ZW1iZXIpOiBwbGFudGVkLCBib3VnaHQgb3IgY2FwdHVyZWQsIHdvcmxkd2lkZSIpOwogewogICBjb25zdCBzcmMgPSBmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUsICJhcHAuanMiKSwgInV0ZjgiKTsK"

if __name__ == "__main__":
    main()
