#!/usr/bin/env python3
"""Round 79 (27 September): nuclear weapons storage, Russia's storage map and the US Navy at sea. Needs round 78 first (they run in name order). Upload to the culprits repo's patches folder. Safe to run twice."""
import base64, subprocess, sys, os, tempfile
NOTE = "\n## Round 79 (27 September)\n\n- mil_nuclear_storage (geojsonlive, military/nuclear_sites.geojson from\n  culprits-tiles-more scripts/nuclear_sites.py): the storage sites the Nuclear\n  Notebook names, with its words and estimates (Europe: \"The changing nuclear\n  landscape in Europe\", Dec 2025; US: \"United States nuclear weapons, 2026\").\n  Stated coordinates where given, else Wikidata's by name (linked).\n- mil_russia_storage: russianforces.org's 12th GUMO map in the companion\n  panel (CC BY-NC-ND 4.0: not copied).\n- mil_usni_fleet (route usnifleet, readUsniFleet): USNI News Fleet and Marine\n  Tracker, weekly, headings placed at area centres (scripts/usni_fleet.py\n  AREAS table), paragraphs quoted; unplaced headings listed on the row.\n- Probe (scripts/site_probe.py, run by hand): what theyrule.net and\n  unroca.org load (requests, data starts, They Rule's source-map data files),\n  written to probe/sites/ for the next round.\n- Not built: missile ranges (CSIS Missile Threat is all rights reserved and\n  its missile pages could not be read; ranges wait on the owner).\n"
DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDc0MjJmYWIuLmM1MTYx
MGUgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMzkzMyw2ICsz
OTMzLDcgQEAgYXN5bmMgZnVuY3Rpb24gYWRkTGl2ZVBsYWNlc0xheWVyKGNmZykgewogICAgICAg
ICA6IGNmZy5yb3V0ZSA9PT0gImdlb2pzb25saXZlIiA/IGF3YWl0IHJlYWRHZW9qc29uRmlsZXMo
Y2ZnKQogICAgICAgICA6IGNmZy5yb3V0ZSA9PT0gImdkZWx0Z2VvIiA/IGF3YWl0IHJlYWRHZGVs
dEdlbyhjZmcpCiAgICAgICAgIDogY2ZnLnJvdXRlID09PSAiZ2RlbHRhcmNoaXZlIiA/IGF3YWl0
IHJlYWRHZGVsdEFyY2hpdmUoY2ZnKQorICAgICAgICA6IGNmZy5yb3V0ZSA9PT0gInVzbmlmbGVl
dCIgPyBhd2FpdCByZWFkVXNuaUZsZWV0KGNmZykKICAgICAgICAgOiBjZmcucm91dGUgPT09ICJ3
cGdtemEiID8gYXdhaXQgcmVhZFdwZ216YShjZmcpCiAgICAgICAgIDogY2ZnLnJvdXRlID09PSAi
YXRsYXNjaXRpZXMiID8gYXdhaXQgcmVhZEF0bGFzQ2l0aWVzKGNmZykKICAgICAgICAgOiBjZmcu
cm91dGUgPT09ICJ0cmFzZWZhYyIgPyBhd2FpdCByZWFkVHJhc2VGYWNpbGl0aWVzKGNmZykKQEAg
LTExMTA2LDYgKzExMTA3LDMwIEBAIGFzeW5jIGZ1bmN0aW9uIHJlYWRHZGVsdEFyY2hpdmUoY2Zn
KSB7CiAgIH0KICAgcmV0dXJuIHsgdGl0bGU6IGNmZy5uYW1lLCBpdGVtcywgbm90ZTogbW9udGhz
Lmxlbmd0aCA/IGAke21vbnRocy5sZW5ndGh9IG1vbnRoJHttb250aHMubGVuZ3RoID09PSAxID8g
IiIgOiAicyJ9IGtlcHQsIHNpbmNlICR7bW9udGhzWzBdfWAgOiAibm90aGluZyBrZXB0IHlldCIg
fTsKIH0KKy8vIFJvdW5kIDc5OiBVU05JIE5ld3MncyB3ZWVrbHkgRmxlZXQgYW5kIE1hcmluZSBU
cmFja2VyLCBhIGhlYWRpbmcgdG8gYSBtYXJrCisvLyAoY3VscHJpdHMtdGlsZXMtbW9yZSBzY3Jp
cHRzL3VzbmlfZmxlZXQucHkpLCBlYWNoIHdlZWsgYSBjaGlwIG9mIHRoZSByb3cuCithc3luYyBm
dW5jdGlvbiByZWFkVXNuaUZsZWV0KGNmZykgeworICBjb25zdCBpZHggPSBhd2FpdCBnZXRKc29u
KGAke2NmZy5hcmNoaXZlfS9pbmRleC5qc29uYCwgMzAwMDApOworICBjb25zdCB3ZWVrcyA9IChp
ZHgud2Vla3MgfHwgW10pLnNsaWNlKCkuc29ydCgpOworICBjb25zdCBpdGVtcyA9IFtdOworICBj
b25zdCB1bnBsYWNlZCA9IFtdOworICBmb3IgKGNvbnN0IHcgb2Ygd2Vla3MpIHsKKyAgICBsZXQg
Z2o7CisgICAgdHJ5IHsgZ2ogPSBhd2FpdCBnZXRKc29uKGAke2NmZy5hcmNoaXZlfS8ke3d9Lmdl
b2pzb25gLCA2MDAwMCk7IH0gY2F0Y2ggKGUpIHsgY29udGludWU7IH0KKyAgICAoZ2oudW5wbGFj
ZWQgfHwgW10pLmZvckVhY2goKHUpID0+IHVucGxhY2VkLnB1c2goYCR7dX0gKCR7d30pYCkpOwor
ICAgIChnai5mZWF0dXJlcyB8fCBbXSkuZm9yRWFjaCgoZiwgaSkgPT4geworICAgICAgY29uc3Qg
cCA9IGYucHJvcGVydGllcyB8fCB7fTsKKyAgICAgIGl0ZW1zLnB1c2goeyBnZW9tZXRyeTogZi5n
ZW9tZXRyeSwga2V5OiBgJHt3fToke2l9YCwgbmFtZTogcC5uYW1lIHx8ICIiLCBncm91cDogYHdl
ZWsgb2YgJHt3fWAsCisgICAgICAgIGg6IGJveE9wZW4gKyBgPGg0IHN0eWxlPSJtYXJnaW46MCAw
IDZweCI+JHtlc2NhcGVIdG1sKHAubmFtZSB8fCAiIil9LCB3ZWVrIG9mICR7ZXNjYXBlSHRtbCh3
KX08L2g0PmAgKworICAgICAgICAgIFN0cmluZyhwLnNhaWQgfHwgIiIpLnNwbGl0KC9cblxuKy8p
Lm1hcCgoeCkgPT4gYDxwIHN0eWxlPSJtYXJnaW46MCAwIDZweCI+JHtlc2NhcGVIdG1sKHgpfTwv
cD5gKS5qb2luKCIiKSArCisgICAgICAgICAgKGdqLnRvdGFsID8gYDxkaXYgc3R5bGU9Im9wYWNp
dHk6LjgiPiR7ZXNjYXBlSHRtbChnai50b3RhbCl9PC9kaXY+YCA6ICIiKSArCisgICAgICAgICAg
YDxkaXYgc3R5bGU9Im1hcmdpbi10b3A6NnB4Ij48YSBocmVmPSIke2VzY2FwZUh0bWwocC5hcnRp
Y2xlIHx8IGdqLmFydGljbGUgfHwgIiIpfSIgdGFyZ2V0PSJfYmxhbmsiIHJlbD0ibm9vcGVuZXIi
PiR7ZXNjYXBlSHRtbChwLnRpdGxlIHx8IGdqLnRpdGxlIHx8ICJVU05JIE5ld3MgRmxlZXQgYW5k
IE1hcmluZSBUcmFja2VyIil9PC9hPjwvZGl2PmAgKworICAgICAgICAgIGA8ZGl2IHN0eWxlPSJt
YXJnaW4tdG9wOjZweDtvcGFjaXR5Oi43NTtmb250LXNpemU6MTFweCI+RHJhd24gYXQgdGhlIG1p
ZGRsZSBvZiB0aGUgYXJlYSBVU05JIG5hbWVzOyBVU05JIGdpdmVzIG5vIGNvb3JkaW5hdGVzLCBh
bmQgd2Fyc2hpcHMgb2Z0ZW4gc3dpdGNoIHRoZWlyIHRyYW5zcG9uZGVycyBvZmYuPC9kaXY+PC9k
aXY+YCB9KTsKKyAgICB9KTsKKyAgfQorICByZXR1cm4geyB0aXRsZTogY2ZnLm5hbWUsIGl0ZW1z
LCBub3RlOiAod2Vla3MubGVuZ3RoID8gYCR7d2Vla3MubGVuZ3RofSB3ZWVrJHt3ZWVrcy5sZW5n
dGggPT09IDEgPyAiIiA6ICJzIn0ga2VwdGAgOiAibm90aGluZyBrZXB0IHlldCIpICsKKyAgICAo
dW5wbGFjZWQubGVuZ3RoID8gYCBcdTAwYjcgbm90IHBsYWNlZDogJHt1bnBsYWNlZC5qb2luKCI7
ICIpfWAgOiAiIikgfTsKK30KIGFzeW5jIGZ1bmN0aW9uIHJlYWRHZGVsdEdlbyhjZmcpIHsKICAg
bGV0IGdqID0gbnVsbCwgbm90ZSA9ICIiOwogICB0cnkgewpAQCAtMTQyMjAsNiArMTQyNDUsMTgg
QEAgY29uc3QgTUlMSVRBUlkgPSB7CiAgICAgeyBpZDogIm1pbF9uZXdzX2FyY2hpdmUiLCBuYW1l
OiAiTmV3cyBvZiBmaWdodGluZywgZXZlcnkgZGF5IHNpbmNlIHRoZSBtYXAgYmVnYW4ga2VlcGlu
ZyBpdCwgYnkgbW9udGggKEdERUxUKSIsIHVuaXQ6ICJwbGFjZXMgbmFtZWQiLCBjb2xvdXI6ICIj
N0E1QTU4Iiwgcm91dGU6ICJnZGVsdGFyY2hpdmUiLCByZWFkeTogdHJ1ZSwgbGF6eTogdHJ1ZSwK
ICAgICAgIGFyY2hpdmU6ICJodHRwczovL3dlbGNvbWV0b3lvdXJnYWxheHkuZ2l0aHViLmlvL2N1
bHByaXRzLXRpbGVzLW1vcmUvbWlsaXRhcnkvbmV3cyIsCiAgICAgICBub3RlOiAiRWFjaCBkYXkg
dGhlIHNldmVuIGRheXMgb2YgbmV3cyBhYm91dCBmaWdodGluZyB0aGF0IEdERUxUIHBsYWNlcyBv
biB0aGUgbWFwIGFyZSBrZXB0LCBhIG1vbnRoIHRvIGEgZmlsZSwgd2l0aCBldmVyeSBhcnRpY2xl
IGxpbmsgc2VlbiBmb3IgZWFjaCBwbGFjZTsgYSBjb3B5IHJlbmV3ZWQgZGFpbHkgYnkgY3VscHJp
dHMtdGlsZXMtbW9yZS4gTW9udGhzIGFyZSBjaGlwcyBvZiB0aGUgcm93LiIgfSwKKyAgICAvLyBS
b3VuZCA3OTogbnVjbGVhciB3ZWFwb25zIHN0b3JhZ2UgYXMgdGhlIE51Y2xlYXIgTm90ZWJvb2sg
c3RhdGVzIGl0OworICAgIC8vIFJ1c3NpYSdzIHN0b3JhZ2Ugc2l0ZXMgb24gdGhlaXIgb3duIG1h
cCAoaXRzIGxpY2VuY2UgYWxsb3dzIG5vIGNvcGllcyk7CisgICAgLy8gdGhlIFVTIE5hdnkgYXQg
c2VhIGFzIFVTTkkgTmV3cyB3b3JkcyBpdCBlYWNoIHdlZWsuCisgICAgeyBpZDogIm1pbF9udWNs
ZWFyX3N0b3JhZ2UiLCBuYW1lOiAiTnVjbGVhciB3ZWFwb25zIHN0b3JhZ2Ugc2l0ZXMsIGFzIHRo
ZSBOdWNsZWFyIE5vdGVib29rIHN0YXRlcyB0aGVtIChGQVMsIEJ1bGxldGluIG9mIHRoZSBBdG9t
aWMgU2NpZW50aXN0cykiLCB1bml0OiAic2l0ZXMiLCBjb2xvdXI6ICIjN0U1QTVBIiwgcm91dGU6
ICJnZW9qc29ubGl2ZSIsIHJlYWR5OiB0cnVlLCBsYXp5OiB0cnVlLAorICAgICAgZmlsZXM6IFt7
IGxhYmVsOiAiTnVjbGVhciBOb3RlYm9vayIsIHVybDogImh0dHBzOi8vd2VsY29tZXRveW91cmdh
bGF4eS5naXRodWIuaW8vY3VscHJpdHMtdGlsZXMtbW9yZS9taWxpdGFyeS9udWNsZWFyX3NpdGVz
Lmdlb2pzb24iIH1dLAorICAgICAgbm90ZTogIlRoZSBVUyBib21icyBpbiBFdXJvcGUgKEF2aWFu
bywgR2hlZGksIEluY2lybGlrLCBLbGVpbmUgQnJvZ2VsLCBWb2xrZWwsIELDvGNoZWwpLCBSQUYg
TGFrZW5oZWF0aCAoc3RhdHVzIHVuY2VydGFpbiksIHRoZSBkZXBvdCBuZWFyIEFzaXBvdmljaHkg
aW4gQmVsYXJ1cywgYW5kIHRoZSBVUyBzdG9yYWdlIGxvY2F0aW9ucyB0aGUgTm90ZWJvb2sgbmFt
ZXMsIGVhY2ggd2l0aCB0aGUgTm90ZWJvb2sncyBvd24gd29yZHMgYW5kIGVzdGltYXRlLiBQb3Np
dGlvbnMgYXMgdGhlIE5vdGVib29rIG9yIEZBUyBzdGF0ZSB0aGVtLCBvdGhlcndpc2UgV2lraWRh
dGEncywgc2FpZCBpbiBlYWNoIGJveC4gQ29waWVkIGRhaWx5IGJ5IGN1bHByaXRzLXRpbGVzLW1v
cmUuIiB9LAorICAgIHsgaWQ6ICJtaWxfcnVzc2lhX3N0b3JhZ2UiLCBuYW1lOiAiUnVzc2lhJ3Mg
bnVjbGVhciB3ZWFwb25zIHN0b3JhZ2Ugc2l0ZXM6IDEyIG5hdGlvbmFsLWxldmVsIGFuZCBhYm91
dCAzNSBiYXNlLWxldmVsIChSdXNzaWFuIFN0cmF0ZWdpYyBOdWNsZWFyIEZvcmNlcykiLCB1bml0
OiAib3BlbnMgdGhlIG1hcCBpdHNlbGYgaW4gYSBwYW5lbCIsIGNvbG91cjogIiM2QTVFNUEiLCBy
b3V0ZTogImNvbXBhbmlvbiIsIHJlYWR5OiB0cnVlLCBsYXp5OiB0cnVlLAorICAgICAgcGFnZTog
Imh0dHBzOi8vcnVzc2lhbmZvcmNlcy5vcmcvbWFwcy9SdXNzaWEtMTJ0aEdVTU8uaHRtbCIsCisg
ICAgICBub3RlOiAiUGF2ZWwgUG9kdmlnJ3MgbWFwIG9mIHRoZSAxMnRoIE1haW4gRGlyZWN0b3Jh
dGUncyBzdG9yYWdlIGZhY2lsaXRpZXMsIHNob3duIHdob2xlIGluIHRoZSBwYW5lbCBhbG9uZyB0
aGUgYm90dG9tOiBpdHMgbGljZW5jZSAoQ0MgQlktTkMtTkQgNC4wKSBkb2VzIG5vdCBhbGxvdyBp
dHMgcG9pbnRzIHRvIGJlIGNvcGllZCBvbnRvIHRoaXMgbWFwLiBIb3ZlciBhIGRvdCBmb3IgdGhl
IGZhY2lsaXR5J3MgbmFtZS4iIH0sCisgICAgeyBpZDogIm1pbF91c25pX2ZsZWV0IiwgbmFtZTog
IlVTIE5hdnkgc2hpcHMgYXQgc2VhLCB3ZWVrIGJ5IHdlZWsgKFVTTkkgTmV3cyBGbGVldCBhbmQg
TWFyaW5lIFRyYWNrZXIpIiwgdW5pdDogImFyZWFzIG5hbWVkIiwgY29sb3VyOiAiIzVFNjQ3MCIs
IHJvdXRlOiAidXNuaWZsZWV0IiwgcmVhZHk6IHRydWUsIGxhenk6IHRydWUsCisgICAgICBhcmNo
aXZlOiAiaHR0cHM6Ly93ZWxjb21ldG95b3VyZ2FsYXh5LmdpdGh1Yi5pby9jdWxwcml0cy10aWxl
cy1tb3JlL21pbGl0YXJ5L3VzbmkiLAorICAgICAgbm90ZTogIkVhY2ggd2Vla2x5IEZsZWV0IGFu
ZCBNYXJpbmUgVHJhY2tlciwgYSBtYXJrIHRvIGVhY2ggc2VhLCBvY2VhbiBvciBwb3J0IGl0IG5h
bWVzLCB3aXRoIGl0cyBwYXJhZ3JhcGhzIHF1b3RlZCB3aG9sZSBhbmQgbGlua2VkOyBldmVyeSB3
ZWVrIGtlcHQsIGVhY2ggYSBjaGlwLiBVU05JIGdpdmVzIG5vIGNvb3JkaW5hdGVzLCBzbyBlYWNo
IG1hcmsgaXMgdGhlIG1pZGRsZSBvZiB0aGUgYXJlYSBuYW1lZC4gQ29waWVkIGRhaWx5IGJ5IGN1
bHByaXRzLXRpbGVzLW1vcmUuIiB9LAogICAgIHsgaWQ6ICJtaWxfb3NtIiwgbmFtZTogIk1pbGl0
YXJ5IGFpcmZpZWxkcywgYmFzZXMsIG5hdmFsIGJhc2VzLCBiYXJyYWNrcywgcmFuZ2VzIGFuZCB0
cmFpbmluZyBhcmVhcywgaW4gdXNlIGFuZCBubyBsb25nZXIgKE9wZW5TdHJlZXRNYXApIiwgdW5p
dDogInBsYWNlcyIsIGNvbG91cjogIiM2RTYzNTgiLCByb3V0ZTogImdlb2pzb25saXZlIiwgcmVh
ZHk6IHRydWUsIGxhenk6IHRydWUsCiAgICAgICBmaWxlczogW3sgbGFiZWw6ICJPcGVuU3RyZWV0
TWFwIiwgdXJsOiAiaHR0cHM6Ly93ZWxjb21ldG95b3VyZ2FsYXh5LmdpdGh1Yi5pby9jdWxwcml0
cy10aWxlcy1tb3JlL21pbGl0YXJ5L29zbV9taWxpdGFyeS5nZW9qc29uIiB9XSwKICAgICAgIG5v
dGU6ICJFdmVyeSBwbGFjZSBPcGVuU3RyZWV0TWFwIHRhZ3MgbWlsaXRhcnk9YWlyZmllbGQsIGJh
c2UsIG5hdmFsX2Jhc2UsIGJhcnJhY2tzLCByYW5nZSwgdHJhaW5pbmdfYXJlYSBvciBudWNsZWFy
X2V4cGxvc2lvbl9zaXRlIChhbmQgd2FzOi9kaXN1c2VkOiBvbmVzKSwgZWFjaCBhdCBpdHMgbWlk
ZGxlLCBldmVyeSB0YWcga2VwdDsga2luZHMgYXJlIGNoaXBzIG9mIHRoZSByb3cuIEEgY29weSBy
ZW5ld2VkIGRhaWx5IGJ5IGN1bHByaXRzLXRpbGVzLW1vcmUgZnJvbSBPdmVycGFzcy4gT0RiTC4i
IH0sCkBAIC0xNDQ3Myw3ICsxNDUxMCw3IEBAIGZ1bmN0aW9uIGVuc3VyZUxheWVyKGNmZykgewog
ICAgICAgOiBjZmcucm91dGUgPT09ICJ3b3JsZHNyaW5nIiA/IGFkZFdvcmxkc1JpbmdMYXllcihj
ZmcpCiAgICAgICA6IGNmZy5yb3V0ZSA9PT0gInVmbyIgPyBhZGRVZm9MYXllcihjZmcpCiAgICAg
ICA6IGNmZy5yb3V0ZSA9PT0gImFkc2JtaWwiID8gYWRkQWRzYk1pbExheWVyKGNmZykKLSAgICAg
IDogWyJlamF0bGFzIiwgImdlb2pzb25saXZlIiwgIndwZ216YSIsICJhdGxhc2NpdGllcyIsICJ0
cmFzZWZhYyIsICJnZGVsdGdlbyIsICJnZGVsdGFyY2hpdmUiXS5pbmNsdWRlcyhjZmcucm91dGUp
ID8gYWRkTGl2ZVBsYWNlc0xheWVyKGNmZykKKyAgICAgIDogWyJlamF0bGFzIiwgImdlb2pzb25s
aXZlIiwgIndwZ216YSIsICJhdGxhc2NpdGllcyIsICJ0cmFzZWZhYyIsICJnZGVsdGdlbyIsICJn
ZGVsdGFyY2hpdmUiLCAidXNuaWZsZWV0Il0uaW5jbHVkZXMoY2ZnLnJvdXRlKSA/IGFkZExpdmVQ
bGFjZXNMYXllcihjZmcpCiAgICAgICA6IGNmZy5yb3V0ZSA9PT0gIndtc21lbnUiID8gYWRkV21z
TWVudUxheWVyKGNmZykKICAgICAgIDogY2ZnLnJvdXRlID09PSAiZ2Z3bWVudSIgPyBhZGRHZndN
ZW51TGF5ZXIoY2ZnKQogICAgICAgOiBhZGRQbXRpbGVzTGF5ZXIoY2ZnKTsKQEAgLTE1NDc3LDYg
KzE1NTE0LDcgQEAgY29uc3QgTk9UX0xJVkUgPSB7CiAgIG1pbF9hdHRhY2tzOiAiQ29waWVkIGRh
aWx5IGZyb20gV2lraWRhdGEgYnkgY3VscHJpdHMtdGlsZXMtbW9yZSIsCiAgIG1pbF9zaXRlczog
IkNvcGllZCBkYWlseSBmcm9tIFdpa2lkYXRhIGJ5IGN1bHByaXRzLXRpbGVzLW1vcmUiLAogICBt
aWxfb3NtOiAiQ29waWVkIGRhaWx5IGZyb20gT3BlblN0cmVldE1hcCBieSBjdWxwcml0cy10aWxl
cy1tb3JlIiwKKyAgbWlsX251Y2xlYXJfc3RvcmFnZTogIldyaXR0ZW4gZnJvbSB0aGUgTnVjbGVh
ciBOb3RlYm9vazsgcG9zaXRpb25zIGxvb2tlZCB1cCBkYWlseSBieSBjdWxwcml0cy10aWxlcy1t
b3JlIiwKICAgbWlsX21pcnRhOiAiQ29waWVkIGRhaWx5IGZyb20gY2F0YWxvZy5kYXRhLmdvdiBi
eSBjdWxwcml0cy10aWxlcy1tb3JlIiwKICAgbWlsX3VuaXRzOiAiQ29waWVkIGRhaWx5IGZyb20g
V2lraWRhdGEgYnkgY3VscHJpdHMtdGlsZXMtbW9yZSIsCiAgIG1pbF90ZXN0X3NpdGVzOiAiQ29w
aWVkIGRhaWx5IGZyb20gV2lraWRhdGEgYnkgY3VscHJpdHMtdGlsZXMtbW9yZSIsCkBAIC0xNTU1
Myw3ICsxNTU5MSw3IEBAIGNvbnN0IFBBTkVMX09SREVSID0gWwogICAvLyBwbGFjZSBvZiB0aGUg
R3VlcmlsbGFtYXAgcm93LCB3aGljaCBjb3VsZCBvbmx5IGxpbmsgdG8gYW5vdGhlciBzaXRlLgog
ICB7IGg6IDMsIHQ6ICJPZiBjb3VudHJpZXMgYnkgY291bnRyaWVzIiB9LCAic2l0ZV9zZWNyZXRf
c29jaWV0aWVzIiwKICAgeyBoOiA0LCBidW5kbGU6ICJtaWxpdGFyeSIsIGNvbG91cjogIiM2QTVF
NUEiIH0sICJtaWxfbmV3cyIsICJtaWxfbmV3c19hcmNoaXZlIiwgIm1pbF9jb25mbGljdHMiLCAi
bWlsX2F0dGFja3MiLCAibWlsX2FpcmNyYWZ0IiwgIm1pbF9zaXRlcyIsICJtaWxfdW5pdHMiLAot
ICAibWlsX29zbSIsICJtaWxfbWlydGEiLCAibWlsX3Rlc3Rfc2l0ZXMiLCAibWlsX21pbmVmaWVs
ZHMiLCAibWlsX2FsbGlhbmNlcyIsCisgICJtaWxfbnVjbGVhcl9zdG9yYWdlIiwgIm1pbF9ydXNz
aWFfc3RvcmFnZSIsICJtaWxfdXNuaV9mbGVldCIsICJtaWxfb3NtIiwgIm1pbF9taXJ0YSIsICJt
aWxfdGVzdF9zaXRlcyIsICJtaWxfbWluZWZpZWxkcyIsICJtaWxfYWxsaWFuY2VzIiwKICAgeyBo
OiA1LCBidW5kbGU6ICJtaWxjb21wYXJlIiwgY29sb3VyOiAiIzZFNUY1MiIgfSwgIm1pbF9zcGVu
ZF9nZHAiLCAibWlsX3NwZW5kX2dvdiIsICJtaWxfc3BlbmRfdXNkIiwgIm1pbF9wZXJzb25uZWwi
LCAibWlsX3dhcmhlYWRzIiwgIm1pbF90ZXN0cyIsICJtaWxfbnVjbGVhcl9wb3NpdGlvbiIsCiAg
IC8vIFJvdW5kIDc3OiB0aGUgd2hvbGUgVW5lYXJ0aGluZ3MgbWFwLCBpbiBpdHMgb3duIG9yZGVy
LgogICB7IGg6IDIsIHQ6ICJJbnZhc2lvbiBvZiB0aGUgYWZ0ZXItbGlmZSIgfSwgInJlbWFpbnNf
cmVjb3JkcyIsICJyZW1haW5zX3VuaXRzIiwgInJlbWFpbnNfZmluZGluZ3MiLCAicmVtYWluc19j
ZW1ldGVyaWVzIiwKZGlmZiAtLWdpdCBhL21hcC9pbmRleC5odG1sIGIvbWFwL2luZGV4Lmh0bWwK
aW5kZXggYWJhZDUxNC4uNjU4NTUzMiAxMDA2NDQKLS0tIGEvbWFwL2luZGV4Lmh0bWwKKysrIGIv
bWFwL2luZGV4Lmh0bWwKQEAgLTUxOCw3ICs1MTgsNyBAQAogICB9OwogfSkoKTsKIDwvc2NyaXB0
PgotPHNjcmlwdCBzcmM9Ii4vYXBwLmpzP3Y9NzgiPjwvc2NyaXB0PgorPHNjcmlwdCBzcmM9Ii4v
YXBwLmpzP3Y9NzkiPjwvc2NyaXB0PgogPHNjcmlwdCBzcmM9Ii4vd2lyZS5qcz92PTY3Ij48L3Nj
cmlwdD4KIDwhLS0gVGhlIGRyYWcgYmFyIG9uIHRoZSBsYXllcnMgYm94J3MgcmlnaHQgZWRnZSAo
bWFkZSBieSBjb2x1bW5FZGdlKCkgaW4KICAgICAgYXBwLmpzKSByYW4gdGhlIGZ1bGwgaGVpZ2h0
IG9mIHRoZSBjb2x1bW4sIHNvIGl0IHN0YXllZCBzdGFuZGluZyBiZXNpZGUKZGlmZiAtLWdpdCBh
L21hcC90ZXN0Lm1qcyBiL21hcC90ZXN0Lm1qcwppbmRleCBlZWMwMmNmLi4xYmM2MDI5IDEwMDY0
NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rlc3QubWpzCkBAIC00Nzk1LDUgKzQ3OTUs
MTggQEAgQUFBQUFBQUFBQUFBIEFBQUFBQUFBQUFBQUFBQUEgfCBOTk5OIHwgICAgQSAgICB8IFlZ
WVktTU0tREQgSEg6TU0gfCBFRUVFRUVFRSB8IE4KICAgICAgICAgLyJtaWxfb3NtIiwgIm1pbF9t
aXJ0YSIsICJtaWxfdGVzdF9zaXRlcyIvLnRlc3Qoc3JjKSAmJiAvbWlsX29zbTogIkNvcGllZCBk
YWlseSBmcm9tIE9wZW5TdHJlZXRNYXAvLnRlc3Qoc3JjKSAmJiAvbWlsX21pcnRhOiAiQ29waWVk
IGRhaWx5IGZyb20gY2F0YWxvZ1wuZGF0YVwuZ292Ly50ZXN0KHNyYykpOwogICBjaGVjaygidGhl
IHBhZ2UgYXNrcyBmb3IgdGhpcyByb3VuZCdzIHNjcmlwdCIsIC9hcHBcLmpzXD92PSg3WzgtOV18
Wzg5XVxkKS8udGVzdChodG1sKSk7CiB9Cit7CisgIGNvbnNvbGUubG9nKCJcbnJvdW5kIDc5OiBu
dWNsZWFyIHdlYXBvbnMgc3RvcmFnZSwgUnVzc2lhJ3Mgc3RvcmFnZSBtYXAsIHRoZSBVUyBOYXZ5
IGF0IHNlYSIpOworICBjb25zdCBzcmMgPSBmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUs
ICJhcHAuanMiKSwgInV0ZjgiKTsKKyAgY29uc3QgaHRtbCA9IGZzLnJlYWRGaWxlU3luYyhwYXRo
LmpvaW4oSEVSRSwgImluZGV4Lmh0bWwiKSwgInV0ZjgiKTsKKyAgY2hlY2soInRoZSB0aHJlZSBy
b3dzIHNpdCBpbiB0aGUgbWlsaXRhcnkgbGF5ZXIiLAorICAgICAgICAvIm1pbF9udWNsZWFyX3N0
b3JhZ2UiLCAibWlsX3J1c3NpYV9zdG9yYWdlIiwgIm1pbF91c25pX2ZsZWV0IiwgIm1pbF9vc20i
Ly50ZXN0KHNyYykgJiYKKyAgICAgICAgL2lkOiAibWlsX251Y2xlYXJfc3RvcmFnZSJbXlxuXSpy
b3V0ZTogImdlb2pzb25saXZlIi8udGVzdChzcmMpICYmIC9pZDogIm1pbF91c25pX2ZsZWV0Ilte
XG5dKnJvdXRlOiAidXNuaWZsZWV0Ii8udGVzdChzcmMpKTsKKyAgY2hlY2soIlJ1c3NpYSdzIHN0
b3JhZ2UgbWFwIGlzIHNob3duIHdob2xlLCBub3QgY29waWVkIChpdHMgbGljZW5jZSBhbGxvd3Mg
bm8gZGVyaXZhdGl2ZXMpIiwKKyAgICAgICAgL2lkOiAibWlsX3J1c3NpYV9zdG9yYWdlIlteXG5d
KnJvdXRlOiAiY29tcGFuaW9uIi8udGVzdChzcmMpICYmIC9wYWdlOiAiaHR0cHM6XC9cL3J1c3Np
YW5mb3JjZXNcLm9yZ1wvbWFwc1wvUnVzc2lhLTEydGhHVU1PXC5odG1sIi8udGVzdChzcmMpKTsK
KyAgY2hlY2soImVhY2ggVVNOSSB3ZWVrIGlzIGEgY2hpcCwgZXZlcnkgaGVhZGluZydzIHdvcmRz
IHF1b3RlZCwgYW5kIHRoZSBib3ggc2F5cyB0aGUgbWFyayBpcyB0aGUgbWlkZGxlIG9mIHRoZSBh
cmVhIiwKKyAgICAgICAgL2dyb3VwOiBgd2VlayBvZiBcJFx7d1x9YC8udGVzdChzcmMpICYmIC9V
U05JIGdpdmVzIG5vIGNvb3JkaW5hdGVzLCBhbmQgd2Fyc2hpcHMgb2Z0ZW4gc3dpdGNoIHRoZWly
IHRyYW5zcG9uZGVycyBvZmYvLnRlc3Qoc3JjKSk7CisgIGNoZWNrKCJ0aGUgcGFnZSBhc2tzIGZv
ciB0aGlzIHJvdW5kJ3Mgc2NyaXB0IiwgL2FwcFwuanNcP3Y9KDc5fFs4OV1cZCkvLnRlc3QoaHRt
bCkpOworfQogY29uc29sZS5sb2coYFxuJHtwYXNzfSBwYXNzZWQsICR7ZmFpbH0gZmFpbGVkXG5g
KTsKIHByb2Nlc3MuZXhpdChmYWlsID8gMSA6IDApOwo=
""")
FILES = ["map/app.js", "map/index.html", "map/test.mjs"]
def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True)
if not os.path.exists("map/app.js"):
    sys.exit("Run this from the culprits folder.")
with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
    f.write(DIFF); path = f.name
if git("apply", "--check", "-R", path).returncode == 0:
    print("Already applied. Nothing changed.")
else:
    r = git("apply", "--3way", path)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        git("checkout", "--", *[x for x in FILES if os.path.exists(x)])
        for x in FILES:
            if git("ls-files", "--error-unmatch", x).returncode != 0 and os.path.exists(x):
                os.remove(x)
        sys.exit("Did not apply; nothing changed. Round 78 must be applied first.")
    print("Code changes applied.")
os.unlink(path)
if os.path.exists("HANDOFF.md"):
    h = open("HANDOFF.md", encoding="utf-8").read()
    if "Round 79 (27 September)" not in h:
        i = h.index("---") + 3
        open("HANDOFF.md", "w", encoding="utf-8").write(h[:i] + "\n" + NOTE + h[i:])
        print("HANDOFF.md note added.")
