#!/usr/bin/env python3
"""Round 70 (26 September): the largest banks row is corporate banks only; development banks get a row of their own. Needs round 69 first (they run in name order). Upload to the culprits repo's patches folder. Safe to run twice."""
import base64, subprocess, sys, os, tempfile
NOTE = """
## Round 70 (26 September)

- Owner, 26 September: they already have a central banks layer, so the
  largest banks row is corporate banks only, and development banks go in a
  row of their own. culprits-tiles-more scripts/largest_banks.py (round 70
  tiles patch) now sorts every item with total assets by Wikidata class,
  found by English name at build time ("central bank", "development bank",
  "multilateral development bank"; the build stops if one is missing):
  central banks are left out (listed in banks/largest.build.json),
  development banks all go to banks/development.geojson, and the 250 largest
  other banks to banks/largest.geojson.
- Rows: largest_banks renamed "The 250 largest corporate banks by total
  assets"; new development_banks ("Development banks by total assets, national
  and multilateral"), filed beside it under Banks and monetary power.
"""
DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDdhYWMwMTAuLjAzMDE5
ZTcgMTAwNjQ0Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMTIxMTMsMTAg
KzEyMTEzLDE1IEBAIGNvbnN0IE9USEVSX01BUFMgPSB7CiAgICAgICBub3RlOiAiQ29tcGlsZWQg
aGVyZSBpbiBwbGFjZSBvZiBGb3J0dW5lJ3MgR2xvYmFsIDUwMCwgd2hvc2UgdGVybXMgZm9yYmlk
IGNvcHlpbmcgaXQuIEV2ZXJ5IGNvbXBhbnkgV2lraWRhdGEgZ2l2ZXMgYSB0b3RhbCByZXZlbnVl
IGZvciwgYXQgaXRzIGxhdGVzdCB5ZWFyLCB0dXJuZWQgaW50byBVUyBkb2xsYXJzIGF0IHRoYXQg
eWVhcidzIGF2ZXJhZ2UgcmF0ZSAodGhlIEV1cm9wZWFuIENlbnRyYWwgQmFuaydzLCBvciBmb3Ig
Y3VycmVuY2llcyBpdCBkb2VzIG5vdCBwdWJsaXNoLCB0aGUgV29ybGQgQmFuaydzIG9mZmljaWFs
IHJhdGUpLCBhbmQgdGhlIDUwMCBsYXJnZXN0IHRoYXQgV2lraWRhdGEgc2F5cyBhcmUgYnVzaW5l
c3Nlcy4gRWFjaCBib3ggc2hvd3MgZXZlcnl0aGluZyBnYXRoZXJlZDogcmFuaywgcmV2ZW51ZSBh
cyBzdGF0ZWQgYW5kIGluIGRvbGxhcnMsIHRoZSByYXRlIHVzZWQsIGhlYWRxdWFydGVycywgY291
bnRyeSwgaW5kdXN0cnksIGVtcGxveWVlcywgZm91bmRpbmcgZGF0ZSwgd2Vic2l0ZSwgc3RvY2sg
ZXhjaGFuZ2UsIHBhcmVudCBhbmQgY2hpZWYgZXhlY3V0aXZlLCB3aXRoIGEgbGluayB0byB0aGUg
V2lraWRhdGEgcGFnZS4gV2lraWRhdGEgaXMgZWRpdGVkIGJ5IGFueW9uZSwgc28gYSBmaWd1cmUg
Y2FuIGJlIG91dCBvZiBkYXRlIG9yIHdyb25nOyB0aGUgbGluayBzaG93cyB3aGVyZSBpdCBjYW1l
IGZyb20uIEEgY29tcGFueSB3aG9zZSBoZWFkcXVhcnRlcnMgaGFzIG5vIHBvc2l0aW9uIGluIFdp
a2lkYXRhIGlzIGxpc3RlZCBpbiB0aGUgYnVpbGQgZmlsZSwgbm90IHBsYWNlZC4gUmVidWlsdCB3
ZWVrbHkgYnkgY3VscHJpdHMtdGlsZXMtbW9yZS4iIH0sCiAgICAgLy8gQXNrZWQgZm9yIDI2IFNl
cHRlbWJlciAocm91bmQgNjkpOiB0aGUgb3duZXIncyBvd24gbGlzdCBvZiB0aGUgd29ybGQncwog
ICAgIC8vIGxhcmdlc3QgYmFua3MsIGNvbXBpbGVkIHRoZSB3YXkgdGhlIGNvbXBhbmllcyByb3cg
aXMuCi0gICAgeyBpZDogImxhcmdlc3RfYmFua3MiLCBuYW1lOiAiVGhlIDI1MCBsYXJnZXN0IGJh
bmtzIGJ5IHRvdGFsIGFzc2V0cyAoY29tcGlsZWQgZnJvbSBXaWtpZGF0YSkiLCB1bml0OiAiYmFu
a3MsIGF0IHRoZWlyIGhlYWRxdWFydGVycyIsIGNvbG91cjogIiM2QTVENkIiLCByb3V0ZTogImdl
b2pzb25saXZlIiwgcmVhZHk6IHRydWUsIGxhenk6IHRydWUsCi0gICAgICBmaWxlczogW3sgbGFi
ZWw6ICJUaGUgMjUwIGxhcmdlc3QgYmFua3MgYnkgdG90YWwgYXNzZXRzIiwgdXJsOiAiaHR0cHM6
Ly93ZWxjb21ldG95b3VyZ2FsYXh5LmdpdGh1Yi5pby9jdWxwcml0cy10aWxlcy1tb3JlL2Jhbmtz
L2xhcmdlc3QuZ2VvanNvbiIgfV0sCisgICAgeyBpZDogImxhcmdlc3RfYmFua3MiLCBuYW1lOiAi
VGhlIDI1MCBsYXJnZXN0IGNvcnBvcmF0ZSBiYW5rcyBieSB0b3RhbCBhc3NldHMgKGNvbXBpbGVk
IGZyb20gV2lraWRhdGEpIiwgdW5pdDogImJhbmtzLCBhdCB0aGVpciBoZWFkcXVhcnRlcnMiLCBj
b2xvdXI6ICIjNkE1RDZCIiwgcm91dGU6ICJnZW9qc29ubGl2ZSIsIHJlYWR5OiB0cnVlLCBsYXp5
OiB0cnVlLAorICAgICAgZmlsZXM6IFt7IGxhYmVsOiAiVGhlIDI1MCBsYXJnZXN0IGNvcnBvcmF0
ZSBiYW5rcyBieSB0b3RhbCBhc3NldHMiLCB1cmw6ICJodHRwczovL3dlbGNvbWV0b3lvdXJnYWxh
eHkuZ2l0aHViLmlvL2N1bHByaXRzLXRpbGVzLW1vcmUvYmFua3MvbGFyZ2VzdC5nZW9qc29uIiB9
XSwKICAgICAgIGF0dHJpYnV0aW9uOiAiV2lraWRhdGEgKENDMCk7IGV4Y2hhbmdlIHJhdGVzIGZy
b20gdGhlIEV1cm9wZWFuIENlbnRyYWwgQmFuayBhbmQgdGhlIFdvcmxkIEJhbmsiLAotICAgICAg
bm90ZTogIkNvbXBpbGVkIGhlcmUgZnJvbSBvcGVuIGRhdGEgcmF0aGVyIHRoYW4gY29waWVkIGZy
b20gYSBwdWJsaXNoZWQgcmFua2luZy4gRXZlcnkgaXRlbSBXaWtpZGF0YSBnaXZlcyBhIHRvdGFs
IGFzc2V0cyBmaWd1cmUgZm9yLCBhdCBpdHMgbGF0ZXN0IHllYXIsIHR1cm5lZCBpbnRvIFVTIGRv
bGxhcnMgYXQgdGhhdCB5ZWFyJ3MgYXZlcmFnZSByYXRlICh0aGUgRXVyb3BlYW4gQ2VudHJhbCBC
YW5rJ3MsIG9yIGZvciBjdXJyZW5jaWVzIGl0IGRvZXMgbm90IHB1Ymxpc2gsIHRoZSBXb3JsZCBC
YW5rJ3Mgb2ZmaWNpYWwgcmF0ZSksIGFuZCB0aGUgMjUwIGxhcmdlc3QgdGhhdCBXaWtpZGF0YSBz
YXlzIGFyZSBhIGtpbmQgb2YgYmFuay4gQ2VudHJhbCBiYW5rcywgZGV2ZWxvcG1lbnQgYmFua3Mg
YW5kIHRoZSByZXN0IGFyZSBhbGwga2VwdCwgZWFjaCBib3ggc2F5aW5nIHdoYXQga2luZCBvZiBi
YW5rIFdpa2lkYXRhIGNhbGxzIGl0LiBZZWFycyBjYW4gZGlmZmVyIGZyb20gYmFuayB0byBiYW5r
OyBlYWNoIGJveCBnaXZlcyB0aGUgeWVhciBvZiBpdHMgZmlndXJlLiBFYWNoIGJveCBzaG93cyBl
dmVyeXRoaW5nIGdhdGhlcmVkOiByYW5rLCB0b3RhbCBhc3NldHMgYXMgc3RhdGVkIGFuZCBpbiBk
b2xsYXJzLCB0aGUgcmF0ZSB1c2VkLCBraW5kLCBoZWFkcXVhcnRlcnMsIGNvdW50cnksIGVtcGxv
eWVlcywgZm91bmRpbmcgZGF0ZSwgd2Vic2l0ZSwgc3RvY2sgZXhjaGFuZ2UsIHBhcmVudCwgb3du
ZXIgYW5kIGNoaWVmIGV4ZWN1dGl2ZSwgd2l0aCBhIGxpbmsgdG8gdGhlIFdpa2lkYXRhIHBhZ2Uu
IFdpa2lkYXRhIGlzIGVkaXRlZCBieSBhbnlvbmUsIHNvIGEgZmlndXJlIGNhbiBiZSBvdXQgb2Yg
ZGF0ZSBvciB3cm9uZzsgdGhlIGxpbmsgc2hvd3Mgd2hlcmUgaXQgY2FtZSBmcm9tLiBBIGJhbmsg
d2hvc2UgaGVhZHF1YXJ0ZXJzIGhhcyBubyBwb3NpdGlvbiBpbiBXaWtpZGF0YSBpcyBsaXN0ZWQg
aW4gdGhlIGJ1aWxkIGZpbGUsIG5vdCBwbGFjZWQuIFJlYnVpbHQgd2Vla2x5IGJ5IGN1bHByaXRz
LXRpbGVzLW1vcmUuIiB9LAorICAgICAgbm90ZTogIkNvbXBpbGVkIGhlcmUgZnJvbSBvcGVuIGRh
dGEgcmF0aGVyIHRoYW4gY29waWVkIGZyb20gYSBwdWJsaXNoZWQgcmFua2luZy4gRXZlcnkgaXRl
bSBXaWtpZGF0YSBnaXZlcyBhIHRvdGFsIGFzc2V0cyBmaWd1cmUgZm9yLCBhdCBpdHMgbGF0ZXN0
IHllYXIsIHR1cm5lZCBpbnRvIFVTIGRvbGxhcnMgYXQgdGhhdCB5ZWFyJ3MgYXZlcmFnZSByYXRl
ICh0aGUgRXVyb3BlYW4gQ2VudHJhbCBCYW5rJ3MsIG9yIGZvciBjdXJyZW5jaWVzIGl0IGRvZXMg
bm90IHB1Ymxpc2gsIHRoZSBXb3JsZCBCYW5rJ3Mgb2ZmaWNpYWwgcmF0ZSksIGFuZCB0aGUgMjUw
IGxhcmdlc3QgdGhhdCBXaWtpZGF0YSBzYXlzIGFyZSBhIGtpbmQgb2YgYmFuaywgbGVhdmluZyBv
dXQgY2VudHJhbCBiYW5rcyAodGhlaXIgb3duIGxheWVyLCBDZW50cmFsIEJhbmtzKSBhbmQgZGV2
ZWxvcG1lbnQgYmFua3MgKHRoZWlyIG93biByb3csIGJlbG93KS4gU3RhdGUtb3duZWQgY29tbWVy
Y2lhbCBiYW5rcyBhcmUgY29ycG9yYXRlIGJhbmtzIGFuZCBhcmUga2VwdC4gWWVhcnMgY2FuIGRp
ZmZlciBmcm9tIGJhbmsgdG8gYmFuazsgZWFjaCBib3ggZ2l2ZXMgdGhlIHllYXIgb2YgaXRzIGZp
Z3VyZSwgd2l0aCByYW5rLCB0b3RhbCBhc3NldHMgYXMgc3RhdGVkIGFuZCBpbiBkb2xsYXJzLCB0
aGUgcmF0ZSB1c2VkLCBraW5kLCBoZWFkcXVhcnRlcnMsIGNvdW50cnksIGVtcGxveWVlcywgZm91
bmRpbmcgZGF0ZSwgd2Vic2l0ZSwgc3RvY2sgZXhjaGFuZ2UsIHBhcmVudCwgb3duZXIgYW5kIGNo
aWVmIGV4ZWN1dGl2ZSwgYW5kIGEgbGluayB0byB0aGUgV2lraWRhdGEgcGFnZS4gV2lraWRhdGEg
aXMgZWRpdGVkIGJ5IGFueW9uZSwgc28gYSBmaWd1cmUgY2FuIGJlIG91dCBvZiBkYXRlIG9yIHdy
b25nLiBBIGJhbmsgd2hvc2UgaGVhZHF1YXJ0ZXJzIGhhcyBubyBwb3NpdGlvbiBpbiBXaWtpZGF0
YSBpcyBsaXN0ZWQgaW4gdGhlIGJ1aWxkIGZpbGUsIG5vdCBwbGFjZWQuIFJlYnVpbHQgd2Vla2x5
IGJ5IGN1bHByaXRzLXRpbGVzLW1vcmUuIiB9LAorICAgIC8vIEFza2VkIDI2IFNlcHRlbWJlciAo
cm91bmQgNzApOiBkZXZlbG9wbWVudCBiYW5rcyBhcGFydCBmcm9tIHRoZSBvdGhlcnMuCisgICAg
eyBpZDogImRldmVsb3BtZW50X2JhbmtzIiwgbmFtZTogIkRldmVsb3BtZW50IGJhbmtzIGJ5IHRv
dGFsIGFzc2V0cywgbmF0aW9uYWwgYW5kIG11bHRpbGF0ZXJhbCAoY29tcGlsZWQgZnJvbSBXaWtp
ZGF0YSkiLCB1bml0OiAiYmFua3MsIGF0IHRoZWlyIGhlYWRxdWFydGVycyIsIGNvbG91cjogIiM1
RTY0NzAiLCByb3V0ZTogImdlb2pzb25saXZlIiwgcmVhZHk6IHRydWUsIGxhenk6IHRydWUsCisg
ICAgICBmaWxlczogW3sgbGFiZWw6ICJEZXZlbG9wbWVudCBiYW5rcyBieSB0b3RhbCBhc3NldHMi
LCB1cmw6ICJodHRwczovL3dlbGNvbWV0b3lvdXJnYWxheHkuZ2l0aHViLmlvL2N1bHByaXRzLXRp
bGVzLW1vcmUvYmFua3MvZGV2ZWxvcG1lbnQuZ2VvanNvbiIgfV0sCisgICAgICBhdHRyaWJ1dGlv
bjogIldpa2lkYXRhIChDQzApOyBleGNoYW5nZSByYXRlcyBmcm9tIHRoZSBFdXJvcGVhbiBDZW50
cmFsIEJhbmsgYW5kIHRoZSBXb3JsZCBCYW5rIiwKKyAgICAgIG5vdGU6ICJCYW5rcyBvd25lZCBi
eSBvbmUgZ292ZXJubWVudCAobmF0aW9uYWwsIHN1Y2ggYXMgQ2hpbmEgRGV2ZWxvcG1lbnQgQmFu
aywgS2ZXIG9yIEJOREVTKSBvciBieSBzZXZlcmFsIChtdWx0aWxhdGVyYWwsIHN1Y2ggYXMgdGhl
IFdvcmxkIEJhbmsncyBJQlJELCB0aGUgQXNpYW4gRGV2ZWxvcG1lbnQgQmFuayBvciB0aGUgRXVy
b3BlYW4gSW52ZXN0bWVudCBCYW5rKSwgc2V0IHVwIHRvIGxlbmQgZm9yIGRldmVsb3BtZW50OiBk
YW1zLCByb2FkcywgcG93ZXIsIG1pbmVzLCBmYXJtaW5nIGFuZCB0aGUgbGlrZS4gRXZlcnkgaXRl
bSBXaWtpZGF0YSBzYXlzIGlzIGEgZGV2ZWxvcG1lbnQgYmFuayBvciBtdWx0aWxhdGVyYWwgZGV2
ZWxvcG1lbnQgYmFuayBhbmQgZ2l2ZXMgYSB0b3RhbCBhc3NldHMgZmlndXJlIGZvciwgYXQgaXRz
IGxhdGVzdCB5ZWFyLCBpbiBVUyBkb2xsYXJzIGF0IHRoYXQgeWVhcidzIGF2ZXJhZ2UgcmF0ZSwg
cmFua2VkIGJ5IHNpemUuIEEgZGV2ZWxvcG1lbnQgYmFuayB3aXRoIG5vIHRvdGFsIGFzc2V0cyBm
aWd1cmUgaW4gV2lraWRhdGEgaXMgbm90IG9uIGl0LiBFYWNoIGJveCBzaG93cyBldmVyeSBmaWVs
ZCBnYXRoZXJlZCwgd2l0aCBhIGxpbmsgdG8gdGhlIFdpa2lkYXRhIHBhZ2UuIFJlYnVpbHQgd2Vl
a2x5IGJ5IGN1bHByaXRzLXRpbGVzLW1vcmUuIiB9LAogICAgIHsgaWQ6ICJ0aGV5cnVsZSIsIG5h
bWU6ICJUaGV5IFJ1bGUiLCB1bml0OiAib3BlbnMgdGhlIHBhZ2UgaXRzZWxmIGluIGEgcGFuZWwi
LCBjb2xvdXI6ICIjNkE2MjU4Iiwgcm91dGU6ICJjb21wYW5pb24iLCByZWFkeTogdHJ1ZSwgbGF6
eTogdHJ1ZSwKICAgICAgIHBhZ2U6ICJodHRwczovL3RoZXlydWxlLm5ldC8iLAogICAgICAgbm90
ZTogIlRoZSBwYWdlIGFzIHRoZSBzaXRlIHNob3dzIGl0LCB3aG9sZSwgaW4gdGhlIHBhbmVsIGFs
b25nIHRoZSBib3R0b207IGl0cyBkYXRhIGNhbm5vdCBiZSByZWFkIGRpcmVjdGx5IHRvIGRyYXcg
aGVyZS4iIH0sCkBAIC0xMjgxMyw2ICsxMjgxOCw3IEBAIGNvbnN0IExBWUVSX0tJTkQgPSB7CiAg
IGZvcmVzdF9tYW5hZ2VtZW50OiBbInBsYW50IiwgImRvd25zdHJlYW0iXSwKICAgbGFyZ2VzdF9j
b21wYW5pZXM6IFsiaHVtYW4iLCAidXBzdHJlYW0iXSwKICAgbGFyZ2VzdF9iYW5rczogWyJodW1h
biIsICJ1cHN0cmVhbSJdLAorICBkZXZlbG9wbWVudF9iYW5rczogWyJodW1hbiIsICJ1cHN0cmVh
bSJdLAogICB0aGV5cnVsZTogWyJodW1hbiIsICJ1cHN0cmVhbSJdLAogICBwZV9iYW5rcm9sbGlu
ZzogWyJhbmltYWwiLCAidXBzdHJlYW0iXSwKICAgcGVfYmFua3M6IFsiYW5pbWFsIiwgInVwc3Ry
ZWFtIl0sCkBAIC0xMzQzNyw2ICsxMzQ0Myw3IEBAIGNvbnN0IExBWUVSX1NJVEUgPSB7CiAgIGZp
c2hpbmc6ICJodHRwczovL2dsb2JhbGZpc2hpbmd3YXRjaC5vcmciLAogICBsYXJnZXN0X2NvbXBh
bmllczogImh0dHBzOi8vcXVlcnkud2lraWRhdGEub3JnIiwKICAgbGFyZ2VzdF9iYW5rczogImh0
dHBzOi8vcXVlcnkud2lraWRhdGEub3JnIiwKKyAgZGV2ZWxvcG1lbnRfYmFua3M6ICJodHRwczov
L3F1ZXJ5Lndpa2lkYXRhLm9yZyIsCiAgIGZyYWN0cmFja2VyX3JlZmluZXJpZXM6ICJodHRwczov
L3d3dy5mcmFjdHJhY2tlci5vcmciLAogICBnZW1fY29hbDogImh0dHBzOi8vZ2l0aHViLmNvbS9H
cmVlbkluZm8tTmV0d29yay9jb2FsLXRyYWNrZXItY2xpZW50IiwKICAgZ2Z3X2NhdGFsb2d1ZTog
Imh0dHBzOi8vZGF0YS1hcGkuZ2xvYmFsZm9yZXN0d2F0Y2gub3JnIiwKQEAgLTEzNjI5LDYgKzEz
NjM2LDcgQEAgY29uc3QgTk9UX0xJVkUgPSB7CiAgIHNvaWxfbmVtYXRvZGVzOiAiQ29waWVkIGZy
b20gaXRzIGZpZ3NoYXJlIGRhdGEgcmVjb3JkOyBjb3BpZWQgYWdhaW4gb25seSB3aGVuIGEgZmls
ZSBjaGFuZ2VzIiwKICAgbGFyZ2VzdF9jb21wYW5pZXM6ICJDb21waWxlZCB3ZWVrbHkgZnJvbSBX
aWtpZGF0YSBieSBjdWxwcml0cy10aWxlcy1tb3JlIiwKICAgbGFyZ2VzdF9iYW5rczogIkNvbXBp
bGVkIHdlZWtseSBmcm9tIFdpa2lkYXRhIGJ5IGN1bHByaXRzLXRpbGVzLW1vcmUiLAorICBkZXZl
bG9wbWVudF9iYW5rczogIkNvbXBpbGVkIHdlZWtseSBmcm9tIFdpa2lkYXRhIGJ5IGN1bHByaXRz
LXRpbGVzLW1vcmUiLAogICBjb2FzdGFsX2NsZWFudXA6ICJPY2VhbiBDb25zZXJ2YW5jeSdzIGNs
ZWFudXAgc2l0ZXMsIGZyb20gYSBjb3B5IG1hZGUgZGFpbHkgKHRoZWlyIHNlcnZlciBsZXRzIG9u
bHkgdGhlaXIgb3duIHNpdGUgcmVhZCBpdCkiLAogICBmb29kX3NveTogIkJ1aWx0IG9uY2UgZnJv
bSB0aGUgMjAxNyBkYXRhIHBhY2thZ2Ugb2YgSGFscGVybiBldCBhbC4gMjAyMjsgaXQgaXMgbm90
IHVwZGF0ZWQiLAogICB3YXN0ZXdhdGVyX3BsdW1lczogIkJ1aWx0IG9uY2UgZnJvbSB0aGUgR2xv
YmFsIFdhc3Rld2F0ZXIgTW9kZWwncyAyMDIxIGRhdGEgcGFja2FnZTsgaXQgaXMgbm90IHVwZGF0
ZWQiLApAQCAtMTM4NTIsNyArMTM4NjAsNyBAQCBjb25zdCBQQU5FTF9PUkRFUiA9IFsKICAgeyBo
OiAyLCB0OiAiT2YgaHVtYW5zIiB9LAogICB7IGg6IDMsIHQ6ICJQaHlzaWNhbCBzdXBwcmVzc2lv
biIgfSwKICAgeyBoOiA0LCB0OiAiQ29udHJvbCBvZiBwaHlzaWNhbCByZXNvdXJjZXMiIH0sCi0g
IHsgaDogNSwgdDogIkJhbmtzIGFuZCBtb25ldGFyeSBwb3dlciIgfSwgImxhcmdlc3RfYmFua3Mi
LCAic2l0ZV9jZW50cmFsX2JhbmtzIiwgInNpdGVfYmFua2luZ19keW5hc3RpZXMiLCAic2l0ZV9i
YW5raW5nX2R5bmFzdGllc19jaGFydHMiLCAicG9saWN5X3JhdGVzIiwgImltYmFsYW5jZXMiLCAi
Y2ZyX3RyYWNrZXIiLCAidGFibGVhdV96c2YiLCAic2l0ZV9leHBvcnRfY3JlZGl0IiwgInRyb3V0
d29vZCIsCisgIHsgaDogNSwgdDogIkJhbmtzIGFuZCBtb25ldGFyeSBwb3dlciIgfSwgImxhcmdl
c3RfYmFua3MiLCAiZGV2ZWxvcG1lbnRfYmFua3MiLCAic2l0ZV9jZW50cmFsX2JhbmtzIiwgInNp
dGVfYmFua2luZ19keW5hc3RpZXMiLCAic2l0ZV9iYW5raW5nX2R5bmFzdGllc19jaGFydHMiLCAi
cG9saWN5X3JhdGVzIiwgImltYmFsYW5jZXMiLCAiY2ZyX3RyYWNrZXIiLCAidGFibGVhdV96c2Yi
LCAic2l0ZV9leHBvcnRfY3JlZGl0IiwgInRyb3V0d29vZCIsCiAgIHsgaDogNSwgdDogIlRyYWRl
IiB9LCAicnRlX3RyYWRlIiwgInNpdGVfdHJhZGVfcHJvZml0cyIsICJndGFfYWN0cyIsCiAgIHsg
aDogNSwgdDogIkZ1bmRpbmcgb2YgaW50ZXJuYXRpb25hbCBib2RpZXMiIH0sICJzaXRlX2Vhcm1h
cmtlZF9mdW5kaW5nIiwKICAgeyBoOiA0LCB0OiAiRWNvbm9taWMgaW5lcXVhbGl0eSB3aXRoaW4g
aXQiIH0sCmRpZmYgLS1naXQgYS9tYXAvaW5kZXguaHRtbCBiL21hcC9pbmRleC5odG1sCmluZGV4
IGExMjU0ZGUuLjllNWUxNDggMTAwNjQ0Ci0tLSBhL21hcC9pbmRleC5odG1sCisrKyBiL21hcC9p
bmRleC5odG1sCkBAIC01MTgsNyArNTE4LDcgQEAKICAgfTsKIH0pKCk7CiA8L3NjcmlwdD4KLTxz
Y3JpcHQgc3JjPSIuL2FwcC5qcz92PTY5Ij48L3NjcmlwdD4KKzxzY3JpcHQgc3JjPSIuL2FwcC5q
cz92PTcwIj48L3NjcmlwdD4KIDxzY3JpcHQgc3JjPSIuL3dpcmUuanM/dj02NyI+PC9zY3JpcHQ+
CiA8IS0tIFRoZSBkcmFnIGJhciBvbiB0aGUgbGF5ZXJzIGJveCdzIHJpZ2h0IGVkZ2UgKG1hZGUg
YnkgY29sdW1uRWRnZSgpIGluCiAgICAgIGFwcC5qcykgcmFuIHRoZSBmdWxsIGhlaWdodCBvZiB0
aGUgY29sdW1uLCBzbyBpdCBzdGF5ZWQgc3RhbmRpbmcgYmVzaWRlCmRpZmYgLS1naXQgYS9tYXAv
dGVzdC5tanMgYi9tYXAvdGVzdC5tanMKaW5kZXggYTYyMWQ1Ni4uNTQ5M2MxMyAxMDA2NDQKLS0t
IGEvbWFwL3Rlc3QubWpzCisrKyBiL21hcC90ZXN0Lm1qcwpAQCAtMzM4OCw4ICszMzg4LDggQEAg
Y29uc29sZS5sb2coIlxucm91bmQgb2YgMjMgU2VwdGVtYmVyICg1KTogdGhlIEF0bGFzIHBhbmVs
IHBhcmVkIGRvd247IG5vIGdyYWluOwogICAgICAgICAvZWxcLnN0eWxlXC5tYXhIZWlnaHQgPSBo
IFwrICJweCI7Ly50ZXN0KHNyYykgJiYgIS9lbFwuc3R5bGVcLmZsZXggPSAiMCAwIGF1dG8iOy8u
dGVzdChzcmMpICYmIC9cLmxlZnQtY29sIFwucGFuZWxce2ZsZXg6MCAxIGF1dG9cfS8udGVzdChm
cy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUsICJpbmRleC5odG1sIiksICJ1dGY4IikpICYm
CiAgICAgICAgIC9cLmxlZnQtY29sIFwucGFuZWwgPiBcLnB1bGwtZ3JpcFx7cG9zaXRpb246c3Rp
Y2t5O2JvdHRvbTowLy50ZXN0KGZzLnJlYWRGaWxlU3luYyhwYXRoLmpvaW4oSEVSRSwgImluZGV4
Lmh0bWwiKSwgInV0ZjgiKSkpOwogICBjaGVjaygidGhlIGxhcmdlc3QgYmFua3Mgcm93IHJlYWRz
IGl0cyB3ZWVrbHkgY29weSwgZmlsZWQgdW5kZXIgQmFua3MgYW5kIG1vbmV0YXJ5IHBvd2VyIChy
b3VuZCA2OSkiLAotICAgICAgICAvaWQ6ICJsYXJnZXN0X2JhbmtzIiwgbmFtZTogIlRoZSAyNTAg
bGFyZ2VzdCBiYW5rcyBieSB0b3RhbCBhc3NldHMgXChjb21waWxlZCBmcm9tIFdpa2lkYXRhXCki
W15cbl0qcm91dGU6ICJnZW9qc29ubGl2ZSIvLnRlc3Qoc3JjKSAmJgotICAgICAgICAvY3VscHJp
dHMtdGlsZXMtbW9yZVwvYmFua3NcL2xhcmdlc3RcLmdlb2pzb24vLnRlc3Qoc3JjKSAmJiAvIkJh
bmtzIGFuZCBtb25ldGFyeSBwb3dlciIgXH0sICJsYXJnZXN0X2JhbmtzIi8udGVzdChzcmMpICYm
CisgICAgICAgIC9pZDogImxhcmdlc3RfYmFua3MiLCBuYW1lOiAiVGhlIDI1MCBsYXJnZXN0IGNv
cnBvcmF0ZSBiYW5rcyBieSB0b3RhbCBhc3NldHMgXChjb21waWxlZCBmcm9tIFdpa2lkYXRhXCki
W15cbl0qcm91dGU6ICJnZW9qc29ubGl2ZSIvLnRlc3Qoc3JjKSAmJgorICAgICAgICAvY3VscHJp
dHMtdGlsZXMtbW9yZVwvYmFua3NcL2xhcmdlc3RcLmdlb2pzb24vLnRlc3Qoc3JjKSAmJiAvIkJh
bmtzIGFuZCBtb25ldGFyeSBwb3dlciIgXH0sICJsYXJnZXN0X2JhbmtzIiwgImRldmVsb3BtZW50
X2JhbmtzIi8udGVzdChzcmMpICYmIC9jdWxwcml0cy10aWxlcy1tb3JlXC9iYW5rc1wvZGV2ZWxv
cG1lbnRcLmdlb2pzb24vLnRlc3Qoc3JjKSAmJgogICAgICAgICAvbGFyZ2VzdF9iYW5rczogIkNv
bXBpbGVkIHdlZWtseSBmcm9tIFdpa2lkYXRhLy50ZXN0KHNyYykpOwogICBjaGVjaygidGhlIHdh
dGVyc2hlZHMgYXJlIHNoYWRlZCBpbiBzdGVwcyBvZiB0ZW4sIHdpdGggYSBrZXkgKHJvdW5kIDY3
KSIsCiAgICAgICAgIC9sb2dTdGVwczogXFsxZTUsIDFlNiwgMWU3LCAxZTgsIDFlOSwgMWUxMFxd
Ly50ZXN0KHNyYykgJiYgL2NvbnN0IGJyZWFrcyA9IFwoY2ZnXC5sb2dTdGVwcyBcfFx8Ly50ZXN0
KHNyYykgJiYgL25vbmUgdG8gXCRce2xhYlwoYnJlYWtzXFswXF1cKVx9Ly50ZXN0KHNyYykpOwo=
""")
def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True)
if not os.path.exists("map/app.js"):
    sys.exit("Run this from the culprits folder.")
with tempfile.NamedTemporaryFile("wb", suffix=".diff", delete=False) as f:
    f.write(DIFF); path = f.name
if git("apply", "--check", "-R", path).returncode == 0:
    print("Already applied. Nothing changed.")
else:
    r = git("apply", "--3way", path)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        git("checkout", "--", "map/app.js", "map/test.mjs", "map/index.html", "map/wire.js", "map/wire.test.mjs")
        sys.exit("Did not apply; nothing changed.")
    print("Code changes applied.")
os.unlink(path)
if os.path.exists("HANDOFF.md"):
    h = open("HANDOFF.md", encoding="utf-8").read()
    if "## Round 70 (26 September)" not in h:
        i = h.index("---") + 3
        open("HANDOFF.md", "w", encoding="utf-8").write(h[:i] + "\n" + NOTE + h[i:])
        print("HANDOFF.md note added.")
