#!/usr/bin/env python3
"""
patch_0923_buildings.py - 3D buildings stand up again. MapLibre had refused the
  buildings layer over one malformed setting, so it was never added.

Needs patch_0923_seabed.py (75e1c6f) first; it is on main.
Run from the culprits folder:  python3 patch_0923_buildings.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IDQ0NzYxYTkuLjNhNzQwNjAgMTAwNjQ0Ci0tLSBhL0hB
TkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtNSw3ICs1LDE1IEBAIHRvdWNoZXMuCiAKIC0tLQogCi0jIyBUaGUgU2F0ZWxs
aXRlIHNlYSBkcmF3biBmcm9tIGRlcHRoIHRpbGVzICgyMyBTZXB0ZW1iZXIsIGxhdGVzdCkKKyMjIDNEIGJ1aWxkaW5nczogdGhl
IGxheWVyIHdhcyBuZXZlciBhZGRlZCAoMjMgU2VwdGVtYmVyLCBsYXRlc3QpCisKK0ZvdW5kIHJ1bm5pbmcgdGhlIHJlYWwgcGFn
ZSBpbiBoZWFkbGVzcyBDaHJvbWl1bTogTWFwTGlicmUgcmVmdXNlZAorYGJ1aWxkaW5ncy0zZGAgKCJ6b29tIGV4cHJlc3Npb24g
bWF5IG9ubHkgYmUgdXNlZCBhcyBpbnB1dCB0byBhIHRvcC1sZXZlbAorc3RlcCBvciBpbnRlcnBvbGF0ZSIpIGJlY2F1c2UgYGZp
bGwtZXh0cnVzaW9uLWJhc2VgIHB1dCBbInpvb20iXSBpbnNpZGUgYQorImNhc2UiLiBUaGUgd2hvbGUgbGF5ZXIgZmFpbGVkLCBz
byBubyBidWlsZGluZyBldmVyIHN0b29kIHVwIHdpdGggM0QgdGVycmFpbgorb24uIFRoZSBiYXNlIGlzIG5vdyBhbiBpbnRlcnBv
bGF0ZSwgbGlrZSB0aGUgaGVpZ2h0LgorCisjIyBUaGUgU2F0ZWxsaXRlIHNlYSBkcmF3biBmcm9tIGRlcHRoIHRpbGVzICgyMyBT
ZXB0ZW1iZXIpCiAKIFdoeSBub25lIG9mIHRoZSBTYXRlbGxpdGUgcm91bmRzIGNoYW5nZWQgdGhlIHNlYSBvbiB0aGUgbGl2ZSBt
YXA6IE1hcHRlcmhvcm4KIChvdXRsaW5lLWRlbSkgaXMgYnVpbHQgZnJvbSBDb3Blcm5pY3VzIEdMTy0zMCwgbGFuZCBvbmx5LCBz
byB0aGUgc2VhIGlzIDAgbQpkaWZmIC0tZ2l0IGEvbWFwL2FwcC5qcyBiL21hcC9hcHAuanMKaW5kZXggZTMxMzExNS4uZTE1NDc1
MyAxMDA2NDQKLS0tIGEvbWFwL2FwcC5qcworKysgYi9tYXAvYXBwLmpzCkBAIC02NTk5LDggKzY1OTksMTEgQEAgZnVuY3Rpb24g
c2V0QnVpbGRpbmdzM0Qob24pIHsKICAgICAgICAgLy8gVGhleSByaXNlIGFzIHlvdSBjb21lIGluLCByYXRoZXIgdGhhbiBhcHBl
YXJpbmcgZnVsbCBoZWlnaHQgYXQgMTUuCiAgICAgICAgICJmaWxsLWV4dHJ1c2lvbi1oZWlnaHQiOiBbImludGVycG9sYXRlIiwg
WyJsaW5lYXIiXSwgWyJ6b29tIl0sCiAgICAgICAgICAgQlVJTERJTkdTX1pPT00sIDAsIEJVSUxESU5HU19aT09NICsgMSwgWyJn
ZXQiLCAicmVuZGVyX2hlaWdodCJdXSwKLSAgICAgICAgImZpbGwtZXh0cnVzaW9uLWJhc2UiOiBbImNhc2UiLCBbIj49IiwgWyJ6
b29tIl0sIEJVSUxESU5HU19aT09NICsgMV0sCi0gICAgICAgICAgWyJjb2FsZXNjZSIsIFsiZ2V0IiwgInJlbmRlcl9taW5faGVp
Z2h0Il0sIDBdLCAwXSwKKyAgICAgICAgLy8gQW4gaW50ZXJwb2xhdGUsIGxpa2UgdGhlIGhlaWdodDogTWFwTGlicmUgcmVmdXNl
cyBbInpvb20iXSBpbnNpZGUgYQorICAgICAgICAvLyAiY2FzZSIsIGFuZCB1bnRpbCAyMyBTZXB0ZW1iZXIgdGhhdCByZWZ1c2Fs
IGtlcHQgdGhlIHdob2xlIGxheWVyCisgICAgICAgIC8vIGZyb20gYmVpbmcgYWRkZWQsIHNvIG5vIGJ1aWxkaW5nIGV2ZXIgc3Rv
b2QgdXAuCisgICAgICAgICJmaWxsLWV4dHJ1c2lvbi1iYXNlIjogWyJpbnRlcnBvbGF0ZSIsIFsibGluZWFyIl0sIFsiem9vbSJd
LAorICAgICAgICAgIEJVSUxESU5HU19aT09NLCAwLCBCVUlMRElOR1NfWk9PTSArIDEsIFsiY29hbGVzY2UiLCBbImdldCIsICJy
ZW5kZXJfbWluX2hlaWdodCJdLCAwXV0sCiAgICAgICAgICJmaWxsLWV4dHJ1c2lvbi1vcGFjaXR5IjogMC44NSwKICAgICAgIH0s
CiAgICAgfSk7CmRpZmYgLS1naXQgYS9tYXAvdGVzdC5tanMgYi9tYXAvdGVzdC5tanMKaW5kZXggMGQwOTc1Mi4uOGZjYmVjNSAx
MDA2NDQKLS0tIGEvbWFwL3Rlc3QubWpzCisrKyBiL21hcC90ZXN0Lm1qcwpAQCAtMzI3Nyw1ICszMjc3LDE4IEBAIGNvbnNvbGUu
bG9nKCJcbnJvdW5kIG9mIDIzIFNlcHRlbWJlciAoMyk6IHRoZSB3YXN0ZXdhdGVyIHBvaW50cycgcHJvamVjdGlvbjsgV2FzCiAg
ICAgICAgIC9kZWYgbW9sbHdlaWRlX2ludmVyc2VcKHgsIHlcKTovLnRlc3QocHkpICYmIC9cKHggXC8gXCgyIFwqIFNRMiBcKiBB
XClcKSBcKlwqIDIgXCsgXCh5IFwvIFwoU1EyIFwqIEFcKVwpIFwqXCogMiA+IDEvLnRlc3QocHkpICYmIC9BID0gNjM3ODEzN1wu
MC8udGVzdChweSkpOwogICBjaGVjaygidGhlIFdhc3RlIEF0bGFzIHByb2JlIGV4aXN0cyBhbmQgb25seSByZWFkcyIsIGZzLmV4
aXN0c1N5bmMocGF0aC5qb2luKEhFUkUsICIuLiIsICJwaXBlbGluZSIsICJ3YXN0ZWF0bGFzX3Byb2JlLnB5IikpKTsKIH0KK2Nv
bnNvbGUubG9nKCJcbmJ1aWxkaW5ncyBzdGFuZCB1cCBhZ2FpbiAoMjMgU2VwdGVtYmVyKSIpOworeworICBjb25zdCBzcmMgPSBm
cy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKEhFUkUsICJhcHAuanMiKSwgInV0ZjgiKTsKKyAgY29uc3QgYSA9IHNyYy5pbmRleE9m
KCdpZDogImJ1aWxkaW5ncy0zZCInKSwgYmxvY2sgPSBzcmMuc2xpY2UoYSwgc3JjLmluZGV4T2YoIn0pOyIsIGEpKTsKKyAgLy8g
TWFwTGlicmUgb25seSB0YWtlcyBbInpvb20iXSBhcyB0aGUgaW5wdXQgb2YgYSB0b3AtbGV2ZWwgc3RlcCBvcgorICAvLyBpbnRl
cnBvbGF0ZTsgYW55d2hlcmUgZWxzZSB0aGUgd2hvbGUgbGF5ZXIgaXMgcmVmdXNlZC4KKyAgY29uc3QgcGFpbnQgPSBibG9jay5z
bGljZShibG9jay5pbmRleE9mKCJwYWludDoiKSkucmVwbGFjZSgvXC9cLy4qJC9nbSwgIiIpOworICBjb25zdCB0b3BMZXZlbCA9
IChwYWludC5tYXRjaCgvXFsiaW50ZXJwb2xhdGUiLCBcWyJsaW5lYXIiXF0sIFxbInpvb20iXF0vZykgfHwgW10pLmxlbmd0aCAr
CisgICAgICAgICAgICAgICAgICAgKHBhaW50Lm1hdGNoKC9cWyJzdGVwIiwgXFsiem9vbSJcXS9nKSB8fCBbXSkubGVuZ3RoOwor
ICBjaGVjaygiZXZlcnkgem9vbSBpbiB0aGUgM0QgYnVpbGRpbmdzJyBwYWludCBpcyB0aGUgaW5wdXQgb2YgYSB0b3AtbGV2ZWwg
aW50ZXJwb2xhdGUgb3Igc3RlcCwgc28gTWFwTGlicmUgYWRkcyB0aGUgbGF5ZXIiLAorICAgICAgICAhL1xbImNhc2UiLCBcWyI+
PSIsIFxbInpvb20iXF0vLnRlc3QoYmxvY2spICYmIHRvcExldmVsID49IDIgJiYKKyAgICAgICAgKHBhaW50Lm1hdGNoKC9cWyJ6
b29tIlxdL2cpIHx8IFtdKS5sZW5ndGggPT09IHRvcExldmVsKTsKK30KIGNvbnNvbGUubG9nKGBcbiR7cGFzc30gcGFzc2VkLCAk
e2ZhaWx9IGZhaWxlZFxuYCk7CiBwcm9jZXNzLmV4aXQoZmFpbCA/IDEgOiAwKTsK
""")

root = pathlib.Path.cwd()
app = root / "map" / "app.js"
if not app.exists():
    sys.exit("Run this from the culprits folder (cd ~/Desktop/culprits), not from inside map/.")
s = app.read_text(encoding="utf-8")
if "that refusal kept the whole layer" in s:
    sys.exit("Already applied: nothing to do.")
if "sat-relief-seabed" not in s:
    sys.exit("This needs patch_0923_seabed.py first. Run: git pull   then try again.")
tmp = root / ".patch_0923_buildings.diff"
tmp.write_bytes(DIFF)
try:
    chk = subprocess.run(["git", "apply", "--check", str(tmp)], capture_output=True, text=True)
    if chk.returncode != 0:
        sys.exit("The patch does not fit these files, so nothing was changed:\n" + chk.stderr)
    subprocess.run(["git", "apply", str(tmp)], check=True)
finally:
    tmp.unlink(missing_ok=True)
print("Applied: 3D buildings layer fixed (map/app.js, map/test.mjs, HANDOFF.md).")
