#!/usr/bin/env python3
"""
patch_0923p.py - the Satellite basemap draws Esri's imagery at every zoom again, as
                 when patch o's look was made (the Sentinel-2 wide views are kept,
                 switched off).

Run from the repo folder:  python3 patch_0923p.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IDE2NWFhNDYuLjk3MWQ2MzIgMTAwNjQ0Ci0tLSBhL0hB
TkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtNSw2ICs1LDE2IEBAIHRvdWNoZXMuCiAKIC0tLQogCisjIyBTYXRlbGxpdGUg
YmFjayBvbiBFc3JpJ3MgaW1hZ2VyeSBhdCBldmVyeSB6b29tICgyMyBTZXB0ZW1iZXIpCisKK1RoZSBvd25lcidzIGNob3NlbiBs
b29rIChwYXRjaCBvJ3MsIHdpdGggZWRpdHMpIHdhcyBtYWRlIG9uIEVzcmkncyBpbWFnZXJ5Oworc2luY2UgNTI5NWIzNiB0aGUg
U2F0ZWxsaXRlIGJhc2VtYXAgZHJldyBTZW50aW5lbC0yIGNsb3VkbGVzcyAyMDI0IG91dCB0bworem9vbSAxMi41LCB3aGljaCBp
cyBkYXJrZXIsIG1vcmUgc2F0dXJhdGVkIGFuZCBvcmFuZ2UgaW4gdGhlIGRlc2VydHMsIHNvIHRoZQorbG9vayBjYW1lIG91dCBk
aWZmZXJlbnQuIGBTQVRfQ0xPU0UuczJgIGlzIG5vdyBmYWxzZTogdGhlIFNhdGVsbGl0ZSBiYXNlbWFwCitkcmF3cyB0aGUgYGJh
c2VgIGxheWVyIChFc3JpKSBhdCBldmVyeSB6b29tLCBncmFkZWQgYnkgQkFTRV9HUkFERS5zYXRlbGxpdGU7CitgYmFzZS1zMmAg
YW5kIGBiYXNlLWNsb3NlYCBzdGF5IGluIHRoZSBzdHlsZSwgaGlkZGVuLiBFc3JpJ3MgY2hhbmdlIG9mIHNlYXNvbgorYXJvdW5k
IHpvb20gMTIgaXMgYmFjay4gU2V0IHMyIHRvIHRydWUgdG8gcmVzdG9yZSB0aGUgU2VudGluZWwtMiB3aWRlIHZpZXdzLgorCiAj
IyBUaGUgU2F0ZWxsaXRlIGJhc2VtYXAgYXMgcGF0Y2ggbywgd2l0aCB0aGUgb3duZXIncyBlZGl0cyAoMjMgU2VwdGVtYmVyKQog
CiBSZXBsYWNlcyBwYXRjaCBuJ3MgbG9vayAoYWY2MDEyMyksIHdoaWNoIHRoZSBvd25lciBmb3VuZCBlbnRpcmVseSBkaWZmZXJl
bnQKZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDVkYmQwOGUuLjI4ZWJjMGQgMTAwNjQ0Ci0tLSBh
L21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtODY3LDYgKzg2NywxMiBAQCBjb25zdCBTQVRfQ0xPU0UgPSB7CiAgIC8v
IG1vc2FpYyAob25lIHllYXIsIGNsb3VkLWZyZWUsIHRoZSBzYW1lIGV2ZXJ5d2hlcmUpOyBFc3JpJ3Mgc2hhcnBlciBwaG90bwog
ICAvLyBmYWRlcyBpbiBiZXR3ZWVuIDEyLjUgYW5kIDEzLjI1LgogICBoYW5kb3ZlcjogWzEyLjUsIDEzLjI1XSwKKyAgLy8gT2Zm
IHNpbmNlIDIzIFNlcHRlbWJlciwgYXQgdGhlIG93bmVyJ3MgY2hvaWNlOiB0aGUgbG9vayB0aGV5IHdhbnQgKHBhdGNoCisgIC8v
IG8ncykgd2FzIG1hZGUgb24gRXNyaSdzIGltYWdlcnksIGFuZCBTZW50aW5lbC0yIGNsb3VkbGVzcyBpcyBkYXJrZXIsIG1vcmUK
KyAgLy8gc2F0dXJhdGVkLCB3aXRoIG9yYW5nZSBkZXNlcnRzLiBFc3JpIGF0IGV2ZXJ5IHpvb20gYWdhaW47IGl0cyBjaGFuZ2Ug
b2YKKyAgLy8gc2Vhc29uIGFyb3VuZCB6b29tIDEyIGNvbWVzIGJhY2sgd2l0aCBpdC4gdHJ1ZSByZXN0b3JlcyB0aGUgU2VudGlu
ZWwtMgorICAvLyB3aWRlIHZpZXdzIGFzIHRoZXkgd2VyZS4KKyAgczI6IGZhbHNlLAogfTsKIAogLy8gVGhlIGNvbG91ciB3YXNo
ZXMsIGFzIG9uZSBXZWJHTCBsYXllciBkcmF3biBvdmVyIHRoZSBpbWFnZXJ5LgpAQCAtMTk2OSw5ICsxOTc1LDkgQEAgZnVuY3Rp
b24gc2V0QmFzZW1hcChraW5kKSB7CiAgIH07CiAgIGNvbnN0IGltYWdlcnkgPSBraW5kICE9PSAib3V0bGluZXMiOwogICBpZiAo
IWltYWdlcnkpIGFkZE91dGxpbmVMYXllcnMoKTsKLSAgc2hvdygiYmFzZSIsIGtpbmQgPT09ICJhdGxhcyIpOwotICBzaG93KCJi
YXNlLXMyIiwga2luZCA9PT0gInNhdGVsbGl0ZSIpOwotICBzaG93KCJiYXNlLWNsb3NlIiwga2luZCA9PT0gInNhdGVsbGl0ZSIp
OworICBzaG93KCJiYXNlIiwga2luZCA9PT0gImF0bGFzIiB8fCAoa2luZCA9PT0gInNhdGVsbGl0ZSIgJiYgIVNBVF9DTE9TRS5z
MikpOworICBzaG93KCJiYXNlLXMyIiwga2luZCA9PT0gInNhdGVsbGl0ZSIgJiYgU0FUX0NMT1NFLnMyKTsKKyAgc2hvdygiYmFz
ZS1jbG9zZSIsIGtpbmQgPT09ICJzYXRlbGxpdGUiICYmIFNBVF9DTE9TRS5zMik7CiAgIC8vIEVzcmkncyByZWxpZWYgdGlsZXMg
b24gdGhlIGF0bGFzIG9ubHk7IHRoZSBTYXRlbGxpdGUgYmFzZW1hcCBoYXMgaXRzIG93bi4KICAgc2hvdygiaGlsbHNoYWRlIiwg
a2luZCA9PT0gImF0bGFzIiAmJiAhVEVSUkFJTl9PTik7CiAgIHNob3coImF0bGFzLXBsYXRlIiwga2luZCA9PT0gImF0bGFzIik7
CkBAIC0xOTg1LDcgKzE5OTEsNyBAQCBmdW5jdGlvbiBzZXRCYXNlbWFwKGtpbmQpIHsKICAgT1VUTElORV9JRFMuZm9yRWFjaCgo
aWQpID0+IHNob3coaWQsICFpbWFnZXJ5KSk7CiAgIHNob3coIm91dGxpbmUtbGluZSIsICFpbWFnZXJ5KTsKICAgaWYgKGltYWdl
cnkpIHsKLSAgICBmb3IgKGNvbnN0IGlkIG9mIGtpbmQgPT09ICJzYXRlbGxpdGUiID8gWyJiYXNlLXMyIiwgImJhc2UtY2xvc2Ui
XSA6IFsiYmFzZSJdKSB7CisgICAgZm9yIChjb25zdCBpZCBvZiBraW5kID09PSAic2F0ZWxsaXRlIiAmJiBTQVRfQ0xPU0UuczIg
PyBbImJhc2UtczIiLCAiYmFzZS1jbG9zZSJdIDogWyJiYXNlIl0pIHsKICAgICAgIGlmICghbWFwLmdldExheWVyKGlkKSkgY29u
dGludWU7CiAgICAgICBmb3IgKGNvbnN0IFtrLCB2XSBvZiBPYmplY3QuZW50cmllcyhCQVNFX0dSQURFW2tpbmRdKSkgbWFwLnNl
dFBhaW50UHJvcGVydHkoaWQsIGssIHYpOwogICAgIH0KZGlmZiAtLWdpdCBhL21hcC90ZXN0Lm1qcyBiL21hcC90ZXN0Lm1qcwpp
bmRleCBhZGY0N2E0Li43N2QzZmYwIDEwMDY0NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rlc3QubWpzCkBAIC0xMzQ1
LDE0ICsxMzQ1LDE0IEBAIGNvbnNvbGUubG9nKCJcbnRoZSB3aXJlcyBvbiB0aGUgbWFwIik7CiAgIGNvbnN0IGF0ID0gKHopID0+
IGYuYXRsYXNXYXNoUGFzc2VzKHopOwogICBjaGVjaygiU2F0ZWxsaXRlOiBubyB3YXNoIGF0IGFueSB6b29tIiwKICAgICAgICAg
WzQsIDEwLCAxMiwgMTQsIDE4XS5ldmVyeSgoeikgPT4gYXQoeikubGVuZ3RoID09PSAwKSAmJiAhKCJtdWx0aXBseSIgaW4gZi5T
QVRfQ0xPU0UpKTsKLSAgY2hlY2soIuKAplNlbnRpbmVsLTIgY2xvdWRsZXNzIDIwMjQgb3V0IHRvIDEzLjI1LCBFc3JpJ3MgcGhv
dG8gZmFkaW5nIGluIGZyb20gMTIuNSwgdGhlIGF0bGFzIGtlZXBzIGl0cyBvd24gaW1hZ2VyeSBsYXllciIsCisgIGNoZWNrKCLi
gKZ0aGUgU2VudGluZWwtMiB3aWRlIHZpZXdzIGFyZSBrZXB0IGJ1dCBzd2l0Y2hlZCBvZmYgKFNBVF9DTE9TRS5zMiBmYWxzZSk6
IEVzcmkncyBpbWFnZXJ5IGF0IGV2ZXJ5IHpvb20sIGFzIHdoZW4gcGF0Y2ggbyB3YXMgbWFkZSIsCiAgICAgICAgIC90aWxlczog
XFsiaHR0cHM6XC9cL3RpbGVzXC5tYXBzXC5lb3hcLmF0XC93bXRzXC8xXC4wXC4wXC9zMmNsb3VkbGVzcy0yMDI0XzM4NTdcL2Rl
ZmF1bHRcL2dcL1x7elx9XC9ce3lcfVwvXHt4XH1cLmpwZyJcXS8udGVzdChzcmMpICYmCiAgICAgICAgIC9Db250YWlucyBtb2Rp
ZmllZCBDb3Blcm5pY3VzIFNlbnRpbmVsIGRhdGEgMjAyNC8udGVzdChzcmMpICYmCiAgICAgICAgIC9pZDogImJhc2UtczIiLCB0
eXBlOiAicmFzdGVyIiwgc291cmNlOiAiczIiLCBtYXh6b29tOiBTQVRfQ0xPU0VcLmhhbmRvdmVyXFsxXF0vLnRlc3Qoc3JjKSAm
JgogICAgICAgICAvaWQ6ICJiYXNlLWNsb3NlIiwgdHlwZTogInJhc3RlciIsIHNvdXJjZTogImJhc2UiLCBtaW56b29tOiBTQVRf
Q0xPU0VcLmhhbmRvdmVyXFswXF0vLnRlc3Qoc3JjKSAmJgogICAgICAgICBKU09OLnN0cmluZ2lmeShmLlNBVF9DTE9TRS5oYW5k
b3ZlcikgPT09ICJbMTIuNSwxMy4yNV0iICYmCi0gICAgICAgIC9zaG93XCgiYmFzZSIsIGtpbmQgPT09ICJhdGxhcyJcKTsvLnRl
c3Qoc3JjKSAmJiAvc2hvd1woImJhc2UtczIiLCBraW5kID09PSAic2F0ZWxsaXRlIlwpOy8udGVzdChzcmMpICYmCi0gICAgICAg
IC9zaG93XCgiYmFzZS1jbG9zZSIsIGtpbmQgPT09ICJzYXRlbGxpdGUiXCk7Ly50ZXN0KHNyYykgJiYKKyAgICAgICAgL3Nob3dc
KCJiYXNlIiwga2luZCA9PT0gImF0bGFzIiBcfFx8IFwoa2luZCA9PT0gInNhdGVsbGl0ZSIgJiYgIVNBVF9DTE9TRVwuczJcKVwp
Oy8udGVzdChzcmMpICYmIC9zaG93XCgiYmFzZS1zMiIsIGtpbmQgPT09ICJzYXRlbGxpdGUiICYmIFNBVF9DTE9TRVwuczJcKTsv
LnRlc3Qoc3JjKSAmJgorICAgICAgICAvc2hvd1woImJhc2UtY2xvc2UiLCBraW5kID09PSAic2F0ZWxsaXRlIiAmJiBTQVRfQ0xP
U0VcLnMyXCk7Ly50ZXN0KHNyYykgJiYgZi5TQVRfQ0xPU0UuczIgPT09IGZhbHNlICYmCiAgICAgICAgIC9cWyJiYXNlIiwgInMy
IiwgImhpbGxzaGFkZSIsICJsYWJlbHMiLCAiYXRsYXMtcGxhdGUiXF1cLmluY2x1ZGVzXChzcmNcKS8udGVzdChzcmMpKTsKICAg
Zi5zZXRCKCJhdGxhcyIpOwogICBjaGVjaygi4oCmYW5kIHRoZSBwYWludGVkIGF0bGFzJ3Mgd2FzaGVzIGFyZSB1bmNoYW5nZWQg
YnkgaXQiLCBhdCgxMikubGVuZ3RoID09PSA0KTsK
""")

def main():
    app = pathlib.Path("map/app.js")
    if not app.exists():
        sys.exit("Run this from the culprits folder (the one with map/app.js).")
    s = app.read_text(encoding="utf-8")
    if "  s2: false," in s:
        sys.exit("Already applied. Nothing changed.")
    if "const RELIEF_SOURCE = {" not in s:
        sys.exit("patch_0922s.py has to be applied and committed first.")
    tmp = pathlib.Path(".patch_0923p.diff")
    tmp.write_bytes(DIFF)
    try:
        chk = subprocess.run(["git", "apply", "--check", str(tmp)], capture_output=True, text=True)
        if chk.returncode != 0:
            print(chk.stderr)
            sys.exit("Does not apply cleanly. Nothing changed.")
        subprocess.run(["git", "apply", str(tmp)], check=True)
    finally:
        tmp.unlink(missing_ok=True)
    print("Applied. Changed: map/app.js, map/test.mjs, HANDOFF.md")
    print("Now run both suites:")
    print("    cd map && node test.mjs && node wire.test.mjs")

main()
