#!/usr/bin/env python3
"""
patch_0921a.py - two of Nusantara's unnamed layers get their names.

  - concessionfca_spv: Forest Clearance Authority (FCA) concessions, Papua New Guinea
  - millopbufferol50km_spv: Near palm oil mills, 50 km
Both from Nusantara Atlas's own menu. The other three stay as the server names
them, since nothing confirms what they are.

Needs patch_0920z.py applied and committed first.
Run from the repo folder:  python3 patch_0921a.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IGM1OGJhNDguLjMxMjEzYTEgMTAwNjQ0Ci0tLSBhL0hB
TkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtMjQyLDYgKzI0MiwxNiBAQCBhcyBiZWZvcmUsIHNvIG5vdGhpbmcgYnJlYWtz
IHdoaWxlIHRoZSB0aWxpbmcgY2F0Y2hlcyB1cC4KIAogLS0tCiAKKyMjIE51c2FudGFyYTogdHdvIG9mIHRoZSBmaXZlIHVubmFt
ZWQgbGF5ZXJzIG5hbWVkCisKK0Zyb20gTnVzYW50YXJhIEF0bGFzJ3Mgb3duIG1lbnUsIHJlYWQgb2ZmIHRoZWlyIHNpdGUgYnkg
dGhlIG93bmVyICgyMSBTZXB0ZW1iZXIpOgorYGNvbmNlc3Npb25mY2Ffc3B2YCBpcyAiRm9yZXN0IENsZWFyYW5jZSBBdXRob3Jp
dHkgKEZDQSkiIGFuZCBjb3ZlcnMgUGFwdWEgTmV3CitHdWluZWEgKGEgcnVsZSBpbiBgTlVTQU5UQVJBX1dIRVJFYCBzYXlzIHNv
KTsgYG1pbGxvcGJ1ZmZlcm9sNTBrbV9zcHZgIGlzIHRoZWlyCisiTmVhciBwYWxtIG9pbCBtaWxscyIgYXQgNTAga20uIFN0aWxs
IHVubmFtZWQsIGJlY2F1c2Ugbm90aGluZyBjb25maXJtcyB0aGVtOgorYGNvbmNlc3Npb25jbWFfc3B2YCwgYG1pbGxvcGJ1ZmZl
cm9sX3NwdmAgKHRoZWlyIG1lbnUgaGFzIDEwLCAyNSBhbmQgNTAga20gYW5kCit0aGlzIGlkIGNhcnJpZXMgbm8gZGlzdGFuY2Up
IGFuZCBgbWlsbG9wYnVmZmVycG9seWxvcmVhbF9zcHZgICh0aGUgb3duZXIgd29uZGVycword2hldGhlciBpdCBpcyBMJ09yZWFs
J3Mgc3VwcGxpZXIgbWlsbHM7IHVuY29uZmlybWVkKS4KKwogIyMgVGhyZWUgc2l0ZSBtYXBzIHNwbGl0IGludG8gYSByb3cgcGVy
IHR5cGUKIAogVGhlIHBsYW50cywgbWljcm9vcmdhbmlzbXMgYW5kIGluc2VudGllbnQgbWFwcyBoYXZlIG5vIGNvbnRyb2wgdGhh
dCBzb3J0cyB0aGVpcgpkaWZmIC0tZ2l0IGEvbWFwL2FwcC5qcyBiL21hcC9hcHAuanMKaW5kZXggNTQyODUzNS4uMGVhYTY2YiAx
MDA2NDQKLS0tIGEvbWFwL2FwcC5qcworKysgYi9tYXAvYXBwLmpzCkBAIC0zODg5LDYgKzM4ODksOSBAQCBjb25zdCBOVVNBTlRB
UkFfTkFNRVMgPSB7CiAgICJidXJuZWRfYXJlYV9yZ2JfY3JvcCI6ICJCdXJuZWQgYXJlYSAocGljdHVyZSwgY3JvcHBlZCkiLAog
ICAiYnVybmVkYXJlYV9yZ2IiOiAiQnVybmVkIGFyZWEgKHBpY3R1cmUpIiwKICAgImJ1cm5lZGFyZWFucnQiOiAiQnVybmVkIGFy
ZWEsIG5lYXIgcmVhbCB0aW1lLCBzaG93aW5nIG92ZXJsYXBzIiwKKyAgLy8gTmFtZWQgZnJvbSBOdXNhbnRhcmEgQXRsYXMncyBv
d24gbWVudSwgYXMgdGhlIG93bmVyIHJlYWQgaXQgb2ZmIHRoZWlyIHNpdGUgb24KKyAgLy8gMjEgU2VwdGVtYmVyIDIwMjY6ICJG
b3Jlc3QgQ2xlYXJhbmNlIEF1dGhvcml0eSAoRkNBKSAtIFBhcHVhIE5ldyBHdWluZWEiLgorICAiY29uY2Vzc2lvbmZjYV9zcHYi
OiAiRm9yZXN0IENsZWFyYW5jZSBBdXRob3JpdHkgKEZDQSkgY29uY2Vzc2lvbnMiLAogICAiY29uY2Vzc2lvbmhndV9zcHYiOiAi
UGxhbnRhdGlvbiBsYW5kLXVzZSByaWdodHMgKEhHVSkiLAogICAiY29uY2Vzc2lvbmlvcF9maW5hbmNlX2NyZWRpdCI6ICJPaWwg
cGFsbSBjb25jZXNzaW9ucywgYnkgd2hvIGxlbmRzIHRvIHRoZW0iLAogICAiY29uY2Vzc2lvbmlvcF9maW5hbmNlX2ludmVzdCI6
ICJPaWwgcGFsbSBjb25jZXNzaW9ucywgYnkgd2hvIGludmVzdHMgaW4gdGhlbSIsCkBAIC0zOTE0LDYgKzM5MTcsOSBAQCBjb25z
dCBOVVNBTlRBUkFfTkFNRVMgPSB7CiAgICJtaWxsb3BidWZmZXIxaHJfc3B2IjogIlBhbG0gb2lsIG1pbGwgc291cmNpbmcgYXJl
YXMsIG9uZSBob3VyJ3MgZHJpdmUiLAogICAibWlsbG9wYnVmZmVyMmhyX3NwdiI6ICJQYWxtIG9pbCBtaWxsIHNvdXJjaW5nIGFy
ZWFzLCB0d28gaG91cnMnIGRyaXZlIiwKICAgIm1pbGxvcGJ1ZmZlcl9zcHYiOiAiUGFsbSBvaWwgbWlsbCBzb3VyY2luZyBhcmVh
cyIsCisgIC8vIFRoZWlyIG1lbnUgbGlzdHMgIk5lYXIgcGFsbSBvaWwgbWlsbHMiIGF0IDEwLCAyNSBhbmQgNTAga20uIFRoaXMg
aWQgY2FycmllcworICAvLyBpdHMgNTAga207IHdoYXQgaXRzICJvbCIgc3RhbmRzIGZvciBpcyBub3Qga25vd24gYW5kIGlzIG5v
dCBndWVzc2VkIGF0LgorICAibWlsbG9wYnVmZmVyb2w1MGttX3NwdiI6ICJOZWFyIHBhbG0gb2lsIG1pbGxzLCA1MCBrbSIsCiAg
ICJtaWxsb3ByZWZpbmVyaWVzX3NwIjogIlBhbG0gb2lsIHJlZmluZXJpZXMiLAogICAicGFwdWFfY29uY2Vzc2lvbmlvcF9lZGl0
ZWQiOiAiT2lsIHBhbG0gY29uY2Vzc2lvbnMsIFBhcHVhICh0aGVpciBlZGl0ZWQgdmVyc2lvbikiLAogICAicGFwdWFfZXhwYW5z
aW9uXzIwMjUiOiAiUGxhbnRhdGlvbiBleHBhbnNpb24gMjAyNSwgUGFwdWEiLApAQCAtNDAzMSw2ICs0MDM3LDcgQEAgY29uc3Qg
TlVTQU5UQVJBX1dIRVJFID0gWwogICBbL0lETk1ZU0Jvcm5lby9pLCAiQm9ybmVvIl0sCiAgIFsvUkVHSUROTVlTL2ksICJJbmRv
bmVzaWEgYW5kIE1hbGF5c2lhIl0sCiAgIFsvXkJBTElffGJhZHVuZ3x0YWJhbmFuL2ksICJCYWxpIl0sCisgIFsvXmNvbmNlc3Np
b25mY2FfL2ksICJQYXB1YSBOZXcgR3VpbmVhIl0sCiAgIFsvcGFwdWEvaSwgIlBhcHVhIl0sCiAgIFsvbWVyYXVrZS9pLCAiTWVy
YXVrZSJdLAogICBbL3Jhd2FzaW5na2lsL2ksICJSYXdhIFNpbmdraWwiXSwKZGlmZiAtLWdpdCBhL21hcC90ZXN0Lm1qcyBiL21h
cC90ZXN0Lm1qcwppbmRleCBhNGMzOWY3Li4xYjAzNGJkIDEwMDY0NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rlc3Qu
bWpzCkBAIC0yNTYzLDYgKzI1NjMsMTAgQEAgY29uc29sZS5sb2coIlxuTnVzYW50YXJhJ3MgbGF5ZXJzIHNheSB3aGF0IHRoZXkg
c2hvdyIpOwogICAgICAgICB0YWJsZS5HbG9iYWxfUGxhbnRhdGlvbklPUF8yMDI1ID09PSAiSW5kdXN0cmlhbCBvaWwgcGFsbSBw
bGFudGF0aW9ucyAyMDI1IiAmJgogICAgICAgICB0YWJsZS5jb25jZXNzaW9uaXRwX3NwdiA9PT0gIkluZHVzdHJpYWwgdGltYmVy
IHBsYW50YXRpb24gY29uY2Vzc2lvbnMiICYmCiAgICAgICAgIHRhYmxlLnYzcDNfc3BhdGlhbHBsYW5tb3JhdG9yaXVtX3NwdiA9
PT0gIk1vcmF0b3JpdW0gYXJlYXMgKFBJUFBJQikgKHYzcDMgY29weSkiKTsKKyAgY2hlY2soInR3byBtb3JlIGFyZSBuYW1lZCBm
cm9tIE51c2FudGFyYSdzIG93biBtZW51LCBhbmQgdGhlIHRocmVlIG5vYm9keSBjYW4gdm91Y2ggZm9yIGFyZSBzdGlsbCBsZWZ0
IGFsb25lIiwKKyAgICAgICAgdGFibGUuY29uY2Vzc2lvbmZjYV9zcHYgPT09ICJGb3Jlc3QgQ2xlYXJhbmNlIEF1dGhvcml0eSAo
RkNBKSBjb25jZXNzaW9ucyIgJiYgdGFibGUubWlsbG9wYnVmZmVyb2w1MGttX3NwdiA9PT0gIk5lYXIgcGFsbSBvaWwgbWlsbHMs
IDUwIGttIiAmJgorICAgICAgICAhKCJjb25jZXNzaW9uY21hX3NwdiIgaW4gdGFibGUpICYmICEoIm1pbGxvcGJ1ZmZlcm9sX3Nw
diIgaW4gdGFibGUpICYmICEoIm1pbGxvcGJ1ZmZlcnBvbHlsb3JlYWxfc3B2IiBpbiB0YWJsZSkgJiYKKyAgICAgICAgL1xbXC9c
XmNvbmNlc3Npb25mY2FfXC9pLCAiUGFwdWEgTmV3IEd1aW5lYSJcXS8udGVzdChzcmMpKTsKICAgY2hlY2soImEgbGF5ZXIgbm9i
b2R5IGhhcyBuYW1lZCBrZWVwcyB0aGUgc2VydmVyJ3Mgb3duIHRpdGxlLCByYXRoZXIgdGhhbiBhIGd1ZXNzIiwKICAgICAgICAg
L2NvbnN0IHNhaWQgPSBOVVNBTlRBUkFfTkFNRVNcW2lkXF0gXHxcfCBcKHR0ICYmIHR0XC50ZXh0Q29udGVudFwpIFx8XHwgaWQ7
Ly50ZXN0KHNyYykpOwogfQo=
""").decode("utf-8")


def run(cmd, text=None):
    return subprocess.run(cmd, input=text, text=True, capture_output=True)


def main():
    if not pathlib.Path("map/app.js").exists():
        sys.exit("Run this from the culprits folder (cd ~/Desktop/culprits).")
    app = pathlib.Path("map/app.js").read_text(encoding="utf-8")
    if "function siteTypeRowsFor" not in app:
        sys.exit("patch_0920z.py has to be applied and committed first.")
    if run(["git", "apply", "--check", "--reverse", "-"], DIFF).returncode == 0:
        print("Already applied - nothing to do.")
        return
    check = run(["git", "apply", "--check", "-"], DIFF)
    if check.returncode != 0:
        print(check.stderr.strip())
        sys.exit("Does not apply cleanly.")
    out = run(["git", "apply", "-"], DIFF)
    if out.returncode != 0:
        print(out.stderr.strip())
        sys.exit("git apply failed.")
    print("Applied. Changed: map/app.js, map/test.mjs, HANDOFF.md")
    print("Now run both suites:")
    print("    cd map && node test.mjs && node wire.test.mjs")


if __name__ == "__main__":
    main()
