#!/usr/bin/env python3
"""
patch_0924b.py - the popup finds a record's pieces by the layer, since the tiles carry no source field.

Run from the repo folder:  python3 patch_0924b.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDRmNzkyMmQuLjQ0MzkxYTEgMTAwNjQ0Ci0tLSBhL21h
cC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtMjA3OSw3ICsyMDc5LDcgQEAgYXN5bmMgZnVuY3Rpb24gYWRkUG10aWxlc0xh
eWVyKGNmZykgewogICAgICAgICBpZiAoY2ZnLndoZXJlKSBzcGVjLmZpbHRlciA9IGNmZy53aGVyZTsKICAgICAgICAgbWFwLmFk
ZExheWVyKHNwZWMsIGAke2NmZy5pZH0tJHtraW5kfWApOwogICAgICAgICBjZmcuX2xheWVySWRzLnB1c2gobGlkKTsKLSAgICAg
ICAgaWYgKGNmZy5ib3hlcykgYmluZEh0bWxQb3B1cChsaWQsIChwKSA9PiBwaWVjZUJveChjZmcsIHApKTsgZWxzZSBiaW5kUG9w
dXAobGlkKTsKKyAgICAgICAgaWYgKGNmZy5ib3hlcykgYmluZEh0bWxQb3B1cChsaWQsIChwKSA9PiBwaWVjZUJveChjZmcsIHAp
KTsgZWxzZSBiaW5kUG9wdXAobGlkLCBvd25lcik7CiAgICAgICB9CiAgICAgfSk7CiAgICAgYXBwbHlWaXNpYmlsaXR5KGNmZy5p
ZCk7CkBAIC0yMDk1LDggKzIwOTUsOCBAQCBhc3luYyBmdW5jdGlvbiBhZGRQbXRpbGVzTGF5ZXIoY2ZnKSB7CiAgICAgICAgIChi
Lm5vX3Bvc2l0aW9uID8gYCBcdTAwYjcgJHtOdW1iZXIoYi5ub19wb3NpdGlvbikudG9Mb2NhbGVTdHJpbmcoKX0gbW9yZSBpbiB0
aGUgY29weSBoYXZlIG5vIHBvc2l0aW9uIGFuZCBjYW5ub3QgYmUgZHJhd25gIDogIiIpKTsKICAgICB9KS5jYXRjaCgoKSA9PiB7
fSk7CiAgIH0gZWxzZSB7Ci0gICAgYmluZFBvcHVwKGAke2NmZy5pZH0tYWdnYCk7Ci0gICAgYmluZFBvcHVwKGAke2NmZy5pZH0t
cHRgKTsKKyAgICBiaW5kUG9wdXAoYCR7Y2ZnLmlkfS1hZ2dgLCBvd25lcik7CisgICAgYmluZFBvcHVwKGAke2NmZy5pZH0tcHRg
LCBvd25lcik7CiAgIH0KICAgYXBwbHlWaXNpYmlsaXR5KGNmZy5pZCk7CiAgIGJ1aWxkTGVnZW5kKCk7CkBAIC04OTAxLDcgKzg5
MDEsMTEgQEAgZnVuY3Rpb24gYnVpbGRMZWdlbmQoKSB7CiAvLyBjbGlja3MgbmV2ZXIgZG8sIGhvd2V2ZXIgZmFzdCB0aGV5IGNv
bWUuCiBsZXQgcG9wdXBDbGFpbWVkQnkgPSBudWxsOwogCi1mdW5jdGlvbiBiaW5kUG9wdXAobGF5ZXJJZCkgeworLy8gYHNvdXJj
ZWAgbmFtZXMgdGhlIHBpZWNlcyB0byByZWFkIGEgcmVjb3JkJ3MgZXZlcnkgZmllbGQgZnJvbQorLy8gKG1hcC9kYXRhL3BpZWNl
cy88c291cmNlPi8pLiBUaGUgdGlsZXMgdGhlbXNlbHZlcyBubyBsb25nZXIgY2FycnkgYSBzb3VyY2UKKy8vIGZpZWxkIC0gYnVp
bGRfdGlsZXMuc2ggbGVhdmVzIGl0IG91dCB0byBrZWVwIHRoZW0gc21hbGwgLSB3aGljaCBpcyB3aHkgdGhlCisvLyBzZWN0aW9u
IG5ldmVyIGFwcGVhcmVkOiB0aGUgcG9wdXAgbG9va2VkIGZvciBpdCBvbiB0aGUgcG9pbnQuCitmdW5jdGlvbiBiaW5kUG9wdXAo
bGF5ZXJJZCwgc291cmNlKSB7CiAgIG1hcC5vbigiY2xpY2siLCBsYXllcklkLCAoZSkgPT4gewogICAgIGNvbnN0IGNsYWltID0g
ZS5vcmlnaW5hbEV2ZW50IHx8IGU7CiAgICAgaWYgKHBvcHVwQ2xhaW1lZEJ5ID09PSBjbGFpbSkgcmV0dXJuOwpAQCAtODk4Miwx
NSArODk4NiwxNiBAQCBmdW5jdGlvbiBiaW5kUG9wdXAobGF5ZXJJZCkgewogICAgIC8vIChtYXAvZGF0YS9waWVjZXMvPHNvdXJj
ZT4vLCB3cml0dGVuIGJ5IHRoZSBwaXBlbGluZSBiZXNpZGUgdGhlIHRpbGVzKS4KICAgICAvLyBBIGxheWVyIHdpdGggbm8gcGll
Y2VzIC0gb25lIGJ1aWx0IGJlZm9yZSB0aGV5IGV4aXN0ZWQsIG9yIG9uZSB0b28gYmlnCiAgICAgLy8gZm9yIHRoZW0gLSBzaG93
cyB3aGF0IHRoZSB0aWxlcyBjYXJyeSBhbmQgbm90aGluZyBtb3JlLgotICAgIGlmIChjb3VudCA9PT0gMSAmJiBwLnNvdXJjZSAm
JiBwLmlkICE9IG51bGwgJiYgIW5vUGllY2VzLmhhcyhwLnNvdXJjZSkpIHsKLSAgICAgIHJlYWRQaWVjZShgZGF0YS9waWVjZXMv
JHtwLnNvdXJjZX1gLCBwLmlkKS50aGVuKChwaWVjZSkgPT4geworICAgIGNvbnN0IGZyb20gPSBzb3VyY2UgfHwgcC5zb3VyY2U7
CisgICAgaWYgKGNvdW50ID09PSAxICYmIGZyb20gJiYgcC5pZCAhPSBudWxsICYmICFub1BpZWNlcy5oYXMoZnJvbSkpIHsKKyAg
ICAgIHJlYWRQaWVjZShgZGF0YS9waWVjZXMvJHtmcm9tfWAsIHAuaWQpLnRoZW4oKHBpZWNlKSA9PiB7CiAgICAgICAgIGNvbnN0
IHJhdyA9IHBpZWNlICYmIHBpZWNlW1N0cmluZyhwLmlkKV07CiAgICAgICAgIGlmICghcmF3IHx8IHR5cGVvZiByYXcgIT09ICJv
YmplY3QiKSByZXR1cm47CiAgICAgICAgIGNvbnN0IHJvd3MgPSBPYmplY3QuZW50cmllcyhyYXcpLmZpbHRlcigoWywgdl0pID0+
IHYgIT09IG51bGwgJiYgdiAhPT0gIiIgJiYgIShBcnJheS5pc0FycmF5KHYpICYmICF2Lmxlbmd0aCkpCiAgICAgICAgICAgLm1h
cCgoW2ssIHZdKSA9PiBgPHRyPjx0aCBzdHlsZT0idGV4dC1hbGlnbjpsZWZ0O3BhZGRpbmctcmlnaHQ6OHB4O3ZlcnRpY2FsLWFs
aWduOnRvcCI+JHtlc2NhcGVIdG1sKGsucmVwbGFjZSgvXy9nLCAiICIpKX08L3RoPmAgKwogICAgICAgICAgICAgYDx0ZD4ke2Vz
Y2FwZUh0bWwodHlwZW9mIHYgPT09ICJvYmplY3QiID8gSlNPTi5zdHJpbmdpZnkodikgOiBTdHJpbmcodikpfTwvdGQ+PC90cj5g
KS5qb2luKCIiKTsKICAgICAgICAgaWYgKHJvd3MgJiYgcG9wdXAuaXNPcGVuKCkpIHBvcHVwLnNldEhUTUwoaHRtbCArIGA8ZGl2
IGNsYXNzPSJtZXRhIj48Yj5FdmVyeSBmaWVsZCB0aGUgc291cmNlIHB1Ymxpc2hlczwvYj48dGFibGU+JHtyb3dzfTwvdGFibGU+
PC9kaXY+YCk7Ci0gICAgICB9KS5jYXRjaCgoKSA9PiBub1BpZWNlcy5hZGQocC5zb3VyY2UpKTsKKyAgICAgIH0pLmNhdGNoKCgp
ID0+IG5vUGllY2VzLmFkZChmcm9tKSk7CiAgICAgfQogICB9KTsKICAgbWFwLm9uKCJtb3VzZWVudGVyIiwgbGF5ZXJJZCwgKCkg
PT4gKG1hcC5nZXRDYW52YXMoKS5zdHlsZS5jdXJzb3IgPSAicG9pbnRlciIpKTsKZGlmZiAtLWdpdCBhL21hcC90ZXN0Lm1qcyBi
L21hcC90ZXN0Lm1qcwppbmRleCA2MzE5OWVhLi45MDU0MjRmIDEwMDY0NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rl
c3QubWpzCkBAIC0yNzc0LDggKzI3NzQsOCBAQCBjb25zb2xlLmxvZygiXG5OdXNhbnRhcmEncyBsYXllcnMgc2F5IHdoYXQgdGhl
eSBzaG93Iik7CiAgICAgICBjaGVjaygiZXZlcnkgaGFydmVzdGVyIGhhbmRzIGl0cyB3aG9sZSBzb3VyY2Ugcm93IG9uLCBhbmQg
dGhlIHBpcGVsaW5lIGZpbGVzIGl0IGluIHBpZWNlcyBiZXNpZGUgdGhlIHRpbGVzIiwKICAgICAgICAgICAgIGhhcnYuZXZlcnko
KGgpID0+IC8icmF3IjogW2Etel0rLFxuXHMqImV4dHJhIjogXHsvLnRlc3QoaCkpICYmIC9kZWYgd3JpdGVfcGllY2VzXChyYXdz
LCBwaWVjZXNfZGlyXCkvLnRlc3Qobm9ybSkgJiYKICAgICAgICAgICAgIC9waWVjZXNfZGlyPWYibWFwXC9kYXRhXC9waWVjZXNc
L1x7YXJnc1wuc291cmNlXH0iLy50ZXN0KG5vcm0pICYmIC9QSUVDRVNfU0tJUCA9IFx7ImNsaW1hdGVfdHJhY2UiXH0vLnRlc3Qo
bm9ybSkpOwotICAgICAgY2hlY2soIlx1MjAyNmFuZCBhIGNsaWNrIHNob3dzIGV2ZXJ5IGZpZWxkIGZyb20gdGhlIHJlY29yZCdz
IHBpZWNlLCBmb3VuZCBieSB0aGUgc2FtZSBoYXNoIHRoZSBwaXBlbGluZSB1c2VkIiwKLSAgICAgICAgICAgIC9yZWFkUGllY2Vc
KGBkYXRhXC9waWVjZXNcL1wkXHtwXC5zb3VyY2VcfWAsIHBcLmlkXCkvLnRlc3Qoc3JjKSAmJiAvRXZlcnkgZmllbGQgdGhlIHNv
dXJjZSBwdWJsaXNoZXMvLnRlc3Qoc3JjKSAmJgorICAgICAgY2hlY2soIlx1MjAyNmFuZCBhIGNsaWNrIHNob3dzIGV2ZXJ5IGZp
ZWxkIGZyb20gdGhlIHJlY29yZCdzIHBpZWNlLCBmb3VuZCBieSB0aGUgc2FtZSBoYXNoIHRoZSBwaXBlbGluZSB1c2VkLCB0aGUg
cGllY2VzIG5hbWVkIGJ5IHRoZSBsYXllciBzaW5jZSB0aGUgdGlsZXMgY2Fycnkgbm8gc291cmNlIGZpZWxkIiwKKyAgICAgICAg
ICAgIC9yZWFkUGllY2VcKGBkYXRhXC9waWVjZXNcL1wkXHtmcm9tXH1gLCBwXC5pZFwpLy50ZXN0KHNyYykgJiYgL2JpbmRQb3B1
cFwoYFwkXHtjZmdcLmlkXH0tcHRgLCBvd25lclwpLy50ZXN0KHNyYykgJiYgL0V2ZXJ5IGZpZWxkIHRoZSBzb3VyY2UgcHVibGlz
aGVzLy50ZXN0KHNyYykgJiYKICAgICAgICAgICAgIC9oID0gXChcKGggXF4gYlwpIFwqIDB4MDEwMDAxOTNcKSAmIDB4RkZGRkZG
RkYvLnRlc3Qobm9ybSkpOwogICAgICAgY29uc3QgZmllbGRSb3dzID0gbmV3IEZ1bmN0aW9uKCJlc2NhcGVIdG1sIiwgc3JjLm1h
dGNoKC9mdW5jdGlvbiBmaWVsZFJvd3NbXHNcU10qP1xufVxuLylbMF0gKyAiOyByZXR1cm4gZmllbGRSb3dzOyIpKCh4KSA9PiBT
dHJpbmcoeCkpOwogICAgICAgY2hlY2soIlx1MjAyNmFuZCBhIHZhbHVlIEpTT04gY2Fubm90IHdyaXRlIChhIHNldCwgYSBkYXRl
KSBpcyB3cml0dGVuIHBsYWlubHkgcmF0aGVyIHRoYW4gc3RvcHBpbmcgdGhlIGhhcnZlc3QiLAo=
""").decode("utf-8")


def run(cmd, text=None):
    return subprocess.run(cmd, input=text, text=True, capture_output=True)


def main():
    if not pathlib.Path("map/app.js").exists():
        sys.exit("Run this from the culprits folder (cd ~/Desktop/culprits).")
    app = pathlib.Path("map/app.js").read_text(encoding="utf-8")
    if "const GLOW = {" not in app:
        sys.exit("patch_0922g.py has to be applied and committed first.")
    if run(["git", "apply", "--check", "--reverse", "-"], DIFF).returncode == 0:
        print("Already applied - nothing to do.")
        return
    check = run(["git", "apply", "--check", "-"], DIFF)
    if check.returncode != 0:
        print(check.stderr.strip())
        sys.exit("Does not apply cleanly.")
    out = run(["git", "apply", "-"], DIFF)
    if out.returncode != 0:
        print(out.stderr.strip())
        sys.exit("git apply failed.")
    print("Applied. Changed: map/app.js, map/test.mjs")
    print("Now run both suites:")
    print("    cd map && node test.mjs && node wire.test.mjs")


if __name__ == "__main__":
    main()
