#!/usr/bin/env python3
"""
patch_0923_ridge.py - pronounced relief on the Satellite basemap at world and
  continent scale, as the paleo-map plates draw it; the sea floor stays calm.

Needs patch_0923_even.py first.
Run from the culprits folder:  python3 patch_0923_ridge.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IGIyOWJjYTEuLmNmNjhjMzQgMTAwNjQ0Ci0tLSBhL0hB
TkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtNSw3ICs1LDIwIEBAIHRvdWNoZXMuCiAKIC0tLQogCi0jIyBUaGUgU2F0ZWxs
aXRlIGJhc2VtYXAsIHRoZSBzYW1lIGF0IGV2ZXJ5IHpvb207IHRoZSBwbGF0ZXMnIGJsdWVzICgyMyBTZXB0ZW1iZXIsIGxhdGVz
dCkKKyMjIFRoZSBTYXRlbGxpdGUgYmFzZW1hcDogcHJvbm91bmNlZCByZWxpZWYgYXQgd29ybGQgc2NhbGUgKDIzIFNlcHRlbWJl
ciwgbGF0ZXN0KQorCitPbiB0b3Agb2YgcGF0Y2hfMDkyM19ldmVuLiBUaGUgb3duZXIgZm91bmQgdGhlIHdvcmxkIHZpZXcgZmxh
dCBuZXh0IHRvIHRoZQorcGxhdGVzLCB3aG9zZSByZWxpZWYgaXMgcHJvbm91bmNlZCBvbiBwdXJwb3NlLiBUd28gbmV3IGhpbGxz
aGFkZXMsCitgc2F0LXJlbGllZi1yaWRnZWAgYW5kIGBzYXQtcmVsaWVmLXJpZGdlMmAgKHNhbWUgcGFpbnQsIGBTQVRfUkVMSUVG
LnJpZGdlYDoKK3N0YW5kYXJkIG1ldGhvZCwgTlcgbGlnaHQgYXQgMzAgZGVncmVlcywgc2hhZG93IGFscGhhIDEgYW5kIHBhbGUg
bGlnaHQgMC4zNCBhdAorem9vbSAzIGVhc2luZyB0byAwIGJ5IHpvb20gNywgbWF4em9vbSA3KSwgZHJhd24gdHdpY2UgYmVjYXVz
ZSBvbmUgaGlsbHNoYWRlCit0b3BzIG91dCBhdCBleGFnZ2VyYXRpb24gMS4gVGhleSBzaXQgZGlyZWN0bHkgb24gdGhlIGltYWdl
cnksIHVuZGVyCitgc2F0LXJlbGllZi1jb2xvdXJgOiB0aGUgc2VlLXRocm91Z2ggbGFuZCBwYWxldHRlIGxldHMgdGhlIHJhbmdl
cyBzaG93LCBhbmQKK3RoZSBuZWFyLXNvbGlkIGRlZXAtc2VhIG5hdnkgaGlkZXMgdGhlbSBzbyB0aGUgb2NlYW4gZmxvb3Igc3Rh
eXMgY2FsbS4gRnJvbQorem9vbSA3IGluIHRoZSBsb29rIGlzIHVuY2hhbmdlZC4gVHJpZWQgaW4gcHJldmlldzogYGNvbWJpbmVk
YCBhbmQgYGlnb3JgCittZXRob2RzICh3ZWFrZXIgYXQgd29ybGQgdmlldyB0aGFuIGRvdWJsZWQgYHN0YW5kYXJkYCkuCisKKyMj
IFRoZSBTYXRlbGxpdGUgYmFzZW1hcCwgdGhlIHNhbWUgYXQgZXZlcnkgem9vbTsgdGhlIHBsYXRlcycgYmx1ZXMgKDIzIFNlcHRl
bWJlcikKIAogT24gdG9wIG9mIHRoZSBwYWxlby1tYXAgcGF0Y2ggKDU3ZDA0YTkpLiBUaGUgb3duZXIgc2F3IHRoZSBsb29rIGhh
bmQgb3ZlciB0bwogcGxhaW4gaW1hZ2VyeSBjbG9zZXIgaW4gYW5kIHdhbnRzIHRoZSBzYW1lIGVmZmVjdHMgYXQgYWxsIHpvb21z
OiB0aGUgdGludCdzCmRpZmYgLS1naXQgYS9tYXAvYXBwLmpzIGIvbWFwL2FwcC5qcwppbmRleCAyY2EzMzcxLi4xNmY1NzhhIDEw
MDY0NAotLS0gYS9tYXAvYXBwLmpzCisrKyBiL21hcC9hcHAuanMKQEAgLTg0OCw2ICs4NDgsMjYgQEAgY29uc3QgU0FUX1JFTElF
RiA9IHsKICAgICAiaGlsbHNoYWRlLWFjY2VudC1jb2xvciI6ICJyZ2JhKDEyLDE4LDEwLDApIiwKICAgICAiaGlsbHNoYWRlLWV4
YWdnZXJhdGlvbiI6IDAuMywKICAgfSwKKyAgLy8gUHJvbm91bmNlZCByZWxpZWYgZm9yIHRoZSB3b3JsZCBhbmQgY29udGluZW50
IHZpZXdzICgyMyBTZXB0ZW1iZXIpLCBhcworICAvLyB0aGUgcGxhdGVzIGRyYXcgaXQgb24gcHVycG9zZTogYSBsb3cgbm9ydGgt
d2VzdCBsaWdodCwgZHJhd24gdHdpY2UKKyAgLy8gKHNhdC1yZWxpZWYtcmlkZ2UgYW5kIC1yaWRnZTI7IG9uZSBsYXllciB0b3Bz
IG91dCBhdCBleGFnZ2VyYXRpb24gMSksIHRoYXQKKyAgLy8gY2FydmVzIHRoZSByYW5nZXMgd2l0aCBkZWVwIHNoYWRvdyBhbmQg
YSBwYWxlIGxpdCBmYWNlLiBBIHJhbmdlIGlzIG9ubHkgYQorICAvLyBmZXcgcGl4ZWxzIHdpZGUgZnJvbSB0aGUgd29ybGQgdmll
dywgc28gaXQgbmVlZHMgZmFyIG1vcmUgbGlnaHQgYW5kIHNoYWRvdworICAvLyB0aGFuIGNsb3NlIGluIHRvIHJlYWQgYXMgaGln
aCBncm91bmQ7IHRoZSBwYWlyIGlzIGF0IGZ1bGwgc3RyZW5ndGggb3V0IHRvCisgIC8vIHpvb20gMyBhbmQgZWFzZXMgdG8gbm90
aGluZyBieSB6b29tIDcsIHdoZXJlIHRoZSBvdGhlciB0d28gbGlnaHRzIGNhcnJ5IHRoZQorICAvLyByZWxpZWYgYXMgYmVmb3Jl
LiBUaGV5IHNpdCBkaXJlY3RseSBvbiB0aGUgaW1hZ2VyeSwgdW5kZXIgdGhlIHRlcnJhaW4KKyAgLy8gcGFsZXR0ZTogdGhlIGxh
bmQgcGFsZXR0ZSBpcyBzZWUtdGhyb3VnaCwgc28gdGhlIHJhbmdlcyBzaG93LCB3aGlsZSB0aGUKKyAgLy8gbmVhci1zb2xpZCBu
YXZ5IG9mIHRoZSBkZWVwIHNlYSBjb3ZlcnMgdGhlbSBhbmQgdGhlIG9jZWFuIGZsb29yIHN0YXlzIGNhbG0uCisgIHJpZGdlOiB7
CisgICAgImhpbGxzaGFkZS1tZXRob2QiOiAic3RhbmRhcmQiLAorICAgICJoaWxsc2hhZGUtaWxsdW1pbmF0aW9uLWRpcmVjdGlv
biI6IDMxNSwKKyAgICAiaGlsbHNoYWRlLWlsbHVtaW5hdGlvbi1hbHRpdHVkZSI6IDMwLAorICAgICJoaWxsc2hhZGUtaWxsdW1p
bmF0aW9uLWFuY2hvciI6ICJtYXAiLAorICAgICJoaWxsc2hhZGUtaGlnaGxpZ2h0LWNvbG9yIjogWyJpbnRlcnBvbGF0ZSIsIFsi
bGluZWFyIl0sIFsiem9vbSJdLCAzLCAicmdiYSgyMzYsMjMyLDIxNiwwLjM0KSIsIDcsICJyZ2JhKDIzNiwyMzIsMjE2LDApIl0s
CisgICAgImhpbGxzaGFkZS1zaGFkb3ctY29sb3IiOiBbImludGVycG9sYXRlIiwgWyJsaW5lYXIiXSwgWyJ6b29tIl0sIDMsICJy
Z2JhKDE0LDE4LDEwLDEpIiwgNywgInJnYmEoMTQsMTgsMTAsMCkiXSwKKyAgICAiaGlsbHNoYWRlLWFjY2VudC1jb2xvciI6IFsi
aW50ZXJwb2xhdGUiLCBbImxpbmVhciJdLCBbInpvb20iXSwgMywgInJnYmEoMTQsMTgsMTAsMC41KSIsIDcsICJyZ2JhKDE0LDE4
LDEwLDApIl0sCisgICAgImhpbGxzaGFkZS1leGFnZ2VyYXRpb24iOiAxLAorICB9LAogICAvLyBXaXRoIDNEIHRlcnJhaW4gb24s
IHRoZSBncm91bmQgaXMgcmFpc2VkIG1vcmUgdGhlIGZ1cnRoZXIgb3V0IHlvdSBhcmUsCiAgIC8vIHNvIHJhbmdlcyBzdGlsbCBz
dGFuZCB1cCBmcm9tIGEgY29udGluZW50J3MgaGVpZ2h0OyAxLjQgY2xvc2UgaW4uCiAgIGxpZnQ6IFtbMywgNC41XSwgWzYsIDNd
LCBbOSwgMl0sIFsxMiwgMS40XV0sCkBAIC0xOTcxLDYgKzE5OTEsOCBAQCBmdW5jdGlvbiBhZGRTYXRlbGxpdGVSZWxpZWYoKSB7
CiAgIHRyeSB7CiAgICAgaWYgKCFtYXAuZ2V0U291cmNlKCJvdXRsaW5lLWRlbSIpKSBtYXAuYWRkU291cmNlKCJvdXRsaW5lLWRl
bSIsIE9iamVjdC5hc3NpZ24oe30sIFJFTElFRl9TT1VSQ0UpKTsKICAgICBjb25zdCBiZWZvcmUgPSBtYXAuZ2V0TGF5ZXIoImF0
bGFzLXdhc2hlcyIpID8gImF0bGFzLXdhc2hlcyIgOiB1bmRlZmluZWQ7CisgICAgbWFwLmFkZExheWVyKHsgaWQ6ICJzYXQtcmVs
aWVmLXJpZGdlIiwgdHlwZTogImhpbGxzaGFkZSIsIHNvdXJjZTogIm91dGxpbmUtZGVtIiwgbWF4em9vbTogNywgcGFpbnQ6IFNB
VF9SRUxJRUYucmlkZ2UgfSwgYmVmb3JlKTsKKyAgICBtYXAuYWRkTGF5ZXIoeyBpZDogInNhdC1yZWxpZWYtcmlkZ2UyIiwgdHlw
ZTogImhpbGxzaGFkZSIsIHNvdXJjZTogIm91dGxpbmUtZGVtIiwgbWF4em9vbTogNywgcGFpbnQ6IFNBVF9SRUxJRUYucmlkZ2Ug
fSwgYmVmb3JlKTsKICAgICBtYXAuYWRkTGF5ZXIoeyBpZDogInNhdC1yZWxpZWYtY29sb3VyIiwgdHlwZTogImNvbG9yLXJlbGll
ZiIsIHNvdXJjZTogIm91dGxpbmUtZGVtIiwKICAgICAgIHBhaW50OiB7ICJjb2xvci1yZWxpZWYtY29sb3IiOiBTQVRfUkVMSUVG
LmNvbG91ciwgImNvbG9yLXJlbGllZi1vcGFjaXR5IjogU0FUX1JFTElFRi5jb2xvdXJPcGFjaXR5IH0gfSwgYmVmb3JlKTsKICAg
ICBtYXAuYWRkTGF5ZXIoeyBpZDogInNhdC1yZWxpZWYtc2hhZGUiLCB0eXBlOiAiaGlsbHNoYWRlIiwgc291cmNlOiAib3V0bGlu
ZS1kZW0iLCBwYWludDogU0FUX1JFTElFRi5zaGFkZSB9LCBiZWZvcmUpOwpAQCAtMTk5Nyw2ICsyMDE5LDggQEAgZnVuY3Rpb24g
c2V0QmFzZW1hcChraW5kKSB7CiAgIHNob3coInNhdC1yZWxpZWYtc2hhZGUiLCBraW5kID09PSAic2F0ZWxsaXRlIik7CiAgIHNo
b3coInNhdC1yZWxpZWYtZGVwdGgiLCBraW5kID09PSAic2F0ZWxsaXRlIik7CiAgIHNob3coInNhdC1yZWxpZWYtc2VhIiwga2lu
ZCA9PT0gInNhdGVsbGl0ZSIpOworICBzaG93KCJzYXQtcmVsaWVmLXJpZGdlIiwga2luZCA9PT0gInNhdGVsbGl0ZSIpOworICBz
aG93KCJzYXQtcmVsaWVmLXJpZGdlMiIsIGtpbmQgPT09ICJzYXRlbGxpdGUiKTsKICAgaWYgKFRFUlJBSU5fT04gJiYgbWFwLmdl
dFRlcnJhaW4gJiYgbWFwLmdldFRlcnJhaW4oKSkgbGlmdFRlcnJhaW4oKTsKICAgc2hvdygib3V0bGluZS1vY2VhbiIsICFpbWFn
ZXJ5KTsKICAgc2hvdygib3V0bGluZS1sYW5kIiwgIWltYWdlcnkpOwpkaWZmIC0tZ2l0IGEvbWFwL3Rlc3QubWpzIGIvbWFwL3Rl
c3QubWpzCmluZGV4IDE5NDM2MzYuLjlkNWU1MjggMTAwNjQ0Ci0tLSBhL21hcC90ZXN0Lm1qcworKysgYi9tYXAvdGVzdC5tanMK
QEAgLTEzOTIsOCArMTM5MiwxMyBAQCBjb25zb2xlLmxvZygiXG5yZWFkaW5nIHRoZSBtYXAiKTsKICAgICAgICAgICAvImhpbGxz
aGFkZS1pbGx1bWluYXRpb24tZGlyZWN0aW9uIjogXFszMTUsIDI3MCwgMCwgMjI1XF0vLnRlc3QoYmxvY2spICYmCiAgICAgICAg
ICAgWy4uLmJsb2NrLm1hdGNoQWxsKC9yZ2JhXCgyNDAsMjM2LDIyMiwoW1xkLl0rKVwpL2cpXS5ldmVyeSgobSkgPT4gK21bMV0g
PD0gMC4xKSAmJgogICAgICAgICAgIC8iaGlsbHNoYWRlLWV4YWdnZXJhdGlvbiI6IDBcLjksLy50ZXN0KGJsb2NrKSAmJiAvImhp
bGxzaGFkZS1leGFnZ2VyYXRpb24iOiAwXC4zLC8udGVzdChibG9jaykgJiYKLSAgICAgICAgICAvY29sb3VyT3BhY2l0eTogMSwv
LnRlc3QoYmxvY2spICYmICEvXFsiem9vbSJcXS8udGVzdChibG9jay5zbGljZSgwLCBibG9jay5pbmRleE9mKCJsaWZ0OiIpKSkg
JiYKKyAgICAgICAgICAvY29sb3VyT3BhY2l0eTogMSwvLnRlc3QoYmxvY2spICYmICEvXFsiem9vbSJcXS8udGVzdChibG9jay5z
bGljZSgwLCBibG9jay5pbmRleE9mKCJyaWRnZToiKSkpICYmCiAgICAgICAgICAgLyJmb2ctZ3JvdW5kLWJsZW5kIjogMFwuOTcv
LnRlc3Qoc3JjKSk7CisgICAgY2hlY2soIuKApnByb25vdW5jZWQgcmVsaWVmIHdpZGVyIG91dDogYSBsb3cgbm9ydGgtd2VzdCBs
aWdodCBkcmF3biB0d2ljZSwgc3RyYWlnaHQgb24gdGhlIGltYWdlcnkgdW5kZXIgdGhlIHBhbGV0dGUsIHN0cm9uZyB0byB6b29t
IDMgYW5kIGdvbmUgYnkgem9vbSA3IiwKKyAgICAgICAgICAvaWQ6ICJzYXQtcmVsaWVmLXJpZGdlIiwgdHlwZTogImhpbGxzaGFk
ZSIsIHNvdXJjZTogIm91dGxpbmUtZGVtIiwgbWF4em9vbTogNywgcGFpbnQ6IFNBVF9SRUxJRUZcLnJpZGdlIFx9LCBiZWZvcmVc
KTtcblxzKm1hcFwuYWRkTGF5ZXJcKFx7IGlkOiAic2F0LXJlbGllZi1yaWRnZTIiLCB0eXBlOiAiaGlsbHNoYWRlIiwgc291cmNl
OiAib3V0bGluZS1kZW0iLCBtYXh6b29tOiA3LCBwYWludDogU0FUX1JFTElFRlwucmlkZ2UgXH0sIGJlZm9yZVwpO1xuXHMqbWFw
XC5hZGRMYXllclwoXHsgaWQ6ICJzYXQtcmVsaWVmLWNvbG91ciIvLnRlc3Qoc3JjKSAmJgorICAgICAgICAgIC9zaG93XCgic2F0
LXJlbGllZi1yaWRnZSIsIGtpbmQgPT09ICJzYXRlbGxpdGUiXCk7XG5ccypzaG93XCgic2F0LXJlbGllZi1yaWRnZTIiLCBraW5k
ID09PSAic2F0ZWxsaXRlIlwpOy8udGVzdChzcmMpICYmCisgICAgICAgICAgLyJoaWxsc2hhZGUtc2hhZG93LWNvbG9yIjogXFsi
aW50ZXJwb2xhdGUiLCBcWyJsaW5lYXIiXF0sIFxbInpvb20iXF0sIDMsICJyZ2JhXCgxNCwxOCwxMCwxXCkiLCA3LCAicmdiYVwo
MTQsMTgsMTAsMFwpIlxdLy50ZXN0KGJsb2NrKSAmJgorICAgICAgICAgIC8iaGlsbHNoYWRlLWhpZ2hsaWdodC1jb2xvciI6IFxb
ImludGVycG9sYXRlIiwgXFsibGluZWFyIlxdLCBcWyJ6b29tIlxdLCAzLCAicmdiYVwoMjM2LDIzMiwyMTYsMFwuMzRcKSIsIDcs
ICJyZ2JhXCgyMzYsMjMyLDIxNiwwXCkiXF0vLnRlc3QoYmxvY2spKTsKICAgICBjaGVjaygi4oCmbm8gZHJhd24gd2F0ZXIiLAog
ICAgICAgICAgICEvc2F0LXdhdGVyLy50ZXN0KHNyYykgJiYgIS9jbG9zZU11bHRpcGx5Ly50ZXN0KHNyYykgJiYKICAgICAgICAg
ICAoc3JjLm1hdGNoKC9tYXBcLmFkZFNvdXJjZVwoIm9zbSIsIE9iamVjdFwuYXNzaWduXChce1x9LCBPU01fU09VUkNFXClcKS9n
KSB8fCBbXSkubGVuZ3RoID09PSAxKTsK
""")

root = pathlib.Path.cwd()
app = root / "map" / "app.js"
if not app.exists():
    sys.exit("Run this from the culprits folder (cd ~/Desktop/culprits), not from inside map/.")
s = app.read_text(encoding="utf-8")
if "sat-relief-ridge" in s:
    sys.exit("Already applied: nothing to do.")
if "colourOpacity: 1," not in s:
    sys.exit("This needs patch_0923_even.py first. Run: python3 patch_0923_even.py   then try again.")
tmp = root / ".patch_0923_ridge.diff"
tmp.write_bytes(DIFF)
try:
    chk = subprocess.run(["git", "apply", "--check", str(tmp)], capture_output=True, text=True)
    if chk.returncode != 0:
        sys.exit("The patch does not fit these files, so nothing was changed:\n" + chk.stderr)
    subprocess.run(["git", "apply", str(tmp)], check=True)
finally:
    tmp.unlink(missing_ok=True)
print("Applied: pronounced relief at world scale (map/app.js, map/test.mjs, HANDOFF.md).")
