#!/usr/bin/env python3
"""
patch_0922r.py - the Satellite basemap's tint held near full at every zoom, so the
                 theme shows on flat and gentle ground close in, not only on slopes.

Needs patch_0922q.py applied and committed first (it is on main).
Run from the repo folder:  python3 patch_0922r.py
"""
import base64, pathlib, subprocess, sys

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IDZkYWU3ZGEuLjI1ZWZhMTAgMTAwNjQ0Ci0tLSBhL0hB
TkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtMzE3LDYgKzMxNywxNiBAQCBDb3N0OiB0aHJlZSBtb3JlIHBhY2thZ2UgZG93
bmxvYWRzIHBlciBzZWN0b3IgcGVyIHJ1biAoYWdyaWN1bHR1cmUncyBjbzJlCiBwYWNrYWdlIGFsb25lIGlzIDEuNCBHQiksIHNv
IHRoZSBwZXItZ2FzIGhhcnZlc3Qgc2hvdWxkIHJ1biBhcyBpdHMgb3duIGpvYgogd2l0aCBpdHMgb3duIEVUYWdzIHJhdGhlciB0
aGFuIGluc2lkZSB0aGUgZXhpc3Rpbmcgb25lLiBOb3Qgd3JpdHRlbiB5ZXQuCiAKKyMjIFRoZSBTYXRlbGxpdGUgdGludCBoZWxk
IGF0IGV2ZXJ5IHpvb20gKDIyIFNlcHRlbWJlciwgbmlnaHQpCisKK0Nsb3NlIGluLCB0aGUgb3duZXIgc2F3IHRoZSB0aGVtZSBv
bmx5IG9uIHN0ZWVwIGdyb3VuZCBhbmQgdGhlIHBsYWluCitwaG90b2dyYXBoIGVsc2V3aGVyZS4gVGhlIHRpbnQgaGFkIGVhc2Vk
IHRvIDAuNyBvcGFjaXR5IHdpdGggbGFuZCBhbHBoYXMgb2YKKzAuMyAoYWJvdXQgYSBmaWZ0aCBvZiB0aGUgd2F5KSwgYW5kIHRo
ZSBicmlnaHRlciBpbWFnZXJ5IGdyYWRlIG9mIHRoZSBmb3VydGgKK3ZlcnNpb24gcHVsbGVkIHRoZSByZXN0IGJhY2sgdG8gdGhl
IHBob3RvZ3JhcGguIE5vdyBsYW5kIHRpbnQgYWxwaGFzIDAuMzgtMC40NiwKK2NvbG91ciBvcGFjaXR5IDEgd2lkZSB0byAwLjg1
IGF0IHpvb20gMTY7IGltYWdlcnkgbWF4IDAuOTUsIHNhdHVyYXRpb24KKyswLjEyLCBjb250cmFzdCAwLjE0LiBUaGUgc2hhZGlu
ZyBvbmx5IHNob3dzIHdoZXJlIHRoZSBncm91bmQgc2xvcGVzLCBzbyBvbgorZmxhdCBncm91bmQgaXQgaXMgdGhlIHRpbnQgdGhh
dCBjYXJyaWVzIHRoZSBsb29rLgorCiAjIyBUaGUgU2F0ZWxsaXRlIHJlbGllZiwgZm91cnRoIHZlcnNpb24gKDIyIFNlcHRlbWJl
ciwgbGF0ZSkKIAogVGhlIHNvZnRlbmVkIHZlcnNpb24gZHJvcHBlZCB0aGUgdGludCBhbmQgc2hhZGluZyBjbG9zZSBpbiBhbmQg
bG9zdCB0aGUKZGlmZiAtLWdpdCBhL21hcC9hcHAuanMgYi9tYXAvYXBwLmpzCmluZGV4IDQzNDEyN2IuLmI3OTgyNDcgMTAwNjQ0
Ci0tLSBhL21hcC9hcHAuanMKKysrIGIvbWFwL2FwcC5qcwpAQCAtNzg4LDggKzc4OCw4IEBAIGNvbnN0IEJBU0VfR1JBREUgPSB7
CiAgIC8vIGluIGVhcnRoIHRvbmVzIChTQVRfUkVMSUVGIGJlbG93KTogdGhlIGltYWdlcnkgaXMgb25seSBhIGxpdHRsZSBtdXRl
ZCwgc28KICAgLy8gdGhlIGdyb3VuZCBrZWVwcyBpdHMgb3duIGNvbG91ciBhbmQgdGV4dHVyZSwgYW5kIHRoZSByZWxpZWYncyBw
YWxldHRlIGFuZAogICAvLyBTd2lzcy1zdHlsZSBzaGFkaW5nIGFyZSBsYWlkIG92ZXIgaXQuCi0gIHNhdGVsbGl0ZTogeyAicmFz
dGVyLWJyaWdodG5lc3MtbWluIjogMC4wMiwgInJhc3Rlci1icmlnaHRuZXNzLW1heCI6IDEsCi0gICAgICAgICAgICAgICAicmFz
dGVyLXNhdHVyYXRpb24iOiAwLjIsICJyYXN0ZXItY29udHJhc3QiOiAwLjEsCisgIHNhdGVsbGl0ZTogeyAicmFzdGVyLWJyaWdo
dG5lc3MtbWluIjogMC4wMiwgInJhc3Rlci1icmlnaHRuZXNzLW1heCI6IDAuOTUsCisgICAgICAgICAgICAgICAicmFzdGVyLXNh
dHVyYXRpb24iOiAwLjEyLCAicmFzdGVyLWNvbnRyYXN0IjogMC4xNCwKICAgICAgICAgICAgICAgICJyYXN0ZXItaHVlLXJvdGF0
ZSI6IDAgfSwKIH07CiBsZXQgQkFTRU1BUCA9ICJhdGxhcyI7CkBAIC04MjYsOSArODI2LDEyIEBAIGNvbnN0IFNBVF9SRUxJRUYg
PSB7CiAgIGNvbG91cjogWyJpbnRlcnBvbGF0ZSIsIFsibGluZWFyIl0sIFsiZWxldmF0aW9uIl0sCiAgICAgLTgwMDAsICJyZ2Jh
KDgsMzAsNTYsMC44KSIsIC0zMDAwLCAicmdiYSgxMCwzOCw2NiwwLjc1KSIsIC01MDAsICJyZ2JhKDE4LDU4LDg0LDAuNikiLAog
ICAgIC02MCwgInJnYmEoMjYsODQsMTAwLDAuNDIpIiwgMCwgInJnYmEoMjYsODQsMTAwLDAuMykiLAotICAgIDEsICJyZ2JhKDQw
LDg2LDM0LDAuMykiLCA0MDAsICJyZ2JhKDQ2LDkwLDM4LDAuMykiLCAxMjAwLCAicmdiYSg2Miw5Miw0NiwwLjI2KSIsCi0gICAg
MjIwMCwgInJnYmEoOTYsODYsNjIsMC4yNCkiLCAzNTAwLCAicmdiYSgxMTIsMTA0LDkyLDAuMjQpIiwgNTUwMCwgInJnYmEoMTI0
LDExOCwxMDgsMC4yNikiXSwKLSAgY29sb3VyT3BhY2l0eTogWyJpbnRlcnBvbGF0ZSIsIFsibGluZWFyIl0sIFsiem9vbSJdLCAy
LCAxLCAxMCwgMC44NSwgMTQsIDAuNywgMTYsIDAuNl0sCisgICAgMSwgInJnYmEoNDAsODYsMzQsMC40NikiLCA0MDAsICJyZ2Jh
KDQ2LDkwLDM4LDAuNDYpIiwgMTIwMCwgInJnYmEoNjIsOTIsNDYsMC40MikiLAorICAgIDIyMDAsICJyZ2JhKDk2LDg2LDYyLDAu
MzgpIiwgMzUwMCwgInJnYmEoMTEyLDEwNCw5MiwwLjM4KSIsIDU1MDAsICJyZ2JhKDEyNCwxMTgsMTA4LDAuNCkiXSwKKyAgLy8g
SGVsZCBuZWFybHkgZnVsbCBhdCBldmVyeSB6b29tICgyMiBTZXB0ZW1iZXIsIG5pZ2h0KTogZWFzZWQgdG8gMC43IGNsb3NlCisg
IC8vIGluLCB0aGUgdGludCBvdmVyIGdlbnRsZSBncm91bmQgd2FzIHRvbyBmYWludCB0byBzZWUsIGFuZCBtb3N0IG9mIHRoZQor
ICAvLyBtYXAgcmVhZCBhcyB0aGUgcGxhaW4gcGhvdG9ncmFwaDsgb25seSBzdGVlcCBncm91bmQgc2hvd2VkIHRoZSB0aGVtZS4K
KyAgY29sb3VyT3BhY2l0eTogWyJpbnRlcnBvbGF0ZSIsIFsibGluZWFyIl0sIFsiem9vbSJdLCAyLCAxLCAxMCwgMC45NSwgMTQs
IDAuOSwgMTYsIDAuODVdLAogICAvLyBMaWdodCBmcm9tIGZvdXIgZGlyZWN0aW9ucywgd2VpZ2h0ZWQgdG8gdGhlIG5vcnRoLXdl
c3QgKFN3aXNzIHN0eWxlKToKICAgLy8gZ3JlZW4tYmxhY2sgc2hhZG93cywgZmFpbnQgd2FybSBzdW5saWdodCBvbiB0aGUgbGl0
IGZhY2VzLgogICBzaGFkZTogewpkaWZmIC0tZ2l0IGEvbWFwL3Rlc3QubWpzIGIvbWFwL3Rlc3QubWpzCmluZGV4IDQwZTBhZTYu
LmJlMjk4NjEgMTAwNjQ0Ci0tLSBhL21hcC90ZXN0Lm1qcworKysgYi9tYXAvdGVzdC5tanMKQEAgLTEzNDMsNyArMTM0Myw3IEBA
IGNvbnNvbGUubG9nKCJcbnJlYWRpbmcgdGhlIG1hcCIpOwogICAvLyBUaGlyZCB2ZXJzaW9uLCAyMiBTZXB0ZW1iZXI6IHRoZSBp
bWFnZXJ5IGNhcnJpZXMgdGhlIGNvbG91cjsgdGhlIHJlbGllZgogICAvLyB0aW50cyBpdCBhbmQgc3RhY2tzIHR3byBsYXllcnMg
b2Ygc2hhZGluZywgc28gdGhlIHdvcmxkIHZpZXcgaXMgbm90IGZsYXQuCiAgIGNoZWNrKCJ0aGUgU2F0ZWxsaXRlIGJhc2VtYXAg
aXMgcmljaGVyIGltYWdlcnkgdW5kZXIgYSBzZWUtdGhyb3VnaCByZWxpZWYgdGludCBhbmQgdHdvIGxheWVycyBvZiBzaGFkaW5n
OyB0aGUgYXRsYXMga2VlcHMgaXRzIG93biBncmFkZSIsCi0gICAgICAgIC9zYXRlbGxpdGU6IFx7ICJyYXN0ZXItYnJpZ2h0bmVz
cy1taW4iOiAwXC4wMiwgInJhc3Rlci1icmlnaHRuZXNzLW1heCI6IDEsXG5ccyoicmFzdGVyLXNhdHVyYXRpb24iOiAwXC4yLy50
ZXN0KHNyYykgJiYKKyAgICAgICAgL3NhdGVsbGl0ZTogXHsgInJhc3Rlci1icmlnaHRuZXNzLW1pbiI6IDBcLjAyLCAicmFzdGVy
LWJyaWdodG5lc3MtbWF4IjogMFwuOTUsXG5ccyoicmFzdGVyLXNhdHVyYXRpb24iOiAwXC4xMi8udGVzdChzcmMpICYmCiAgICAg
ICAgIC9hdGxhczogXHsgInJhc3Rlci1icmlnaHRuZXNzLW1pbiI6IEFUTEFTX1RVTkVcLmxpZnQvLnRlc3Qoc3JjKSAmJgogICAg
ICAgICAvaWQ6ICJzYXQtcmVsaWVmLWNvbG91ciIsIHR5cGU6ICJjb2xvci1yZWxpZWYiLCBzb3VyY2U6ICJvdXRsaW5lLWRlbSIv
LnRlc3Qoc3JjKSAmJgogICAgICAgICAvaWQ6ICJzYXQtcmVsaWVmLXNoYWRlIiwgdHlwZTogImhpbGxzaGFkZSIsIHNvdXJjZTog
Im91dGxpbmUtZGVtIiwgcGFpbnQ6IFNBVF9SRUxJRUZcLnNoYWRlLy50ZXN0KHNyYykgJiYKQEAgLTEzNTUsMTAgKzEzNTUsMTAg
QEAgY29uc29sZS5sb2coIlxucmVhZGluZyB0aGUgbWFwIik7CiAgICAgY29uc3QgYWxwaGFzID0gWy4uLmNvbG91ci5tYXRjaEFs
bCgvcmdiYVwoKFxkKyksKFxkKyksKFxkKyksKFtcZC5dKylcKS9nKV07CiAgICAgY2hlY2soIlx1MjAyNnRoZSBsYW5kIHRpbnQg
aXMgc2VlLXRocm91Z2ggKHRoZSBpbWFnZXJ5J3Mgb3duIGRlc2VydHMsIGZvcmVzdHMgYW5kIGljZSBzaG93KSwgbHVzaCBncmVl
biB0byBncmV5LWJyb3duLCBuZXZlciB3aGl0ZSIsCiAgICAgICAgICAgYWxwaGFzLmxlbmd0aCA+PSAxMCAmJiBhbHBoYXMuZXZl
cnkoKG0pID0+IE1hdGgubWF4KCttWzFdLCArbVsyXSwgK21bM10pIDw9IDEzMCkgJiYKLSAgICAgICAgICBhbHBoYXMuZmlsdGVy
KChtLCBpKSA9PiBpID49IDUpLmV2ZXJ5KChtKSA9PiArbVs0XSA8PSAwLjQpKTsKKyAgICAgICAgICBhbHBoYXMuZmlsdGVyKCht
LCBpKSA9PiBpID49IDUpLmV2ZXJ5KChtKSA9PiArbVs0XSA8PSAwLjUpKTsKICAgICAvLyBGb3VydGggdmVyc2lvbjogdGhlIG93
bmVyIHdhbnRzIHRoZSB0aW50IGFuZCBzaGFkaW5nIGtlcHQgY2xvc2UgaW4sIHdpdGhvdXQgdGhlIHNoZWVuLgotICAgIGNoZWNr
KCLigKZ0aGUgdGludCBhbmQgc2hhZGluZyBzdGF5IGF0IGV2ZXJ5IHpvb20sIGVhc2luZyBjbG9zZSBpbjsgdGhlIGRlcHRoIGxp
Z2h0IGlzIGdvbmUgYnkgMTE7IGZhaW50IHdhcm0gbGlnaHRzIG9ubHk7IGZvZyBvbmx5IGF0IHRoZSBob3Jpem9uIiwKLSAgICAg
ICAgL2NvbG91ck9wYWNpdHk6IFxbImludGVycG9sYXRlIiwgXFsibGluZWFyIlxdLCBcWyJ6b29tIlxdLCAyLCAxLCAxMCwgMFwu
ODUsIDE0LCAwXC43LCAxNiwgMFwuNlxdLy50ZXN0KHNyYykgJiYKKyAgICBjaGVjaygi4oCmdGhlIHRpbnQgYW5kIHNoYWRpbmcg
c3RheSBuZWFybHkgZnVsbCBhdCBldmVyeSB6b29tOyB0aGUgZGVwdGggbGlnaHQgaXMgZ29uZSBieSAxMTsgZmFpbnQgd2FybSBs
aWdodHMgb25seTsgZm9nIG9ubHkgYXQgdGhlIGhvcml6b24iLAorICAgICAgICAvY29sb3VyT3BhY2l0eTogXFsiaW50ZXJwb2xh
dGUiLCBcWyJsaW5lYXIiXF0sIFxbInpvb20iXF0sIDIsIDEsIDEwLCAwXC45NSwgMTQsIDBcLjksIDE2LCAwXC44NVxdLy50ZXN0
KHNyYykgJiYKICAgICAgICAgLyJoaWxsc2hhZGUtZXhhZ2dlcmF0aW9uIjogXFsiaW50ZXJwb2xhdGUiLCBcWyJsaW5lYXIiXF0s
IFxbInpvb20iXF0sIDIsIDEsIDgsIDBcLjksIDEyLCAwXC43LCAxNSwgMFwuNTVcXS8udGVzdChzcmMpICYmCiAgICAgICAgIC8i
aGlsbHNoYWRlLWV4YWdnZXJhdGlvbiI6IFxbImludGVycG9sYXRlIiwgXFsibGluZWFyIlxdLCBcWyJ6b29tIlxdLCAyLCAwXC44
NSwgNiwgMFwuNTUsIDksIDBcLjIsIDExLCAwXF0vLnRlc3Qoc3JjKSAmJgogICAgICAgICAvInJnYmFcKDI1MiwyNDQsMjIwLDBc
LjE0XCkiLy50ZXN0KHNyYykgJiYgIS8icmdiYVwoMlxkXGQsMlxkXGQsMlxkXGQsMFwuWzMtOV0vLnRlc3QoYmxvY2spICYmCg==
""")

def main():
    app = pathlib.Path("map/app.js")
    if not app.exists():
        sys.exit("Run this from the culprits folder (the one with map/app.js).")
    s = app.read_text(encoding="utf-8")
    if "16, 0.85]" in s:
        sys.exit("Already applied. Nothing changed.")
    if "16, 0.6]" not in s:
        sys.exit("patch_0922q.py has to be applied and committed first.")
    tmp = pathlib.Path(".patch_0922r.diff")
    tmp.write_bytes(DIFF)
    try:
        chk = subprocess.run(["git", "apply", "--check", str(tmp)], capture_output=True, text=True)
        if chk.returncode != 0:
            print(chk.stderr)
            sys.exit("Does not apply cleanly. Nothing changed.")
        subprocess.run(["git", "apply", str(tmp)], check=True)
    finally:
        tmp.unlink(missing_ok=True)
    print("Applied. Changed: map/app.js, map/test.mjs, HANDOFF.md")
    print("Now run both suites:")
    print("    cd map && node test.mjs && node wire.test.mjs")

main()
