#!/usr/bin/env python3
"""Atlas plates: only towns and cities answer a look-up; country and state names the plates print are set aside and listed.

Run from the repo folder:  python3 round_0923_plates2.py
Built against main at d15fad5. Checks first, changes nothing if it would not
apply cleanly, and says so if it is already in.
"""
import base64, subprocess, sys, tempfile, os

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL0hBTkRPRkYubWQgYi9IQU5ET0ZGLm1kCmluZGV4IDZhYzE1OTYuLmFhNTA2
ZmUgMTAwNjQ0Ci0tLSBhL0hBTkRPRkYubWQKKysrIGIvSEFORE9GRi5tZApAQCAtNSw2ICs1LDE4
IEBAIHRvdWNoZXMuCiAKIC0tLQogCisjIyBBdGxhcyBwbGF0ZXM6IGNvdW50cnkgbmFtZXMgc2V0
IGFzaWRlICgyMyBTZXB0ZW1iZXIsIGxhdGVyKQorCitUaGUgZmlyc3QgcnVuIHdpdGggbG9vay11
cHMgaW5zaWRlIGVhY2ggYm94IHBsYWNlZCBmb3VyIHBsYXRlcyB3aXRoIDQgbmFtZXMsCithbmQg
ZXZlcnkgb25lIGxlYW5lZCBvbiBhIGNvdW50cnk6IE1hZGFnYXNjYXIgKE1hZGFnYXNjYXIsIE1h
bGF3aSwgWmFtYmlhKSwKK1dhbGxhY2VhIChCcnVuZWksIFBoaWxpcHBpbmVzKSwgTW91bnRhaW5z
IG9mIFNvdXRod2VzdCBDaGluYSAoTXlhbm1hciksIGFuZAorUGhpbGlwcGluZXMgaGFkICJQaGls
aXBwaW5lcyIgYW1vbmcgaXRzIDEzLiBOb21pbmF0aW0ncyBzZXR0bGVtZW50IHR5cGUgbGV0cwor
Y291bnRyaWVzIGFuZCBzdGF0ZXMgdGhyb3VnaC4gYGdlb2NvZGVgIG5vdyBrZWVwcyBvbmx5IGFu
c3dlcnMgd2l0aAorYHBsYWNlX3JhbmtgIG9mIGF0IGxlYXN0IGBNSU5fVE9XTl9SQU5LYCAoMTM6
IHRvd25zIGFuZCBjaXRpZXMsIG5vdCBjb3VudGllcywKK3N0YXRlcyBvciBjb3VudHJpZXMpOyBh
IG5hbWUgd2hvc2UgYW5zd2VycyB3ZXJlIGFsbCByZWdpb25zIGlzIGxpc3RlZCBvbiB0aGUKK3Bs
YXRlIGFzIGBzZXRfYXNpZGVfYXNfcmVnaW9uc2AuIFRoZSBjYWNoZSBrZXkgZ2FpbmVkIGB8dG93
bnNgLCBzbyBldmVyeSBuYW1lCitpcyBhc2tlZCBhZ2FpbiBvbmNlLgorCiAjIyBBdGxhcyBob3Rz
cG90IHBsYXRlczogbG9vay11cHMga2VwdCBpbnNpZGUgZWFjaCBob3RzcG90ICgyMyBTZXB0ZW1i
ZXIsIGxhdGVzdCkKIAogYHBpcGVsaW5lL2F0bGFzX3BsYXRlcy5weWAgbm93IHJlYWRzIGVhY2gg
aG90c3BvdCdzIG91dGxpbmUgYm94IGZyb20gdGhlIHNhbWUKZGlmZiAtLWdpdCBhL3BpcGVsaW5l
L2F0bGFzX3BsYXRlcy5weSBiL3BpcGVsaW5lL2F0bGFzX3BsYXRlcy5weQppbmRleCAzNzhmMGQ3
Li44YTgyZWVkIDEwMDY0NAotLS0gYS9waXBlbGluZS9hdGxhc19wbGF0ZXMucHkKKysrIGIvcGlw
ZWxpbmUvYXRsYXNfcGxhdGVzLnB5CkBAIC03LDcgKzcsOCBAQCBtYXAgb2YgdGhhdCBob3RzcG90
LCB3aXRoIHRoZSBjaXRpZXMgb24gaXQgbmFtZWQgaW4gdGV4dCB0aGF0IHN0YXlzIHRleHQgaW4K
IHRoZSBmaWxlLiBUaGF0IGlzIGVub3VnaCB0byBwdXQgdGhlIHBhZ2Ugd2hlcmUgaXQgYmVsb25n
czoKIAogICAxLiByZWFkIGV2ZXJ5IHBsYWNlIG5hbWUgb24gdGhlIGZpcnN0IHBhZ2UgYW5kIHdo
ZXJlIGl0IHNpdHMgb24gdGhlIHBhZ2U7Ci0gIDIuIGxvb2sgZWFjaCBvbmUgdXAgb24gT3BlblN0
cmVldE1hcCAoTm9taW5hdGltKSwgdG93bnMgYW5kIGNpdGllcyBvbmx5LAorICAyLiBsb29rIGVh
Y2ggb25lIHVwIG9uIE9wZW5TdHJlZXRNYXAgKE5vbWluYXRpbSksIHRvd25zIGFuZCBjaXRpZXMg
b25seQorICAgICAoY291bnRyaWVzIGFuZCBzdGF0ZXMgdGhlIHBsYXRlIHByaW50cyBhcmUgc2V0
IGFzaWRlIGFuZCBsaXN0ZWQpLAogICAgICBhbmQgb25seSBpbnNpZGUgdGhlIGhvdHNwb3QncyBv
d24gb3V0bGluZSBib3ggKENvbnNlcnZhdGlvbgogICAgICBJbnRlcm5hdGlvbmFsJ3MgQmlvZGl2
ZXJzaXR5IEhvdHNwb3RzIDIwMTYuMSwgdGhlIG91dGxpbmVzIHRoZSBtYXAKICAgICAgZHJhd3Mp
LCBzbyBhIHNhbWUtbmFtZWQgdG93biBlbHNld2hlcmUgY2Fubm90IGFuc3dlcjogdGhlIFBoaWxp
cHBpbmVzCkBAIC04Miw2ICs4MywxMyBAQCBIT1RTUE9UUyA9IFsKIAogTUlOX0FHUkVFID0gNSAg
ICAgICAgICAgICMgbmFtZXMgdGhhdCBtdXN0IGFncmVlIG9uIHRoZSBwbGFjZW1lbnQKIE1BWF9F
UlJPUl9TSEFSRSA9IDAuMDMgICAjIHR5cGljYWwgZXJyb3Igbm8gbW9yZSB0aGFuIDMlIG9mIHRo
ZSBwbGF0ZSdzIHdpZHRoCisjIE9wZW5TdHJlZXRNYXAncyByYW5rIG9mIGEgcGxhY2U6IDQgYSBj
b3VudHJ5LCA4IGEgc3RhdGUsIDEyIGEgY291bnR5LCAxNiBhCisjIGNpdHksIDE4IGEgdG93bi4g
Tm9taW5hdGltJ3MgInNldHRsZW1lbnQiIHR5cGUgbGV0cyBjb3VudHJpZXMgYW5kIHN0YXRlcwor
IyB0aHJvdWdoLCBhbmQgdGhlIHBsYXRlcyBhbHNvIHByaW50IGNvdW50cnkgbmFtZXMgKCJNYWxh
d2kiLCAiUGhpbGlwcGluZXMiKToKKyMgb24gMjMgU2VwdGVtYmVyIGV2ZXJ5IHBsYXRlIHBsYWNl
ZCB3aXRoIDQgbmFtZXMgbGVhbmVkIG9uIG9uZSBvZiB0aGVtLiBPbmx5CisjIGFuc3dlcnMgcmFu
a2VkIGFzIGEgdG93biBvciBmaW5lciBhcmUgdXNlZC4KK01JTl9UT1dOX1JBTksgPSAxMworUkVH
SU9OUyA9IHNldCgpICAgICAgICAgICMgbmFtZXMgd2hvc2Ugb25seSBhbnN3ZXJzIHdlcmUgY291
bnRyaWVzIG9yIHJlZ2lvbnMKIE1JTl9BR1JFRV9TTUFMTCA9IDQgICAgICAjIG9uZSBmZXdlciBp
cyBhY2NlcHRlZCBvbmx5IHdpdGggaGFsZiB0aGUgZXJyb3IKIE1BWF9FUlJPUl9TSEFSRV9TTUFM
TCA9IDAuMDE1CiBCT1hfTUFSR0lOID0gMC4yNSAgICAgICAgIyBzaGFyZSBvZiB0aGUgb3V0bGlu
ZSBib3ggYWRkZWQgb24gZWFjaCBzaWRlIChhdCBsZWFzdCAxIGRlZ3JlZSkKQEAgLTMyNCw3ICsz
MzIsNyBAQCBkZWYgaW5zaWRlKGxvbiwgbGF0LCBib3gpOgogZGVmIGdlb2NvZGUobmFtZSwgY2Fj
aGUsIHNlc3Npb24sIGJveD1Ob25lKToKICAgICAiIiJUb3ducyBhbmQgY2l0aWVzIGNhbGxlZCBg
bmFtZWA7IHdpdGggYSBib3gsIG9ubHkgdGhvc2UgaW5zaWRlIGl0LAogICAgIGFza2VkIGZvciBp
bnNpZGUgaXQsIHNvIHRoZSBhbnN3ZXIgaXMgbm90IGZpdmUgc2FtZS1uYW1lZCB0b3ducyBlbHNl
d2hlcmUuIiIiCi0gICAga2V5ID0gbmFtZSBpZiBib3ggaXMgTm9uZSBlbHNlIG5hbWUgKyAifCIg
KyAiLCIuam9pbihmInt2Oi4yZn0iIGZvciB2IGluIGJveCkKKyAgICBrZXkgPSBuYW1lICsgInx0
b3ducyIgaWYgYm94IGlzIE5vbmUgZWxzZSBuYW1lICsgInx0b3duc3wiICsgIiwiLmpvaW4oZiJ7
djouMmZ9IiBmb3IgdiBpbiBib3gpCiAgICAgaWYga2V5IGluIGNhY2hlOgogICAgICAgICByZXR1
cm4gY2FjaGVba2V5XQogICAgIGlmIGJveCBpcyBOb25lOgpAQCAtMzQwLDEwICszNDgsMTYgQEAg
ZGVmIGdlb2NvZGUobmFtZSwgY2FjaGUsIHNlc3Npb24sIGJveD1Ob25lKToKICAgICAgICAgaWYg
cGFydDoKICAgICAgICAgICAgIHBhcmFtcy51cGRhdGUodmlld2JveD0iLCIuam9pbihmInt2Oi40
Zn0iIGZvciB2IGluIHBhcnQpLCBib3VuZGVkPTEpCiAgICAgICAgIHIgPSBzZXNzaW9uLmdldCgi
aHR0cHM6Ly9ub21pbmF0aW0ub3BlbnN0cmVldG1hcC5vcmcvc2VhcmNoIiwgcGFyYW1zPXBhcmFt
cywgaGVhZGVycz1VQSwgdGltZW91dD02MCkKLSAgICAgICAgZ290ICs9IFsoZmxvYXQoaFsibG9u
Il0pLCBmbG9hdChoWyJsYXQiXSkpIGZvciBoIGluIChyLmpzb24oKSBpZiByLm9rIGVsc2UgW10p
XQorICAgICAgICBoaXRzID0gci5qc29uKCkgaWYgci5vayBlbHNlIFtdCisgICAgICAgIHRvd25z
ID0gW2ggZm9yIGggaW4gaGl0cyBpZiBpbnQoaC5nZXQoInBsYWNlX3JhbmsiKSBvciAwKSA+PSBN
SU5fVE9XTl9SQU5LXQorICAgICAgICBpZiBoaXRzIGFuZCBub3QgdG93bnM6CisgICAgICAgICAg
ICBSRUdJT05TLmFkZChuYW1lKQorICAgICAgICBnb3QgKz0gWyhmbG9hdChoWyJsb24iXSksIGZs
b2F0KGhbImxhdCJdKSkgZm9yIGggaW4gdG93bnNdCiAgICAgaWYgYm94IGlzIG5vdCBOb25lOgog
ICAgICAgICBnb3QgPSBbcCBmb3IgcCBpbiAoaW5zaWRlKGxvbiwgbGF0LCBib3gpIGZvciBsb24s
IGxhdCBpbiBnb3QpIGlmIHBdCiAgICAgY2FjaGVba2V5XSA9IGdvdAorICAgIGlmIG5hbWUgaW4g
UkVHSU9OUzoKKyAgICAgICAgY2FjaGVbZiJ7bmFtZX18cmVnaW9ucyJdID0gVHJ1ZQogICAgIHJl
dHVybiBnb3QKIAogCkBAIC00MzQsNiArNDQ4LDkgQEAgZGVmIG1haW4ob25seSwgc2hvdz1GYWxz
ZSk6CiAgICAgICAgIGVudHJ5ID0geyJ0aXRsZSI6IHRpdGxlLCAicGRmIjogUERGX0JBU0UgKyBz
bHVnICsgIi5wZGYiLCAibGFiZWxzIjogbGVuKGxhYmVscyksICoqZ290fQogICAgICAgICBpZiBi
b3g6CiAgICAgICAgICAgICBlbnRyeVsibG9va2VkX3VwX3dpdGhpbiJdID0gW3JvdW5kKHYsIDMp
IGZvciB2IGluIGJveF0KKyAgICAgICAgcmVnaW9ucyA9IHNvcnRlZChuIGZvciBuIGluIGZvdW5k
IGlmIG4gaW4gUkVHSU9OUyBvciBub3QgZm91bmRbbl0gYW5kIGNhY2hlLmdldChmIntufXxyZWdp
b25zIikpCisgICAgICAgIGlmIHJlZ2lvbnM6CisgICAgICAgICAgICBlbnRyeVsic2V0X2FzaWRl
X2FzX3JlZ2lvbnMiXSA9IHJlZ2lvbnMKICAgICAgICAgZW50cnkucG9wKCJ3b3JzdCIsIE5vbmUp
CiAgICAgICAgIFQgPSBlbnRyeS5wb3AoImFmZmluZSIsIE5vbmUpCiAgICAgICAgIGlmIGdvdC5n
ZXQoImtlcHQiKToK
""").decode()


def git(*args, stdin=None):
    return subprocess.run(["git", *args], input=stdin, capture_output=True, text=True)


if git("rev-parse", "--show-toplevel").returncode:
    sys.exit("Run this from inside the repo folder.")
with tempfile.NamedTemporaryFile("w", suffix=".diff", delete=False) as f:
    f.write(DIFF)
    path = f.name
try:
    if git("apply", "--reverse", "--check", path).returncode == 0:
        print("Already applied; nothing to do.")
        sys.exit(0)
    chk = git("apply", "--check", path)
    if chk.returncode:
        print(chk.stderr.strip())
        sys.exit("Does not apply cleanly. It needs round_0923_plates.py (already pushed). Run git pull first; if it still refuses, the files changed since this was built.")
    res = git("apply", path)
    if res.returncode:
        sys.exit(res.stderr.strip())
    print("Applied. Changed:")
    for line in DIFF.splitlines():
        if line.startswith("+++ b/"):
            print("  " + line[6:])
finally:
    os.unlink(path)
