#!/usr/bin/env python3
"""Atlas plates: the drawn hotspot places or checks a page only where it is its
outline's size, both ways, within 3%.

Run from the culprits folder:  python3 round_0924_plates5.py
Built against main at d42f22c. The code change is applied with git's
three-way merge, so other chats' edits to the same files do not stop it; the
HANDOFF.md note is added at the top of its list, whatever else is in it.
Changes nothing if the code change would not apply, and says so if it is
already in.
"""
import base64, subprocess, sys, tempfile, os

DIFF = base64.b64decode("""
ZGlmZiAtLWdpdCBhL21hcC90ZXN0Lm1qcyBiL21hcC90ZXN0Lm1qcwppbmRleCA4MjI2YzI3Li43
MmI1ZGE2IDEwMDY0NAotLS0gYS9tYXAvdGVzdC5tanMKKysrIGIvbWFwL3Rlc3QubWpzCkBAIC0z
MjI4LDYgKzMyMjgsOCBAQCBjb25zb2xlLmxvZygiXG50aGUgQXRsYXMncyBvd24gbWFwcywgb24g
dGhpcyBtYXAgKDIyIFNlcHRlbWJlcikiKTsKICAgICAgICAgL2RlZiBwbGFjZV9ieV9iYXJcKC8u
dGVzdChweSkgJiYgL2xlblwoZm91bmRcWzFcXVwpIDwgMi8udGVzdChweSkgJiYgL0NPVU5UUllf
TEFCRUxfU0laRSA9IDlcLjAvLnRlc3QocHkpICYmICEvTUlOX1RPV05fUkFOSy8udGVzdChweSkp
OwogICBjaGVjaygi4oCmYSBjb3VudHJ5J3MgbmFtZSwgc2V0IGluIHRoZSBBdGxhcydzIGxhcmdl
ciB0eXBlLCBpcyBuZXZlciB1c2VkLCBhbmQgYSBwYWdlIHdpdGggbm8gdHdvIHRvd25zIGlzIHBs
YWNlZCBieSB0aGUgaG90c3BvdCBpdCBkcmF3cywgaW4gaXRzIGtleSdzIG93biBjb2xvdXIiLAog
ICAgICAgICAvc3BhblxbInNpemUiXF0gPj0gQ09VTlRSWV9MQUJFTF9TSVpFLy50ZXN0KHB5KSAm
JiAvZGVmIGtleV9jb2xvdXJcKHBhZ2VcKTovLnRlc3QocHkpICYmIC9kZWYgcGxhY2VfYnlfb3V0
bGluZVwoLy50ZXN0KHB5KSAmJiAvIm91dGxpbmVfY2hlY2tfa20iLy50ZXN0KHB5KSk7CisgIGNo
ZWNrKCLigKZvbmx5IHdoZXJlIHRoZSBkcmF3biBob3RzcG90IGlzIGl0cyBvdXRsaW5lJ3Mgc2l6
ZSwgYm90aCB3YXlzLCB3aXRoaW4gMyU7IG90aGVyd2lzZSBpdCBuZWl0aGVyIHBsYWNlcyBub3Ig
Y2hlY2tzIGEgcGxhdGUiLAorICAgICAgICAvT1VUTElORV9TSVpFX1RPTEVSQU5DRSA9IDBcLjAz
Ly50ZXN0KHB5KSAmJiAvc2FtZV9zaXplIGFuZCBybXMvLnRlc3QocHkpICYmIC9vdXRsaW5lXC5n
ZXRcKCJzYW1lX3NpemUiXCkgYW5kIGdvdFwuZ2V0XCgiYWZmaW5lIlwpLy50ZXN0KHB5KSk7CiB9
CiBjb25zb2xlLmxvZygiXG5yb3VuZCBvZiAyMiBTZXB0ZW1iZXIgKDUpOiB3aGF0IGNoZWNrLXNv
dXJjZXMgZm91bmQiKTsKIHsKZGlmZiAtLWdpdCBhL3BpcGVsaW5lL2F0bGFzX3BsYXRlcy5weSBi
L3BpcGVsaW5lL2F0bGFzX3BsYXRlcy5weQppbmRleCAyZjdlMWE3Li5iZmIzOTVjIDEwMDY0NAot
LS0gYS9waXBlbGluZS9hdGxhc19wbGF0ZXMucHkKKysrIGIvcGlwZWxpbmUvYXRsYXNfcGxhdGVz
LnB5CkBAIC0xMDcsNiArMTA3LDEzIEBAIENPVU5UUllfTEFCRUxfU0laRSA9IDkuMAogIyBib3gg
YXQgdGhlIHNjYWxlIGJhcidzIHNjYWxlLiBUaGUgZml0IGlzIGtlcHQgb25seSB3aGVuIHRoZSB0
d28gYm94ZXMgYXJlIHRoZQogIyBzYW1lIHNpemUgdG8gd2l0aGluIHRoZSBlcnJvciBhbGxvd2Vk
IGZvciB0b3ducy4KIE9VVExJTkVfVE9MRVJBTkNFID0gMTggICAjIDAtMjU1IHBlciBjb2xvdXIg
Y2hhbm5lbAorIyBUaGUgZHJhd24gYXJlYSdzIGJveCBtdXN0IGJlIHRoZSBvdXRsaW5lIGJveCdz
IHNpemUgdG8gd2l0aGluIHRoaXMgc2hhcmUsCisjIGJvdGggd2F5cy4gTWVhc3VyZWQgb24gMjQg
U2VwdGVtYmVyOiB3aGVyZSBib3RoIGNhbWUgd2l0aGluIDEuMyUKKyMgKENhdWNhc3VzLCBNYWRy
ZWFuIHdvb2RsYW5kcywgTWFwdXRhbGFuZCwgQ2VudHJhbCBBc2lhLCBTb3V0aHdlc3QgQ2hpbmEp
CisjIHRoZSBkcmF3biBob3RzcG90IHB1dCB0aGUgcGFnZSdzIG1pZGRsZSAxNyB0byA3MyBrbSBm
cm9tIHdoZXJlIHRoZSB0b3ducworIyBwdXQgaXQ7IHdoZXJlIHRoZXkgZGlkIG5vdCwgdGhlIGhv
dHNwb3QgcnVucyBvZmYgdGhlIHBpY3R1cmUgb3IgaXMgcGFpbnRlZAorIyBvdmVyIGJ5IHByb3Rl
Y3RlZCBhcmVhcywgYW5kIHRoZSBwbGFjZW1lbnQgbWVhbnMgbm90aGluZy4KK09VVExJTkVfU0la
RV9UT0xFUkFOQ0UgPSAwLjAzCiBPVVRMSU5FX1pPT00gPSAxLjUgICAgICAgIyBwaXhlbHMgcGVy
IHBhZ2UgcG9pbnQgd2hlbiByZWFkaW5nIHRoZSBwaWN0dXJlCiAjIFRoZSBmaXQgaXMgYSBzaW1p
bGFyaXR5OiBvbmUgc2NhbGUsIG9uZSB0dXJuIGFuZCBhIHNoaWZ0LCB3aXRoIHRoZSBwYWdlJ3MK
ICMgeSBydW5uaW5nIGRvd24uIFRoZSBlYXJsaWVyIHN0cmFpZ2h0LWxpbmUgKGFmZmluZSkgZml0
IGNvdWxkIGFsc28gc3RyZXRjaCwKQEAgLTQ5MSwxNCArNDk4LDE5IEBAIGRlZiBwbGFjZV9ieV9v
dXRsaW5lKHBhZ2UsIHdpZHRoX3B0LCBoZWlnaHRfcHQsIGJhcl9rbV9wZXJfcHQsIG91dGxpbmVf
Ym94KToKICAgICBybXMgPSBtYXRoLnNxcnQoKGR4ICogZHggKyBkeSAqIGR5KSAvIDIpCiAgICAg
c3Bhbl9rbSA9IGdyb3VuZF9rbSgqYXBwbHkoVCwgMCwgMCksICphcHBseShULCB3aWR0aF9wdCwg
MCkpCiAgICAgY29ybmVycyA9IFt1bm1lcmMoKmFwcGx5KFQsIHgsIHkpKSBmb3IgeCwgeSBpbiAo
KDAsIDApLCAod2lkdGhfcHQsIDApLCAod2lkdGhfcHQsIGhlaWdodF9wdCksICgwLCBoZWlnaHRf
cHQpKV0KLSAgICBrZXB0ID0gb25fZWFydGgoVCwgd2lkdGhfcHQsIGhlaWdodF9wdCkgYW5kIHJt
cyA8PSBzcGFuX2ttICogTUFYX0VSUk9SX1NIQVJFCi0gICAgcmV0dXJuIHsia2VwdCI6IGtlcHQs
Ci0gICAgICAgICAgICAicmVhc29uIjogIiIgaWYga2VwdCBlbHNlIGYidGhlIGRyYXduIGhvdHNw
b3QgYW5kIGl0cyBvdXRsaW5lIGRpZmZlciBieSB7cm1zOi4wZn0ga20gYXQgdGhlIGVkZ2VzLCBt
b3JlIHRoYW4ge01BWF9FUlJPUl9TSEFSRTouMCV9IG9mIHRoZSBwbGF0ZSdzIHtzcGFuX2ttOi4w
Zn0ga20iLAorICAgIHdyID0gKHB4MSAtIHB4MCkgKiBzIC8gKFgxIC0gWDApCisgICAgaHIgPSAo
cHkxIC0gcHkwKSAqIHMgLyAoWW4gLSBZcykKKyAgICBzYW1lX3NpemUgPSBhYnMod3IgLSAxKSA8
PSBPVVRMSU5FX1NJWkVfVE9MRVJBTkNFIGFuZCBhYnMoaHIgLSAxKSA8PSBPVVRMSU5FX1NJWkVf
VE9MRVJBTkNFCisgICAga2VwdCA9IG9uX2VhcnRoKFQsIHdpZHRoX3B0LCBoZWlnaHRfcHQpIGFu
ZCBzYW1lX3NpemUgYW5kIHJtcyA8PSBzcGFuX2ttICogTUFYX0VSUk9SX1NIQVJFCisgICAgcmV0
dXJuIHsia2VwdCI6IGtlcHQsICJzYW1lX3NpemUiOiBzYW1lX3NpemUsCisgICAgICAgICAgICAi
cmVhc29uIjogIiIgaWYga2VwdCBlbHNlIChmInRoZSBob3RzcG90IGRyYXduIG9uIHRoZSBwYWdl
IGlzIHt3cjouMmZ9IG9mIGl0cyBvdXRsaW5lJ3Mgd2lkdGggYW5kIHtocjouMmZ9IG9mIGl0cyBo
ZWlnaHQiCisgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIiAoYm90aCBt
dXN0IGJlIHdpdGhpbiB7T1VUTElORV9TSVpFX1RPTEVSQU5DRTouMCV9KTogaXQgcnVucyBvZmYg
dGhlIHBpY3R1cmUgb3IgaXMgcGFpbnRlZCBvdmVyIgorICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgaWYgbm90IHNhbWVfc2l6ZSBlbHNlIGYidGhlIGRyYXduIGhvdHNwb3Qg
YW5kIGl0cyBvdXRsaW5lIGRpZmZlciBieSB7cm1zOi4wZn0ga20gYXQgdGhlIGVkZ2VzIiksCiAg
ICAgICAgICAgICAiY29ybmVycyI6IFtbcm91bmQobG9uLCA1KSwgcm91bmQobGF0LCA1KV0gZm9y
IGxvbiwgbGF0IGluIGNvcm5lcnNdLAogICAgICAgICAgICAgImVycm9yX2ttIjogcm91bmQocm1z
LCAxKSwgIndpZHRoX2ttIjogcm91bmQoc3Bhbl9rbSksICJuYW1lcyI6IFtdLCAidHVybl9kZWdy
ZWVzIjogMC4wLAogICAgICAgICAgICAgInBsYWNlZF9ieSI6ICJ0aGUgc2NhbGUgYmFyIGFuZCB0
aGUgaG90c3BvdCBkcmF3biBvbiB0aGUgcGFnZSIsICJzY2FsZV92c19iYXIiOiAxLjAsCiAgICAg
ICAgICAgICAib3V0bGluZV9maXQiOiB7ImtleV9jb2xvdXIiOiBsaXN0KGNvbG91ciksICJwaXhl
bHMiOiBjb3VudCwgInBhZ2VfYm94IjogW3JvdW5kKHYsIDEpIGZvciB2IGluIChweDAsIHB5MCwg
cHgxLCBweTEpXSwKLSAgICAgICAgICAgICAgICAgICAgICAgICAgICAid2lkdGhfcmF0aW8iOiBy
b3VuZCgocHgxIC0gcHgwKSAqIHMgLyAoWDEgLSBYMCksIDMpLCAiaGVpZ2h0X3JhdGlvIjogcm91
bmQoKHB5MSAtIHB5MCkgKiBzIC8gKFluIC0gWXMpLCAzKX0sCisgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgIndpZHRoX3JhdGlvIjogcm91bmQod3IsIDMpLCAiaGVpZ2h0X3JhdGlvIjogcm91
bmQoaHIsIDMpfSwKICAgICAgICAgICAgICJ3b3JzdCI6IFtdLCAiYWZmaW5lIjogVH0KIAogCkBA
IC03MjIsNyArNzM0LDcgQEAgZGVmIG1haW4ob25seSwgc2hvdz1GYWxzZSk6CiAgICAgICAgICAg
ICAgICAgICAgKyAoZiIgKHsnLCAnLmpvaW4odG93bnMpfSkiIGlmIHRvd25zIGVsc2UgIiIpICsg
IjsgdHdvIGFyZSBuZWVkZWQifQogICAgICAgICBpZiBiYXI6CiAgICAgICAgICAgICBnb3RbInNj
YWxlX2Jhcl9rbV9wZXJfcHQiXSA9IHJvdW5kKGJhciwgNCkKLSAgICAgICAgaWYgb3V0bGluZSBh
bmQgb3V0bGluZS5nZXQoImNvcm5lcnMiKSBhbmQgZ290LmdldCgiYWZmaW5lIikgYW5kIGdvdCBp
cyBub3Qgb3V0bGluZToKKyAgICAgICAgaWYgb3V0bGluZSBhbmQgb3V0bGluZS5nZXQoInNhbWVf
c2l6ZSIpIGFuZCBnb3QuZ2V0KCJhZmZpbmUiKSBhbmQgZ290IGlzIG5vdCBvdXRsaW5lOgogICAg
ICAgICAgICAgIyBIb3cgZmFyIHRoZSB0b3duIHBsYWNlbWVudCdzIG1pZGRsZSBpcyBmcm9tIHRo
ZSBkcmF3biBob3RzcG90J3MKICAgICAgICAgICAgICMgcGxhY2VtZW50OiBhbiBpbmRlcGVuZGVu
dCBjaGVjayBvbiBib3RoLCBwcmludGVkIGFuZCBrZXB0LgogICAgICAgICAgICAgZ290WyJvdXRs
aW5lX2NoZWNrX2ttIl0gPSByb3VuZChncm91bmRfa20oKmFwcGx5KGdvdFsiYWZmaW5lIl0sIHcg
LyAyLCBoIC8gMiksICphcHBseShvdXRsaW5lWyJhZmZpbmUiXSwgdyAvIDIsIGggLyAyKSksIDEp
Cg==
""").decode()
NOTE = base64.b64decode("""
IyMgQXRsYXMgcGxhdGVzOiB0aGUgZHJhd24gaG90c3BvdCBvbmx5IGNvdW50cyB3aGVuIGl0IGlz
IGl0cyBvdXRsaW5lJ3Mgc2l6ZSAoMjQgU2VwdGVtYmVyLCBsYXRlcikKClRoZSBmaXJzdCBydW4g
d2l0aCBgcGxhY2VfYnlfb3V0bGluZWAgcGxhY2VkIE5ldyBDYWxlZG9uaWEgYW5kIFNvdXRod2Vz
dApBdXN0cmFsaWEgYWx0aG91Z2ggdGhlaXIgZHJhd24gaG90c3BvdHMgd2VyZSAwLjk2IHggMC42
MCBhbmQgMC45MiB4IDAuODkgb2YKdGhlaXIgb3V0bGluZXMnIHNpemU6IHRoZSBlZGdlIGVycm9y
IHdhcyBqdWRnZWQgYWdhaW5zdCB0aGUgd2hvbGUgcGxhdGUncwp3aWR0aCwgd2hpY2ggaXMgZmFy
IGxhcmdlciB0aGFuIGEgc21hbGwgaG90c3BvdC4gSXRzIGNoZWNrcyBvbiB0aGUgdG93bgpwbGFj
ZW1lbnRzIHNob3dlZCB3aGVuIGl0IGNhbiBiZSB0cnVzdGVkOiB3aGVyZSB0aGUgZHJhd24gYm94
IG1hdGNoZWQgdGhlCm91dGxpbmUgYm94IHdpdGhpbiAxLjMlIGJvdGggd2F5cyAoQ2F1Y2FzdXMs
IE1hZHJlYW4gd29vZGxhbmRzLCBNYXB1dGFsYW5kLApDZW50cmFsIEFzaWEsIFNvdXRod2VzdCBD
aGluYSkgaXQgcHV0IHRoZSBwYWdlJ3MgbWlkZGxlIDE3IHRvIDczIGttIGZyb20gdGhlCnRvd25z
JyBwbGFjZW1lbnQ7IGVsc2V3aGVyZSB0aGUgaG90c3BvdCBydW5zIG9mZiB0aGUgcGljdHVyZSBv
ciBpcyBwYWludGVkCm92ZXIgYnkgcHJvdGVjdGVkIGFyZWFzICh0aGUgU3VjY3VsZW50IEthcm9v
J3MgTmFtaWJpYW4gc3RyaXAgaXMgdW5kZXIKcHJvdGVjdGVkLWFyZWEgZ3JlZW4pIGFuZCB0aGUg
ZGlzdGFuY2VzIHJhbiB0byAxLDA5OCBrbS4gU28gYSBwbGFjZW1lbnQgb3IgYQpjaGVjayBieSB0
aGUgZHJhd24gaG90c3BvdCBub3cgbmVlZHMgYm90aCByYXRpb3Mgd2l0aGluIGBPVVRMSU5FX1NJ
WkVfVE9MRVJBTkNFYAooMyUpLiBPZiB0aGUgcGFnZXMgd2l0aCBubyB0d28gdG93bnMsIG9ubHkg
dGhlIENhcGUgKDEuMDA1IHggMC45OTQpIHBhc3Nlcy4KCg==
""").decode()


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True)


if git("rev-parse", "--show-toplevel").returncode:
    sys.exit("Run this from inside the culprits folder.")
with tempfile.NamedTemporaryFile("w", suffix=".diff", delete=False) as f:
    f.write(DIFF)
    path = f.name
try:
    if git("apply", "--reverse", "--check", path).returncode == 0:
        print("Code already applied.")
    else:
        res = git("apply", "--3way", path)
        if res.returncode:
            print(res.stderr.strip())
            sys.exit("Does not apply. Run git pull first; if it still refuses, send me this message.")
        print("Applied: pipeline/atlas_plates.py, map/test.mjs")
finally:
    os.unlink(path)
text = open("HANDOFF.md", encoding="utf-8").read()
if NOTE.splitlines()[0] in text:
    print("HANDOFF.md note already there.")
else:
    at = text.find("---\n\n")
    text = text[:at + 5] + NOTE + text[at + 5:] if at >= 0 else NOTE + text
    open("HANDOFF.md", "w", encoding="utf-8").write(text)
    print("Applied: HANDOFF.md")
